### ISSUE TITLE
Cannot add coinjoin account without Tor in dev mode

### ISSUE THREAD

**Issue by komret** [trezor/trezor-suite#10287]
Adding coinjoin account in dev mode is allowed without running Tor. However, when I try to do it, there is an error in console and the account is then loading forever.

Skipping Tor:
![Screenshot 2023-12-11 at 16 51 56](https://github.com/trezor/trezor-suite/assets/42465546/641dba68-353f-469e-b4c8-97408311d8d8)

Console error:
![Screenshot 2023-12-11 at 16 48 12](https://github.com/trezor/trezor-suite/assets/42465546/2de8cca7-2795-48fc-a053-48d875946cda)

**Comment by szymonlesisz** [comment]
this option should be allowed and makes sense only for regtest (maybe also for testnet) but you shouldnt be able to do it on btc

**Comment by komret** [comment]
It doesn't work for testnet or regtest either. If we don't fix it, I will remove the Skip button. @karliatto, do you know what's up?

**Comment by karliatto** [comment]
I am not sure. But my guess is that some changes in package @trezor/request-manager did not take into consideration this detail. 
This was done for making development faster without Tor and to allow to use local running instance of coinjoin middleware otherwise with Tor it is not possible. If that is still relevant that should be fix, if it is not relevant anymore might the `skip` option be removed.

**Comment by komret** [comment]
Looks like it is not needed anymore so I'll remove the button.
