### ISSUE TITLE
Connect explorer reports no connected device 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#10617]
**Describe the bug**
Connect explorer reports no connected device even it was already used.
It works as expected on staging explorer
`No connected devices`

**Screenshots**
<img width="1200" alt="Screenshot 2024-01-11 at 12 40 32" src="https://github.com/trezor/trezor-suite/assets/31506317/a62ca24c-92bb-4803-b4b1-64397d429f67">

**Comment by karliatto** [comment]
@bosomt After investigation, it happens because now connect-explorer is initializing TrezorConnect as not trusted in order to replicate the 3rd party integrations better.
You can go over it by 2 different ways:

1. Go to https://connect.trezor.io/9/#/settings -> check trustedHost and then click on Init Connect.
2. Go to https://connect.trezor.io/9/#/method/getAddress and click on "Get Address" and then in popup when asking for permission check "Don't ask me again" before giving the permission. As you can see bellow:

![image](https://github.com/trezor/trezor-suite/assets/5362163/e9f8bd1f-2948-4b83-be01-1cb77544aebe)


I think we can close this issue.

**Comment by Hannsek** [comment]
As this is expected we can close it, right? @karliatto
