### ISSUE TITLE
Dark mode is not selected as default even though the system is enabled for dark mode by default.

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#10643]
Steps to reproduce:
1. Set the dark mode as default in your mobile system (Android!)
2. Open the app
3. App does not reflect it

Corrent behaviour: app should respect the settings when colour mode is set to "system"

**Comment by PeKne** [comment]
I wasn't able the find a quick fix for this issue. The `react-native. Appearance.useColorScheme` hook always returns `light` in the Android version of the app. 

According to multiple sources, there should be an easy way to fix this issue by following [this tutorial](https://docs.expo.dev/develop/user-interface/color-themes/). Unfortunately, it works only for expo apps. Since this is a low-priority issue and we are planning to migrate to the expo soon, I will revisit this issue then.

**Comment by bosomt** [comment]
**QA OK**

app starts in dark mode when started for first time or after storage is wiped

- version 24.4.0 3550932
- Android 14 , Nothing phone 1
