### ISSUE TITLE
types, utxo-lib, unresolvable path 

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#10656]
needed for https://github.com/trezor/trezor-suite/issues/10389

<img width="932" alt="image" src="https://github.com/trezor/trezor-suite/assets/30367552/1cbc5c61-d66a-4c68-8be7-824c889e8cbb">

utxo-lib  npm package contains this line which can't be resolved out of monorepo. 

cc @Nodonisko for help

**Comment by Nodonisko** [comment]
This is really interesting issue that doesn't seems to be related to monorepo, because everything is happening inside of one package. I am not sure why but I guess it's related to fact that `d.ts` are special kind of files and it somehow conflict with tsconfig option `declaration: true`... don't ask me how this work exactly I did know that but I forget it because I didn't needed that :D

General rule is to avoid using `d.ts` files and just use `.ts`... I tried to rename it from `global.d.ts` to `global.ts` and it works as expected now.
