### ISSUE TITLE
After Update I get a Discovery error

### ISSUE THREAD

**Issue by TorIamOne** [trezor/trezor-suite#10724]
**Describe the bug**
After I enter my password for Trezor, I am asked to select between a wallet with a password or one without.  I select wallet without a password.  I then get the  "discovery errror".  I am unable to see any of my assets on the Ethereum blockchain. 

**Info:**

-   Remembered Wallet: yes
-   Suite Version: Trezor 24,1,2
-   Version 120.0.6099.218 (Official Build) (64-bit)
-   Windows 11 
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**
My assets should load

**Screenshots**
![treError](https://github.com/trezor/trezor-suite/assets/54206594/0c797e70-643e-4123-914c-e7028f9d218a)

**Additional context**
I have a backup computer.  I am getting the same error.  I think that ur latest updates broke something.

**Comment by mroz22** [comment]
dear reporter,
please be informed that running etherum node is so expensive that almost nobody does it and those who do require payments in exchange for this service. trezor runs its own nodes (and guarantees free usages for trezor users) but there are people in the internet who are unhappy paying for commercial service and resort  to abusing trezor nodes instead. btw you can check eth backends status here https://status.trezor.io/

although it is beyond our mind (speeking for developers at Trezor) what kind of utility ethereum really has, we are trying to do our best to ensure uninterrupted service but it is kind of cat and mouse play. So instead of actually building something useful for humanity, one group of developers is trying to figure out [how to keep ethereum backends alive](https://github.com/trezor/trezor-suite/pull/10723) while another group is trying to figure out how to overcome these measures.

so please be patient, my guess is that devops team is working hard to fix this 👍 let us know if the problem does not go away in matter of hours or maybe days. In the meantime let us contemplate together on the idea "what if there was some kind of internet money that everyone could run on a hardware with a price tag of couple of bucks 😄"

**Comment by hynek-jina** [comment]
Should be solved, just like https://github.com/trezor/trezor-suite/issues/10730#issuecomment-1903490538
