### ISSUE TITLE
Empower/Left nav rounding numbers

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#10815]
# Left nav rounding numbers

Only in the left nav, **not on detail**, could we:

- Remove decimals from FIAT value
- Round crypto value to 4-6 decimals (should be enough in most coins afaik, pls tell if I’m wrong)
    - Maybe `> 0.01 BTC` makes more sense for lower amounts?
    - Maybe `10M sats` , `12k sats` format is standard-enough in finance apps?
- Fiat value as a $30,000,000 → $3mil, $3M

I like the elipsis when account name overflows, **could we be re-rounding crypto value when fiat overflow?** (0.10462347 BTC → 0.105 BTC)

- Or at least do something like **0.104… BTC**?
- 
![image](https://github.com/trezor/trezor-suite/assets/152851523/1d135a51-2672-4e2b-aede-acadd59817f6)

![image](https://github.com/trezor/trezor-suite/assets/152851523/07d6f5e7-d23f-4091-a629-285cb4467af7)

**Comment by AdamSchinzel** [comment]
@Hermez-cz your opinion please?

**Comment by Hermez-cz** [comment]
For the MVP of the February release, let's please keep it simple:

1. Remove decimals from fiat value (instead of 900.11 CZK, round it to 900 CZK); If the fiat value will be below 1, but not 0, show "< 1 CZK" or "< $1"
3. Extend the width of the whole menu from 240 px to 280
4. Align the fiat value on the line with the account name
5. Keep the account name cropping as it is with the "..."
6. Do not crop the crypto value at all even if the fiat value will reach above the crypto value, it will fit comfortably

Design:
![image](https://github.com/trezor/trezor-suite/assets/88533514/6ea98b82-a6f5-4387-896c-4ce51b318ac7)

(we can introduce some smart rounding that will also help readability of the numbers post-mv)

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik  - please see the updated scope from Kuba.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: web 24.2.0 (02d6217963c3f8d49694fe1b6d90610aca848a55)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
 - OS: MacIntel
 - Screen: 1915x1244
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33
