### ISSUE TITLE
Setup new PIN modal on Model One

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1092]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1cc7816ae018fc5a4a00)

- [x] PIN mismatch ([Zeplin](https://sketch.cloud/s/AK1WY/a/WG3Zd2))
- [x] Close button (cross)

Static image for now. To be animated in the next version.

**Comment by wendys-cats** [comment]
**1.PIN SETUP (ENABLE/DISABLE PIN) on T1 bugs**
steps to reproduce NEW PIN SETUP:
1.open settings for T1, enable PIN
2.after entering PIN the second time, cancel during the check procces

**Expected behavior:**
There should not be an option to cancel during the check procces itself, while the device is proccesing the input. 

**Actual behavior**
There is a cancel button that works (to some degree) and you can interrupt the PIN setup wth it, while the device is proccesing the input. This results in entering the pin three times when you want to enable PIN again.

**steps to reproduce DISABLE PIN**
1. open settings to disable PIN (you need to have it enabled in the first place)
2. after entering PIN, cancel during the check procces

**Expected behaviour:**
There should not be an option to cancel while the device is proccesing the input. 

**Actual behaviour:**
There is an interactable button that works (to some degree) and you can interrupt the Disable PIN action. This allows you to disable the PIN next time without having to enter the PIN again. 

**video :**
https://drive.google.com/file/d/1RjqqZuKewLHf_ipBrjx5-zYpGOG_7pmB/view

**Comment by wendys-cats** [comment]
**2.PIN SETUP CANCEL bug**
T1 device
steps to reproduce:
1. open device settings to enable PIN
2. enter PIN the first time
3. cancel the action

**Expected behavour:**
Canceling the action in suite will also cancel the PIN setup on the device screen 

**Actual behaviour:**
Device will show the Enter pin screen (with random number positioning) even after canceling it in suite. This is a regression, fix please.

**Comment by mroz22** [comment]
it's not really a bug. It's just not implemented. We either need to wait for bridge update or add this to trezor connect.

**Comment by mroz22** [comment]
btw try it with the latest bridge. it should work as expected. what about @matejzak shall we close?

**Comment by glacierbits** [comment]
As discussed with @mroz22, we will remove the cancel from loading (as described in 1. PIN SETUP above).

**Comment by wendys-cats** [comment]
**1.PIN SETUP (ENABLE/DISABLE PIN) on T1 bugs**
steps to reproduce NEW PIN SETUP:
1.open settings for T1, enable PIN
2.after entering PIN the second time, cancel during the check procces

**Expected behavior:**
No misdirection fro Suite as to the current PIN protection status.

**Actual behavior**
If the user clicks anywhere while the device is processing the input, Suite will not change the radiobutton to the current PIN protection status, and will also show the notification "Error: pin-cancelled", even though the device has successfully set up PIN protection.

**video for enable PIN:** https://drive.google.com/file/d/1arraNLBzJoymQLyszDup_hVo6-1jP3uU/view

**steps to reproduce DISABLE PIN**

open settings to disable PIN (you need to have it enabled in the first place)
after entering PIN, cancel during the check procces

**Expected behaviour:**
No misdirection fro Suite as to the current PIN protection status.

**Actual behaviour:**
If the user clicks anywhere while the device is processing the input, Suite will not change the radiobutton to the current PIN protection status, and will also show the notification "Error: pin-cancelled", even though the device has successfully set up PIN protection.

**video for disable pin:** https://drive.google.com/file/d/1hpEY02j5SfxgWIIZZBd2Ehr4BBWbHvkZ/view

**Comment by wendys-cats** [comment]
@mroz22 tried with the latest bridge (2.0.28).  The second issue - **PIN SETUP CANCEL bug** still persists in desktop app (nixos version, 1.0.0). BUT fixed on browser version, thank you!

**Comment by mroz22** [comment]
Am I missing something here? Just tried it now and while pin loading, it cannot be canceled in UI which is what we want right? 
of course I might be retarded. But I am closing this for now. Sorry if I am retarded.

**Comment by wendys-cats** [comment]
@mroz22 you cancel the Enable PIN action when the modal pops up second time with Cancel (X) button. 
After this, Suite responds with "Error: pin-cancelled", but the device will still be showing the matrix for PIN modal. Just checked it on Suite application (for NixOS), latest version.
