### ISSUE TITLE
Importing ETH accounts without checksum validation

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#10940]
There seems to be a bug that allows importing Ethereum addresses into the Trezor Suite mobile app without passing the checksum. Consequently, you can send funds to this address from exchanges that don't perform checksums. This issue can lead to lost funds, especially when users import addresses from images using OCR on their phones.

![Image](https://github.com/trezor/trezor-suite/assets/5837757/4f09540c-7a52-4cbd-8b49-ba2f8f76a09f)

invalid address example: **0x22a5d8253fACffe4f5eA111cb11cCE1A2887b1b9**

**Comment by bosomt** [comment]
**QA NOK**

account https://eth1.trezor.io/address/0x22A5D8253facFfe4F5Ea111cb11cCE1A2887b1b9 is still imported without any kind of warning or failing

Android 14 - Nothing Phone 1
24.3.1 (24) dev version 6e9d8d6

see screenshot of imported example address



![Image](https://github.com/trezor/trezor-suite/assets/31506317/5d395486-5036-4fa0-b478-f562174d1ba1)

**Comment by PeKne** [comment]
How did you import it? By scanning the QR code?

**Comment by bosomt** [comment]
Scanning QR code from https://eth1.trezor.io/address/0x22A5D8253facFfe4F5Ea111cb11cCE1A2887b1b9

**Comment by PeKne** [comment]
https://github.com/trezor/trezor-suite/assets/26143964/3c87dfa7-f35c-41a5-988d-a16d63ec1f7a

@bosomt  I am unable to reproduce it. See the demo attached. Could you test it again?

**Comment by bosomt** [comment]
LOL i dont know what im doing wrong
imported via QR and via text both success :)

EDIT: but when i try to scan QR from this attached screenshot i get not valid address https://github.com/trezor/trezor-suite/issues/10940#issue-2108231280


Latest dev version just installed 24.3.1 (29) 


https://github.com/trezor/trezor-suite/assets/31506317/d4c56982-e83b-4c40-8d06-c51a31e96763

**Comment by PeKne** [comment]
Ok, now i got it. You were testing it with a valid address... The ETH addresses are case sensitive. The address that is attached in this issue `0x22a5d8253fACffe4f5eA111cb11cCE1A2887b1b9` (5th character is `a`) is invalid, even desktop say so:

![Image](https://github.com/trezor/trezor-suite/assets/26143964/808ed2c9-373a-4ee5-a342-12e84f0a4469)

On the other hand the address that you used `0x22A5D8253facFfe4F5Ea111cb11cCE1A2887b1b9` (5th character is `A`) is perfectly valid ETH address and works both for mobile and desktop:

![Image](https://github.com/trezor/trezor-suite/assets/26143964/1df8d4f5-8eeb-4f62-96fb-af1e3d750c9f)


So I believe the implementation of this issue is all right.

**Comment by bosomt** [comment]
**QA OK**

24.3.1 cc7d18e
