### ISSUE TITLE
Polygon: Send form info banner should have more subtle design

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#10969]
The new informational banner will eventually become only annoying/redundant for users that will learn the shown facts by heart and it might be annoying for experienced users right away. Especially on Ethereum, but also on Polygon.

Therefore we have created a new more subtle design: https://www.figma.com/file/Mhj56O746tbFxd1vxnWqlC/Invity-in-Trezor-Suite?type=design&node-id=1748%3A32470&mode=design&t=QMdek8uZSUtBOwpK-1

**Comment by LukasRada** [comment]
Does the icon inside the banner need to be in blue variant of the crypto currency? I suggest to use current logo otherwise there should be a blue variant of the original crypto currency logo for other crypto currencies as well (for any ethereum type crypto currency). Just a suggestion for you guys to consider.
![image](https://github.com/trezor/trezor-suite/assets/7394177/45babec1-d823-4156-b1cd-333c728437ea)

Let me know.
Cc: @Hermez-cz

**Comment by Hermez-cz** [comment]
Please update the banner color in dark mode to the darker blue color intended for dark mode and respecting the elevation. https://www.figma.com/file/Y2E8dcdNYrSMGIVRjYFXKp/%5Bs2.0%5D-Components?type=design&node-id=57%3A30791&mode=design&t=nObLWnMATUYrC4I5-1

<img width="896" alt="image" src="https://github.com/trezor/trezor-suite/assets/88533514/ab34b7c7-ee23-4643-a8f4-9c02dbadc4a2">

**Comment by bosomt** [comment]
**QA OK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/66b19871-2831-43b8-9df6-3368c7c93c42)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c3d6a0ae-0b59-4f9f-a96b-8cd19baca49e)



**Info:**
 - Suite version: desktop 24.3.1 (e1bbd6e83b8d33b64dd562a137b279c66c902350)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.3.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.3 regular (revision 2c7cc6e0255dee2339b445b5551eaffb88dbd1b4)
 - Transport: BridgeTransport 2.0.33
