### ISSUE TITLE
BTC only FW

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1110]
Add option to install BTC only FW in Onboarding.

**InVision** [here](https://projects.invisionapp.com/d/main/default/?origin=v7#/projects/prototypes/18954259)

**Comment by mroz22** [comment]
finito

**Comment by bosomt** [comment]
i can choose BTC FW but if fails for model One

![image](https://user-images.githubusercontent.com/31506317/78755677-d7fe6a80-7979-11ea-8b8d-064784e9b239.png)

**Comment by mroz22** [comment]
please provide info about your current setup. to start with something, current firmware and bootloader version would help.

**Comment by bosomt** [comment]
both TT and T1 broken in latest web suite

recored video for both devices here: https://www.youtube.com/watch?v=2CfiMl3bqcs&feature=youtu.be

latets bootloaders 1.8.0 and 2.0.3
latets chromium and latest unstable nixos

**Comment by bosomt** [comment]
same result with full feature firmware, looks like whole FW loading is broken

**Comment by mroz22** [comment]
could you please try here? 
https://github.com/trezor/trezor-suite/pull/1478

there are possibly two problems: 
- [x] wrong url for downloading firmwares (which should be fixed in the link above)
- [ ] maybe "overengineered" sanity checks on which firmware should be installed that could probably happen if device has some custom firmware setup, eg. you downgraded your firmware or something like this. This may result in "no suitable firmware found error". I shall fix that asap but it does not relate to btc only firmware

**Comment by bosomt** [comment]
i see in browser log 403 error forbidden :)
iframe.bda111c3b771225a9cfb.js:2 GET https://wallet.trezor.io//data/firmware/1/trezor-1.8.3.bin 403

**Comment by mroz22** [comment]
thats the // problem, but it should be fixed in `firmware-related` branch. did you try it there, right?

**Comment by bosomt** [comment]
that branch https://suite.corp.sldev.cz/suite-web/firmware-related/ says: 

**Ups. Something went wrong with this fw update. Ended up with error: Invalid parameters: Parameter "version" has invalid type. "array" expected.**

when i try tload fw

**Comment by bosomt** [comment]
BUT, full feature FW 1.8.3 is installed as expected

after that :
**Excellent, fw update successful, only 6% of user share this experience!
**

so only 6% users is able to install fw ? :)

**Comment by mroz22** [comment]
closed in favour of https://github.com/trezor/trezor-suite/issues/1611
