### ISSUE TITLE
XRP reporting All backends are down

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11148]
**Describe the bug**
```
XRP Testnet: All backends are down
XRP: All backends are down
```

Both coins are not discoverable on 24.2.1 version.
Same app and browser version.
Reproduced on multiple computers.
Checked and both production and rc are using same backend urls.
production works as expected. 

**Info:**
 - Suite version: desktop 24.2.1 (d1eda6c68c4619a7060f1fcc8033ee44c4a94a03)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.2.1 Chrome/118.0.5993.129 Electron/27.0.4 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.6.4 regular (revision 42e9ed0e09033d474dee1a560fe5870646fa440e)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
![image](https://github.com/trezor/trezor-suite/assets/31506317/52fe74cf-59be-44c4-81f1-35f2eca9b61f)

**Comment by mroz22** [comment]
cc @hynek-jina 
![image](https://github.com/trezor/trezor-suite/assets/30367552/8614920a-005b-40ee-90f9-e62732499172)

**Comment by marekrjpolak** [comment]
Observation: When you start Suite with only XRP active, it works; but then the other coins don't, after you turn them on.

Cause: It happens since bumping `ws` dependency to `8.16.0` (bd1e5ec81b1ef2a53dc49271794edfbd75232aa1), because (deprecated) `ripple-lib` uses it in `^7.2.0`. Also, that's why it doesn't happen on web as in that case native WebSocket is used. Still don't know the exact reason though.

Solution: Apart from removing XRP ( :pray: ) or migrating from `ripple-lib` to `xrpl` ( :unamused: ), still don't know. Working on it.

**Comment by MiroslavProchazka** [comment]
Interesting. @komret was updating dependencies last week, dunno if that could be connected to that somehow. 
Couldn't we just decrease the  `ws `dependency back to the state that it was before?

**Comment by marekrjpolak** [comment]
No, I'm the one who bumped `ws`, even before Empower was merged. Fix is on the way.

**Comment by matejkriz** [comment]
note for @trezor/qa please test also Solana with this fix, we ran into a similar problem there in December https://satoshilabs.slack.com/archives/C059ZS5T24C/p1702380252030339?thread_ts=1702311810.887369&cid=C059ZS5T24C

**Comment by STew790** [comment]
**QA OK**
Already in EAP and tested.
