### ISSUE TITLE
Switch devices: Styling

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1114]
**Zeplin** [here](https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6fd8cbe83f201c1f35ba)

Modal (accessible from the primary menu) for switching between wallets and devices.
When accessed from context of Settings, wallets listed under each Device are to be disabled.

Device statuses [in Notion.](https://www.notion.so/satoshilabs/464ff236a01547f39a274a8a931b15c3?v=14f48a33f89b4377ab087c99dc224b68)

**Comment by wendys-cats** [comment]
1.Issue with modal for switching devices and wallets (from main menu)

Expected behaviour
Means to switch/choose between connected devices 

Actual behaviour
There is no option for actually switching between the connected devices (no button. f.e.).

**Comment by wendys-cats** [comment]
2.issue with modal for switching devices and wallets (from main menu)

Expected behaviour
The currently active device (and wallet) will be visibly recognizable in the modal when there are several devices connected at once.

Actual behaviour
When there are several connected devices, there is no way to distinguish the currently active one.

**Comment by glacierbits** [comment]
Partially improved by #1371. Device selection is being handled in design process and implemented in the second release.
