### ISSUE TITLE
Biometrics always enabled after fresh reinstall of app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#11854]
**Describe the bug**
See video.
Im not able to reproduce it on develop version on Android or on "production" version on iPhone

**Info:**

-   Mobile Suite Version: 24.4.1/ 9e244b5
-   OS: Android, 14 , Nothing phone 1

**How to reproduce**

1.Disable bio metrics
2. Uninstall app
3. Install app
4. Start app
5. Bio metrics enabled

**Screenshots**

https://github.com/trezor/trezor-suite/assets/31506317/bc5de169-6501-429b-bfa2-72278d886c1f

**Comment by matejkriz** [comment]
This has been caused by Android auto-backup feature https://developer.android.com/guide/topics/data/autobackup

Steps to reproduce:
- Enable biometrics in the app
- Go to device Settings > Google > Backup
- Click on Backup Now on Google One and wait till the backup finished
- Go to the Suite app and disable biometrics or change any settings
- Reinstall Suite app
- You'll get the data back from that Google One backup

**Comment by matejkriz** [comment]
Biometrics, discreet mode and theme are stored in unencrypted storage that can be retrieved from the backup, but rest is encrypted so restoring from backup is not possible anyway, so we will disable the auto-backup feature for our app completely.

**Comment by bosomt** [comment]
**QA OK**

- version 24.4.0 3550932
- Android 14 , Nothing phone 1
