### ISSUE TITLE
Coinmarket - payment method filter bug

### ISSUE THREAD

**Issue by adderpositive** [trezor/trezor-suite#12141]
## Info
After selecting payment method in coinmarker filter should not be displayed offer with errors

**Comment by bosomt** [comment]
Not sure if this is expected outcome when you filter offers that contained only errors like Google or Apple pay.
Otherwise filtering of offers with errors works as expected  

![image](https://github.com/trezor/trezor-suite/assets/31506317/03119e74-07df-4a41-9fe6-7e3d17b1465e)

**Info:**
 - Suite version: web 24.5.0 (a33ad459d3d919d5b6ac4210c9d876298ee8947a)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0
 - OS: MacIntel
 - Screen: 2144x1206
 - Device: Trezor T2B1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
cc @marek-andrsk
