### ISSUE TITLE
Countable: 1 day instead of 1 days

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#12339]
UI shows "1 days", when "1 day" should be shown.

![Image](https://github.com/trezor/trezor-suite/assets/216917/ffb41e07-8d14-4a27-b1bf-088e4b60311d)

**Comment by bosomt** [comment]
**QA NOK**



![Image](https://github.com/trezor/trezor-suite/assets/31506317/c4c8cbc9-3c9b-4a21-904b-6d8e087396cc)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/da390459-850a-4450-933f-9adcd2827d1b)



**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 regular (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
@bosomt please check again

**Comment by bosomt** [comment]
One more day to check it :)
<img width="299" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/80f542cd-5063-4482-9e6c-2a9e37f29796">

**Comment by bosomt** [comment]
I see 1 days during staking ..

![Image](https://github.com/trezor/trezor-suite/assets/31506317/cdc241f6-88d1-4b23-bbaa-06a9d4d76899)

**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
@tomasklim this issue is fixed already, but there is same issue in staking confirmation modal , do you want me to create follow up issue ?



![Image](https://github.com/trezor/trezor-suite/assets/31506317/b521c7a1-da63-4192-8381-aa100033a768)


**Info:**
 - Suite version: desktop 24.6.1 (9d8fc586194255068350256208cbd828cc880876)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33

**Comment by bosomt** [comment]
Follow up created here https://github.com/trezor/trezor-suite/issues/12893
