### ISSUE TITLE
@trezor/connect-common@npm:0.0.32 No candidates found

### ISSUE THREAD

**Issue by msteiner96** [trezor/trezor-suite#12412]
Hey, could you please let me know where the 0.0.32 went? I have some dependencies that don't longer work right now.

**Comment by MiroslavProchazka** [comment]
cc @karliatto

**Comment by karliatto** [comment]
@msteiner96 If you have a project that tries to use @trezor/connect-common@npm:0.0.32 watch out, you are probably using beta version of you npm dependencies.

The version 0.0.32  of `@trezor/connect-common` is only used by `@trezor/connect-web`, `@trezor/connect-webextension` and `@trezor/connect` that are tagged with `beta` in NPM. They should not be updated automatically by any package manager.

Anyway we are planning new beta release today or tomorrow that will fix that issue even for someone using beta tagged NPM, which is obliviously not recommended unless you want to try some latest feature, and run the risk of using a non-stable version.

And if I just try to run `yarn add @trezor/connect-web` it installs "@trezor/connect-common@0.0.31" which is right because 0.0.31 is tagged as latest in NPM and is the current stable release.

Could you explain a bit further how did you get to use `@trezor/connect-common@npm:0.0.32` ?
