### ISSUE TITLE
connect-webextension proxy - revise desing

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#12731]
- I believe that [init](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/proxy/index.ts#L45) should be hadled implicitly inside `call`
- does manifest method make sense here? 
- does cancel method do everything it should?
- if init was not call, and channel not set, call method throws on the first attempt to access channel, this is caught, but in the catch block later on obviously not. https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/proxy/index.ts#L95
- add default `connectSrc`. it is not set and 3rd parties have to do stuff like this https://github.com/RabbyHub/Rabby/blob/59e06afc722e69c6f609654c1f5ccba1f710710f/src/background/service/keyring/eth-trezor-keyring/trezor-offscreen-bridge.ts#L30
- lib/index.js does not contain inlined content-script. so simply importing from @trezor/connect-webextension forces you to use version where you have to vendorize content script. 

related to #12717

**Comment by karliatto** [comment]
Regarding the proxy:
After talking about this with @martykan we came to the conclusion that the proxy is out of the scope of TrezorConnect and we should focus on making connect-webextension work nicely in service worker with popup with ES modules.

**Comment by karliatto** [comment]
> I believe that [init](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/proxy/index.ts#L45) should be hadled implicitly inside call

[init](https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/proxy/index.ts#L45) requires settings in functions arguments and we do not have that in call method if init has not been called before.

> lib/index.js does not contain inlined content-script. so simply importing from @trezor/connect-webextension forces you to use version where you have to vendorize content script.

Should be fixed by this PR https://github.com/trezor/trezor-suite/pull/12761

> add default connectSrc. it is not set and 3rd parties have to do stuff like this https://github.com/RabbyHub/Rabby/blob/59e06afc722e69c6f609654c1f5ccba1f710710f/src/background/service/keyring/eth-trezor-keyring/trezor-offscreen-bridge.ts#L30

> if init was not call, and channel not set, call method throws on the first attempt to access channel, this is caught, but in the catch block later on obviously not. https://github.com/trezor/trezor-suite/blob/develop/packages/connect-webextension/src/proxy/index.ts#L95

Isn't `init` required in all the TrezorConnect implementation?

That part of the Rabby code is running in the service worker and using the [parseConnectSettings](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/data/connectSettings.ts#L82) that will add `DEFAULT_DOMAIN` if connectSrc is not provided, but they decided to provide it explicitly.

**Comment by Hannsek** [comment]
Can we close this one as not planned?
