### ISSUE TITLE
Icons inside tabs in trade section are not clickable

### ISSUE THREAD

**Issue by AdamSchinzel** [trezor/trezor-suite#12819]
**Describe the bug**
Icons are also a part of tabs that together make the vertical navigation inside trade section. But clicking on the icon does nothing.

**How to reproduce**

1. Go to trade section
1. Click on icon inside any tab to change page

**Expected behavior**
Clicking the icon should also change the page.

**Screenshots**

https://github.com/trezor/trezor-suite/assets/66002635/c6d74532-aef7-4c0c-8dd5-2dedb5bfbfa1

**Comment by tomasklim** [comment]
@bosomt please check if still actual

**Comment by bosomt** [comment]
**QA OK**

fixed in new coinmarket design


**Info:**
 - Suite version: web 24.9.0 (07febcf5a71e39819d2e06860cba4e2b608c2de3)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 bitcoin-only (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33
