### ISSUE TITLE
EVM Tokens / Add token (debug)

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#12864]
I think it makes sense to move `Add token` to tokens section (just debug mode)

![Screenshot 2024-06-12 at 13 33 56](https://github.com/trezor/trezor-suite/assets/33235762/29c3af7a-a2dd-4f37-94b0-1046c451c9d8)

We can simplify texts as it is just for testing purposes
![Screenshot 2024-06-12 at 13 32 27](https://github.com/trezor/trezor-suite/assets/33235762/bc56b3de-2893-4685-858e-284c5dae174b)

Check if it works for ETC

**Comment by bosomt** [comment]
**QA OK**

- add button hides/shows as i enable/disable debug mode
- i was able to add random ERC20 token
- nothing happens when you add staking contract as token only `Token added` notification 🙏  

**Info:**
 - Suite version: web 24.7.0 (87a1ef738cd9557e8d447be74b6eb438d1691c8d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
