### ISSUE TITLE
v24.6.1 Not Marked as Latest, Causing Homebrew Livecheck Issues

### ISSUE THREAD

**Issue by nekofar** [trezor/trezor-suite#12913]
I've noticed that [v24.6.1](https://github.com/trezor/trezor-suite/releases/tag/v24.6.1) was released a couple of days ago, but it hasn’t been marked as the latest. This is causing Homebrew livecheck to miss the newest version. Is there a specific reason why this version hasn't been marked as the latest? If it was an oversight, could it be updated to reflect the latest status? This would help ensure everyone is on the most current version. Thanks for your attention to this matter!

https://github.com/Homebrew/homebrew-cask/pull/176917

**Comment by martykan** [comment]
Unfortunately, we've had to make some changes to our release system due to complications with our new Windows signing cert. As part of a workaround, we had to stop tagging the latest release on GitHub. 

Information about the current release can be obtained from: https://data.trezor.io/suite/releases/desktop/latest/latest-mac.yml
This is in Electron Bulder format, so I would suggest switching to this livecheck strategy:

```
livecheck do
  url "https://data.trezor.io/suite/releases/desktop/latest/latest-mac.yml"
  strategy :electron_builder
end
```

**Comment by tsusanka** [comment]
Seems like already done: https://github.com/Homebrew/homebrew-cask/pull/176917/commits/8e3f75e8cfeb83ddbb875db7070c9316dc81f47e . Thanks @krehel and @bevanjkay.

I think we can close here.
