### ISSUE TITLE
Fiat tags: Blue is the new black

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1312]
Grey _fiat balance tags_ are being confused for _crypto rates_. Let's fix that:

**[Zeplin](https://app.zeplin.io/project/5e4e7717ae5dfd7c427a5a28/screen/5e6f3d9561a04817f9f6974b)**

**Comment by slowbackspace** [comment]
<img width="371" alt="Screenshot 2020-03-16 at 18 40 29" src="https://user-images.githubusercontent.com/6961901/76785375-9da81000-67b5-11ea-9f3f-6e9f991513a4.png">
price ticker is still grey. is that want we want?
also what about grey/dark-grey (current rate/historical rate) badges in transactions detail modal, what should be used instead of "dark-grey"?

<img width="737" alt="Screenshot 2020-03-16 at 18 43 38" src="https://user-images.githubusercontent.com/6961901/76785621-11e2b380-67b6-11ea-992b-d1cb0d8d4ed7.png">

**Comment by glacierbits** [comment]
@slowbackspace Have a look at the Zeplin link in the description: It's about the fiat conversion.

**Comment by slowbackspace** [comment]
<img width="292" alt="Screenshot 2020-03-16 at 18 53 54" src="https://user-images.githubusercontent.com/6961901/76786420-7f431400-67b7-11ea-92e5-4609a45c9a22.png">
this looks to me pretty much like fiat conversion

(taken from the transaction detail above)

**Comment by glacierbits** [comment]
Ah sorry, didn't see the second screenshot! 

(1) Yes, the price (rate) remains the same grey as to differentiate it from the fiat "balance".
(2) We will come up with something for the "dark grey". Thanks for the heads-up.

**Comment by glacierbits** [comment]
@vladimirvolek Can you please make the fiat to crypto tags blue on Dashboard as well? Thanks! 
<img width="598" alt="Screen Shot 2020-03-18 at 17 10 56" src="https://user-images.githubusercontent.com/29627086/76982025-9874cd80-693b-11ea-80dd-be26063a29c0.png">
