### ISSUE TITLE
Unify data-test 

### ISSUE THREAD

**Issue by jvaclavik** [trezor/trezor-suite#13247]
use `data-test-id` everywhere instead of `data-test` and `dataTest`. Right now it's dataTest in DS components and `data-test` everywhere else

It needs to be re-configurated also in tests:
- cypress: `getTestElement` in `packages/suite-web/e2e/support/utils/selectors.ts`
- playwright: `testIdAttribute` in `packages/suite-desktop-core/e2e/playwright.config.ts`

**Comment by Lemonexe** [comment]
The PR is ready for CR (refactoring `data-test` to `data-test-id`).

Out of curiosity I briefly researched what is the usual convention,  and seems to be `data-testid` instead of `data-test-id`.   

The convention is set by some testing frameworks such as [testing-library](https://github.com/testing-library/testing-library-docs/issues/746), which [we do use](https://github.com/trezor/trezor-suite/blob/7acb7caddfc96c7d55f4047d6bc92e77e00199ec/packages/suite/package.json#L122).

That being said, the choice is completely arbitrary, both work, and `data-test-id` is much cleaner, so FWIW I'd prefer that.

**Comment by Lemonexe** [comment]
After discussion with QA, it was done as `data-testid` after all
