### ISSUE TITLE
Incorrect button states

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1328]
Buttons look like "clicked" by default. 

Receive, Show log, and some other place I forgot :) 

<img width="671" alt="Screen Shot 2020-03-14 at 18 38 22" src="https://user-images.githubusercontent.com/29627086/76984738-89901a00-693f-11ea-9d6e-b8e0d6081017.png">

<img width="963" alt="Screen Shot 2020-03-18 at 11 01 55" src="https://user-images.githubusercontent.com/29627086/76984742-8bf27400-693f-11ea-8005-a4c34b042fb8.png">

**Comment by vladimirvolek** [comment]
What is the solution here? You can see all the buttons here - https://suite.corp.sldev.cz/components/develop/?path=/story/buttons--all

The "grey one" is our secondary button. Should we delete the secondary button and make all the buttons primary (green)?

**Comment by glacierbits** [comment]
@vladimirvolek Sorry, not what I meant. Both the grey and green button acts as if they have been clicked by default, which means I have opened the modal and they have the border around them and are darker as if they have been pressed even though I haven't touched them yet.

**Comment by slowbackspace** [comment]
![css](https://i.chzbgr.com/full/7588073728/h78549C5D/not-sure-if-i-hate-css-or-i-hate-designers)

**Comment by slowbackspace** [comment]
k, so I toned down focus styles (thats what you see) so now it is same as hover styles.

Originally I completely removed the focus from the buttons in modals you mentioned, but I came to conclusion it is actually correct behaviour. Since it is the only button, the browser automatically gives focus on it. So you know that when you hit the enter (or spacebar, idk which one) it triggers the button click.  Check it out at https://suite.corp.sldev.cz/suite-web/fix/autofocus-button-modal (should be deployed 15 mins from now)

If new styles are not good enough I can mark some div in the modal as tabbable so the focus won't be on the button, meaning you won't see any special styles until you hover over it (or use tab).

**Comment by glacierbits** [comment]
Cleared storage, opened Onboarding

<img width="465" alt="Screen Shot 2020-03-26 at 15 55 57" src="https://user-images.githubusercontent.com/29627086/77661217-a13c5380-6f7a-11ea-9d17-a40f8d638ebb.png">

**Comment by slowbackspace** [comment]
> Cleared storage, opened Onboarding
> 
> <img alt="Screen Shot 2020-03-26 at 15 55 57" width="465" src="https://user-images.githubusercontent.com/29627086/77661217-a13c5380-6f7a-11ea-9d17-a40f8d638ebb.png">

should be fixed by https://github.com/trezor/trezor-suite/commit/631a9d6a4ebc35e829b7e8a3775cf0d78850ba80
