### ISSUE TITLE
Opening device switcher immediately on startup ("Click to discover wallet")

### ISSUE THREAD

**Issue by martykan** [trezor/trezor-suite#13396]
**Describe the bug**
When opening the device switcher immediately after starting Suite, before discovery starts, it goes into a state where it doesn't load the accounts and only shows "Click to discover wallet", which actually doesn't do anything. 

**Steps to reproduce:**
1. Have a Trezor connected and set up, but don't enable view-only
2. Re-start Suite
3. Immediately click on the device switcher menu

**Info:**
 - Suite version: desktop 24.7.2 (3282fe8f6f491e024c0cc9cae99f3085c229c96c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.7.2 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1800x1169
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Expected result:**
I click on "Click to discover wallet" and it restarts discovery.

**Actual result:**
Nothing happens upon clicking. 

**Screenshots:**
<img width="484" alt="Screenshot 2024-07-17 at 14 37 17" src="https://github.com/user-attachments/assets/7ecb0340-426e-45aa-8302-81b28f7478c7">

**Comment by STew790** [comment]
**QA NOK**
This is still an issue. It also happens when you go to Settings and you want to activate some coin for example, it won't even show you the "Activate coins" button.

**Info:**
 - Suite version: web 24.11.0 (258ab9664fb9cddbc0bd28638f00b56583b15e1d)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.33

**Comment by tomasklim** [comment]
It started happening more often recently.

I think it makes sense to show `Activate coins` button when ⬇️ 
![image (3)](https://github.com/user-attachments/assets/68ac9a24-85cf-4343-a047-d0553d335b61)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.1 (a8ae3ff1ea456fa59a46323fda34353c088bc294)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.1
