### ISSUE TITLE
suite-desktop start-on startup

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#13476]
consider implementing suite-desktop auto start. something like electron app.openAtLogin or similar. to be discussed. 

it is useful when we want to use suite-desktop as the source of bridge for 3rd parties.

**Comment by bosomt** [comment]
**QA OK**

checked here https://www.notion.so/satoshilabs/Suite-app-autostart-b91229da95834890892e04b235a2c474?pvs=4

- starts after enabling and restarting OS
- does not start after disabling and restarting OS
- hidden behind debug 

- im not able to delete when autostart enabled
- updtae of app needs to be implemented, tested update 24.8.1 > 34.8.1 with autorun enabled, app was not updated during restart and needed to be started again manually, probably due to one more version running in background
-
