### ISSUE TITLE
Enable to add Cardano, Solana, Ethereum derivation paths under debug mode

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#13733]
Allow user to add cardano, solana, ethereum accounts which are not shown when empty. Mainly for testing purposes

**Comment by bosomt** [comment]
found three possible issues
- all account types have same name when adding, you can not distinguish between them /ok for me for testing purposes/
- im not able add new accounts if i add default account first
- new derivation paths are only available for one testnet

### ETH Holesky 
- derivation paths **not** available @tomasklim is that expected ?
### ETH Sepolia
 - derivation paths **not** available
### Solana Testnet
 - derivation paths **not** available 
### Cardano Testnet - derivation paths available 
- im not able to add second and third derivation account after i added first one , see video /same issue with Cardano :( /

https://github.com/user-attachments/assets/ea493d53-8652-431f-8a76-c0f8bb3e8ee3

### Polygon PoS 
- added `Ledger account m/44'/60'/1'/0/0` added
- sent tx to and from account [link](https://matic2.trezor.io/address/0x535bBC61f9d7C2b174eCB403373053a484eF6690)
- after i removed and rediscovered wallet ledger account is present

### Ethereum Classic
- derivation paths not available

### BnB chain
- added ledger account
- send tx to account and from account [link](https://bsc1.trezor.io/address/0x535bBC61f9d7C2b174eCB403373053a484eF6690)

### Solana
- added ledger account `m/44/501/0`
- sent tzx to and from account `[link ](https://explorer.solana.com/address/E29rP1o7GAxnHssLWFaWuo77pSHAxbW2PKCPFNJwN2EX)`

### Ethereum
- added Legacy `m/44/60/0/0` and Ledger account `m/44/60//0/0`
- sent tx to both accounts
- after i removed and discovered wallet again accounts are not present because transactions are not yet confirmed and not available on all our backends

**Comment by tomasklim** [comment]
1. It is mentioned in PR, ok
2. Ok
3. Ok

How about cardano, does it behave same as cardano testnet?

Evm, solana testnets ok, no need to add

**Comment by bosomt** [comment]
Im not able to add Cardano or Cardano testnet accounts today :( /Pos and ETH works as expected/
Im not sure if anything changed 

<img width="495" alt="image" src="https://github.com/user-attachments/assets/76bb9434-23ab-4c62-aba4-d531cc528f4b">

**Info:**
 - Suite version: web 24.9.0 (a314dcfd25df706f1986ab394f2e20c40c616fd6)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32

**Comment by bosomt** [comment]
**QA OK**

except im not able to add Cardano and Cardano testnet account on **20 word seed** with `Account discovery error` error
but its ok on **24 word seed** 

**Info:**
 - Suite version: desktop 24.9.0 (6ba2bd1d277d1d354677f46e17bd3a5a2a03937e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.9.0 Chrome/124.0.6367.243 Electron/30.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.7.2 regular (revision da75d8f4b67410b40a9cfd2954d183d81dd6e8e8)
 - Transport: BridgeTransport 2.0.32

**Comment by Hannsek** [comment]
This is intended, no?
