### ISSUE TITLE
Expand on loading buttons

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1374]
Spoiler alert: This is a nitpick. I think we should make bigger padding on the buttons that will have a loader in them, so it doesn't aggressively "jump" to side. 

 

![Screen-Recording-2020-03-24-at-21 44 24](https://user-images.githubusercontent.com/29627086/77476343-b306e500-6e1a-11ea-9f85-b78b5692fc08.gif)

**Comment by slowbackspace** [comment]
I think that adding padding even when loading icon isn't showing is really weird. We could solve this by (1) adding slick animation or (2) overlaying the spinner over the button instead of adding it to the left.

check out "slide" (1) and "expand" (2) animation in this example:
https://coreui.io/docs/2.1/components/loading-buttons/

I like adding animation the best because even after click the user still know what is it that he is waiting for.

**Comment by glacierbits** [comment]
@slowbackspace Ok! Let's do the _expand animation_ please.
