### ISSUE TITLE
Label of outgoing address cannot be saved

### ISSUE THREAD

**Issue by worras2019** [trezor/trezor-suite#13862]
I am using Trezor Suite on MacOS sonoma 14.6.1. The Trezor Suite version is 24.7.3. Please check the bug. When I tried to give a label to the outgoing address when sending out coins, the label cannot be saved and there is no place to find the list of addresses. I enable the label function and save locally in Trezor Suite. Please fix the bug or give a solution.

**Describe the bug**

**Info:**

-   Remembered Wallet: yes/no
-   Suite Version: app/web, commit
-   Browser: name, version
-   Browser Installation Method: snap, flatpak, app store, windows store, downloaded installer, etc.
-   OS: name, version
-   Bridge: version
-   Firmware Version: model, version/commit

**How to reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bosomt** [comment]
**QA OK**

@worras2019 fixed in version that will be released in  "soon" ™ 

**Info:**
 - Suite version: web 25.1.0 (f81e70edde076bf7a7890b12a303859e6e2ecc06)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: WebUsbTransport
