### ISSUE TITLE
I am getting   'Auto Updater Error (Downloading)' message when attempting to update windows desktop trezor suite software to version 24.8.3 from version 24.2.4. Please advise.

### ISSUE THREAD

**Issue by Scorpion2008** [trezor/trezor-suite#14039]
I am getting  'Auto Updater Error (Downloading)' message when attempting to update windows desktop Trezor Suite software to version 24.8.3 from version version 24.2.4. I have restarted PC and Suite, and tried again, but this has not resolved the problem. 

Please advise.

**Comment by MiroslavProchazka** [comment]
Hello @Scorpion2008 , 

this is likely caused by our recent change of windows certificate, see more [here](https://trezor.io/learn/a/transitioning-to-new-windows-certificates-for-trezor-suite?srsltid=AfmBOooFTY11OFezdRjq-YSAmrLrqAfYcaq3NQJ_3jJRt6ofOgSpdHhk)

I would suggest following: 
1) Leave EAP (if you are part of it)
2) Restart application
3) Suite should prompt you to update to 24.5.4 version 
4) Update to 24.5.4
5) Suite should prompt you to update to latest (24.8.3) 
6) Do the update 

In case you encounter any errors during the process, you can download the latest version directly from https://trezor.io/trezor-suite. Please do not use Google to search for it; just follow the direct link to the Trezor.io website, as there are many scam sites trying to disguise themselves as the official Trezor site.

Thanks, 

MP

**Comment by Scorpion2008** [comment]
Hello @MiroslavProchazka ,

Thank you for your feedback.

I not sure what you mean by 'Leave EAP' how do I check or do this?

So essentially, you suggest that a two stage software update is done to Trezor Suite in order to get it up to date?

Please advise.

Thanks.

**Comment by Scorpion2008** [comment]
I managed to located EAP and turn it off...

And now Trezor Suite is not loading and keeps crashing....

**Comment by Scorpion2008** [comment]
Hello @MiroslavProchazka ,

I managed to get Trezor Suite to load after restarting the PC, and have successfully managed to upgrade to version 24.5.4.

I was then prompted as you advised, to upgrade to 24.8.3, but this have failed again and I now get the following message in a windows pop up box:

"Failed to uninstall old application files. Please try running the installer again.: 2 " and when I try again it come up with the same message.

Please advise.

Thank you.

**Comment by MiroslavProchazka** [comment]
Hello,

I would advise to download the instalation files of the latest Suite version (24.8.3).
It is the easiest way how to get newest version. Please make sure that you will download the file directly from the official website, as mentioned on the previous message.

**Comment by Scorpion2008** [comment]
Hello @MiroslavProchazka ,

Just to let you know I managed to fix this issue and managed to update the software to the latest version... It was an issue with the controlled folder access in windows security...which I have adjusted, and update was successful.

Thank you for your help.

**Comment by Scorpion2008** [comment]
Issue resolved as detailed above.
