### ISSUE TITLE
Autoupdate - Update on quit does not install update 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#15026]
**Describe the bug**
See video. i Was able to replicate it multiple times.
Works as expected on macARM and update is installed.

**Steps to reproduce:**
1. See video, disable and enable and disable autoupdate
2. Open Update downloaded modal
3. Select Update on quit
4. Quit
5. Update is never installed

**Info:**
 - Suite version: desktop 0.24.11 (99bc1a55596bd6c262159c160320ef3e1862e385)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/0.24.11 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: Trezor T3T1 2.8.4 regular (revision da7ddd5c8c0b2040eef38247d4fd73d4576e6708)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**
https://youtu.be/DFIiCVYQUWA

**Comment by peter-sanderson** [comment]
The issue here is `disable and enable and disable autoupdate`.

Current implementation will intentionally prevent auto-update on quit after you have disabled the silent update. The reason is to enable this scenario:

1. You have auto-update (silent update on)
2. You read bad thinks about Trezor Suite on Twitter and you really dont want to get an update (because you believe it may be compromised for example)
3. You open Suite (but new update is immediately downloaded automatically)
4. But you can go to settings and disable auto-update 
5. Despite the file has been downloaded the app wont update on-quit (because you have just disabled the auto-update)

However, we probably should add this "force" update under this specific button.
![image](https://github.com/user-attachments/assets/61e2759b-41ba-4bef-ac83-0317ce3b8620)

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.2 (b44a924ad9e7cb96c8eaadfdca45e4183314bd66)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.2 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.2
