### ISSUE TITLE
Suite reacts poorly to unknown ButtonRequests

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-suite#1642]
This breaks forward compatibility: I won't be able to use a newer fw with older Suite, if the new FW contains new `ButtonRequestType`s (or possibly other enums too)

I implemented `ButtonRequestType.PinEntry` and send it for PIN entry dialogs. Can provide FW with this.
Now when I go to change PIN, after confirming "do you really want to enable PIN", Trezor freezes (because it does not receive a reply) and Suite shows:
```
Error: l.find(...) is undefined
```
Presumably some call somewhere is trying to resolve the ButtonRequestType and fails.
No errors in console, nothing relevant in "show log"

**Comment by tsusanka** [comment]
Responding to `ButtonRequest` with `ButtonAck` even for unknown types would help a lot (and maybe log such occurrence).

**Comment by matejcik** [comment]
Noting that in the long run, we want to replace reliance on ButtonRequest codes with something smarter. So this is probably low priority.

**Comment by szymonlesisz** [comment]
suite it self doesn't touch transport/protobuf layer at all, it's a trezor-connect job, suite is just a consumer.
So whenever we add new ButtonRequest it needs to be implemented in `trezor-connect` and suite doesn't have to do anything. It will receive ButtonRequest from connect and display default "follow instructions on device" message

> Responding to `ButtonRequest` with `ButtonAck` even for unknown types would help a lot (and maybe log such occurrence).

That's what is happening, every ButtonRequest gets Ack back:
https://github.com/trezor/connect/blob/develop/src/js/device/DeviceCommands.js#L667-L673

The problem is that `trezor-connect` received unknown protobuf message `PinEntry` and failed on parsing (inside trezor-link)

**Comment by tsusanka** [comment]
> That's what is happening, every ButtonRequest gets Ack back:
trezor/connect:src/js/device/DeviceCommands.js@develop#L667-L673 

> The problem is that trezor-connect received unknown protobuf message PinEntry and failed on parsing (inside trezor-link)

Can we modify this that trezor-link does not fail on parsing in such case but only logs some warning and sends `ButtonAck` even for new unknown `ButtonRequestType`? Or we do not want it? Or it is not possible?

**Comment by szymonlesisz** [comment]
sure we can, but this project needs a massive refactoring.
moving issue there
