### ISSUE TITLE
Transactions graph: confusing numbers

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#1779]
Im not sure what should i read from the graph and it's hard for me to get any information from it. It shows some numbers but they are not related to anything what happens in reality

Account: https://etc1.trezor.io/address/0xEF114A242B4f2aC127c603370c8Db965c94CDB36

![Screenshot 2020-05-11 at 23 04 03](https://user-images.githubusercontent.com/3435913/81611868-202b0580-93dc-11ea-835b-d9b08d75f751.png)

**Comment by szymonlesisz** [comment]
compare old wallet with suite (same account)
invalid:
![Screenshot 2020-05-11 at 23 18 06](https://user-images.githubusercontent.com/3435913/81612898-d4795b80-93dd-11ea-8598-50f491c1f26d.png)

valid:
![Screenshot 2020-05-11 at 23 18 18](https://user-images.githubusercontent.com/3435913/81612910-d9d6a600-93dd-11ea-887f-f552a4d9c845.png)

**Comment by slowbackspace** [comment]
@matejzak I guess the problem is (@szymonlesisz correct me if I am wrong) that Blockbook includes an amount from sent to self transactions in its calculation (as you can see in Blockbook explorer linked in the first post). Suite only shows a fee that was paid for the transaction, without the amount that was sent. 

@szymonlesisz should I open a ticket in blockbook repo?

**Comment by szymonlesisz** [comment]
like i said, i'm not sure what our goal is with this. (to look like old wallet ?) i just noticed it throw some weird numbers which i don't understand. thats why i tagged @matejzak 
Also im surprised that no one noticed this before...

**Comment by szymonlesisz** [comment]
i'm not sure that this is only BB issue, for example on the 1st screen you can see that i had 4 transactions, yet graph shows 3

**Comment by slowbackspace** [comment]
> i'm not sure that this is only BB issue, for example on the 1st screen you can see that i had 4 transactions, yet graph shows 3

that was probably just stale data. ~I think there are few mins before the new txs gets aggregated by blockbook.~ Tested, confirmed txs are added instantly, but there is no update logic for the graph data yet so I still suspect you had stale data (fixed in https://github.com/trezor/trezor-suite/pull/1699).  I checked the output from blockbook this morning and it shows 4 txs.

**Comment by szymonlesisz** [comment]
dalsi case, graph se nenacetl a vidim tam tohle: `volume: transactions`
![Screenshot 2020-05-12 at 14 24 08](https://user-images.githubusercontent.com/3435913/81691005-6aec6200-945c-11ea-95a4-551d7c514abc.png)
