### ISSUE TITLE
Minor Firmware Update issues

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#1810]
**A. Issue: Button for available firmware in Device Settings**

**Steps to reproduce:**
**1.** Connect device with outdated FW
**2.** Go to Device Settings

**Expected:**
Button for available firmware in Device Settings will be green to highlight that user can take this desired action.

**Actual:**
Button for available firmware stays the same grey as when there is no FW update available.

![update available](https://user-images.githubusercontent.com/58593111/82198525-ba1f1080-98fc-11ea-9999-9cfccd0c539b.png)

**B. Issue: After FW Update, Device Settings Shows Info for Another Device**

**Steps to reproduce:**
**1.** Connect T1 device (just for easier distinction)
**2.** Connect TT device
**3.** Choose TT device and go to Device Settings
**4.** Initiate and complete FW update

**Expected:**
After completing FW update, user will go back to same Device Settings (in this case settings for TT device) they were before starting FW update.

**Actual:**
When FW is over, user ends up in Device Settings for the other device - the one that has not been updated.

**video:** https://drive.google.com/file/d/1FdXt0l11sGjB_i38gLAkNJ9UcSZ97Qsi/view (0:26 - 0:39 is the update, can be skipped)

**Comment by hynek-jina** [comment]
@trezor/qa is this actual?

**Comment by bosomt** [comment]
2x **QA OK**

fixed in recent design changes.


**Info:**
 - Suite version: desktop 22.8.0 (7e0e13f24db34d253bcb714c01d8aac16326d22d)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.8.0 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
