### ISSUE TITLE
Suite shows incorrect fee in FIAT

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#1816]
Suite always says that fee is max 0.01 $ even it's more than 3.00 $
I have 7.06 $ in account.
Even when there is nothing to send and fee is higher than all funds it says 0.11 $

**Normal fee - no FIAT info**

![image](https://user-images.githubusercontent.com/31506317/82217192-599ecc00-991a-11ea-9977-568e5ad7ac08.png)

**Custom fee = standard fee**

![image](https://user-images.githubusercontent.com/31506317/82217226-67ece800-991a-11ea-93e6-ba123ae174a4.png)

**High custom fee**

![image](https://user-images.githubusercontent.com/31506317/82217511-d03bc980-991a-11ea-8026-7661283a3317.png)

**Comment by wendys-cats** [comment]
**Related issue: Suite does not reload Send Transaction page correctly when changing fees**

**Expected:**
Validation for Send transaction will be triggered when changing fees.

**Actual:**
Validation for Send transaction does not happen when user is changing fees. For example (shown in video), when lowering fee, Suite does not check again if there are enough funds and the shown message "Not enough funds" is from the higher fee and does not necessarily reflect the current state. A complete reload will happen when the Amount is entered again (even if it is the same amount that had "not enough funds" just a moment ago) and suddenly, the transaction is possible. 
Interestingly, this only happens when user is lowering the fees. Validation and reloading are working correctly when moving from lower fees to higher. 

**video:** https://drive.google.com/file/d/1OzoS2BtYTdEWftIfWTlD-KCH0ldbQMea/view

**Comment by bosomt** [comment]
now it's complete mess ;) 
it tries to send more than twice I have in account ;)
@wendys-cats is it related to your issue ?
and I don't think that 180 sat/b fee is only one cent

![image](https://user-images.githubusercontent.com/31506317/82729920-12d71a80-9cfc-11ea-91fb-a270db23c315.png)

**Comment by bosomt** [comment]
actual see is 200x higher than i can see in suite

![image](https://user-images.githubusercontent.com/31506317/82729964-7f521980-9cfc-11ea-8e8d-599f69ce51d2.png)

![image](https://user-images.githubusercontent.com/31506317/82729970-8a0cae80-9cfc-11ea-964b-12a1d72c5354.png)

**Comment by wendys-cats** [comment]
@bosomt the balance inconsistency reported in #1876, where @matejzak commented why it occurs.
