### ISSUE TITLE
Add react-native hot reloading

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#19]
http://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading

**Comment by slowbackspace** [comment]
Update:
Hot reloading should work out of the box for class components (It has to be enabled in dev menu in the emulator (cmd+m)). For functional components there is an issue https://github.com/facebook/react-native/issues/10991

There is a workaround using some babel plugin https://github.com/bvic23/babel-plugin-functional-hmr. But it doesn't work with hooks so that isn't an option. 🤷‍♂️
> Limitations
> If you try to use hooks in your source they won't work (you will get an "Hooks can only be called inside the body of a function component").

Some people say following works

> What is working for me is to use class components for screens. Then, any child components can be functional w/ hooks, and HMR still works.

I haven't tried it yet, since we were still doing some heavy development around views. I will try it ASAP.

**Comment by slowbackspace** [comment]
New version of hot reloading that fixes these problems will be released in RN 0.61.
https://github.com/facebook/react-native/issues/10991#issuecomment-506881184
