### ISSUE TITLE
i see enter passphrase dialogue before i see correct dialogue after i unlock device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2046]
**Info:**
 - OS: Nixos , current stable version
 - Browser: Chromium | 83.0.4103.61 (Developer Build) (64-bit)
 - Wallet Version: web, suite-web/feat/232-pinentry
 https://github.com/trezor/trezor-suite/commit/06d90d21312e090fb2e1b14f83b99be48bd13fb2
and  beta version of suite https://github.com/trezor/trezor-suite/commit/06d90d21312e090fb2e1b14f83b99be48bd13fb2
 - Firmware Version: model T , 2.3.1 production c6b2580cd and 2.3.2 master e630279
 
**Describe the bug**
 i often **see enter passphrase dialogue before i see correct dialogue after i unlock** auto-locked device with some confirmation like change pin or name, after less than second it will disappear and I will see correct dialogue

**Steps to reproduce:**
1. load device in suite
2. wait for autolock or send first request /it never happens when you send second request/
3. observe

**Expected result:**
You will see correct dialogue without passphrase dialogue

**Actual result:**
You will see correct dialogue after brief  passphrase dialogue
Please see video: https://photos.app.goo.gl/qkE2ak4icEBUhZAo8

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/85133016-311c3180-b23a-11ea-8e9d-f5162d3275c4.png)

**Comment by tsusanka** [comment]
More detailed steps to reproduce:

1. load device in suite, initialize it, enable passphrase and PIN
2. go to settings in Suite
3. unplug the device
4. plug the device and wait for autolock
5. set label
6. after unlock you indeed see "Please type passphrase" for a brief period of time

---

@bosomt is this specific to the auto lock feature? In another words are you able to reproduce this with production 2.3.1 and latest beta version of Suite on beta-wallet.trezor.io?

**Comment by tsusanka** [comment]
On a brief examination in firmware it seems that we receive `GetAddress` after `Initialize` therefore we need seed and therefore we request passphrase. So the question is:

1. Does Suite need to send `GetAddress` in this case? It is most likely the GetAddress with testnet path to "contact" the device. If the `GetAddress` would be omitted, the `PassphraseRequest` is not sent and this will be solved.
2. Why does Suite send "empty" `PassphraseAck` as a response to `PassphraseRequest`? It should request the passphrase from user, shouldn't it? Maybe it realizes that this is setting which does not need passphrase but then why not solve it using (1)?

**Comment by bosomt** [comment]
@tsusanka 

no it's not related to auto lock feature, that's why I tested it via 2.3.1 too  /Firmware Version: model T , 2.3.1 production c6b2580cd and 2.3.2 master e630279/

**Comment by bosomt** [comment]
issue still present in current freeze version 44254ee8780ea1550b017621c154b2990b1fe3f0

**Comment by tsusanka** [comment]
@matejzak we should look at this asap, I don't like it.

**Comment by tsusanka** [comment]
Let me summarize. As mentioned this does not relate to autolock. So updated steps to reproduce:

- load device in suite, initialize it, enable passphrase and PIN
- unplug
- go to device settings in Suite
- unplug the device
- plug the device
- set label
- after unlock PassphraseReq/PasshraseAck is exchanged but the passphrase is not requested from the user

----

After going to Dashboard/Accounts the passphrase is requested again though so this is hopefully not a bug? @szymonlesisz is this expected because you know passphrase does not affect ApplySettings?

**Comment by tsusanka** [comment]
Discussed in person. This is fortunetly only a cosmetic issue. @szymonlesisz will investigate whether for ApplySettings we need to get the state (Suite's state - the testnet address) or not, because it seems it is not needed and in such case GetAddress would not be sent -> PassphraseReq/Ack would not be sent as well -> no dialog.

**Comment by szymonlesisz** [comment]
fixed here:
https://github.com/trezor/connect/pull/658/files

**Comment by tsusanka** [comment]
@bosomt please retest

**Comment by bosomt** [comment]
**QA OK**

dev master branch commit ef26a1e262d97c3c30694a8ce6aff89481756dcd
2.3.2 d065c5d
Chromium 84.0.4147.125

**Comment by bosomt** [comment]
QA OK

works fine now in a8438ad

OS Nixos
BR Chromium 84.0.4147.135
FW 1.9.3 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8
