### ISSUE TITLE
Accounts: Filters

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2083]
**[Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5efc87a5cb1263131d55bd0d)** 

- [x] Add cross to remove search input 

<img width="323" alt="Screen Shot 2020-08-15 at 22 54 26" src="https://user-images.githubusercontent.com/29627086/90321464-5384af80-df4a-11ea-8ee0-c73ea0f3b8e9.png">

- [x] Use default placeholder "_e.g. Search_" (as opposed to "Filter accounts") 

- [x] Use "_BTC_" (i.e.  the official 3 letter coin abbreviation) as active filter result (as opposed to "symbol:BTC")

<img width="286" alt="Screen Shot 2020-08-15 at 22 56 38" src="https://user-images.githubusercontent.com/29627086/90321487-96df1e00-df4a-11ea-93e5-6fceb13b6dcb.png">

**Comment by sorooris** [comment]
**Bug**: No accounts are displayed in **AccountsMenu** when a specific CoinsFilter is selected and the coin deselcted in Settings.

> OS: any (tested NixOS)
Browser: any supported (tested Firefox 79.0.1)
Wallet Version: web, 20.9.1 cf1f18089c5ed75a68f2e720a5e08b6e3df79130
Device 1.9.3 0d5f00668

**Preconditions:**
- an arbitrary coin is selected so the CoinsFilter is displayed
- existing accounts

**Steps to reproduce:**
- select a coin in the **CoinsFilter**
- navigate to Settings -> Coins and **deselect the coin** (selected in the CoinsFilter in the previous step)
- **navigate back** to Accounts tab and see the left-hand-side _My Accounts_ menu (AccountsMenu)

**Actual behavior:**
No accounts are displayed in the AccountsMenu.

**Expected behavior:**
The filter is deselected and associated accounts are displayed.

![image](https://user-images.githubusercontent.com/10185314/92451821-89215f00-f1bd-11ea-84ec-5c93d0e233c9.png)

**Comment by glacierbits** [comment]
@slowbackspace I assume upon disabling the particular coin, filter should automatically reset itself.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model T 2.3.4 commit 50854b921
