### ISSUE TITLE
Clear storage button doesn't work

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2254]
See Sentry report I submitted moments ago.

**Comment by slowbackspace** [comment]
tldr; it is working just in different way that one could expect. Right now it clears a content of all created object stores. The new behaviour will be that we'll remove whole db instead. The added benefit is that if we mess up creating/removing object store (ie changing db structure) in the migration process, "clear storage" button will really save us and trigger db initialisation instead of just emptying whatever content is in current db structure.

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web + app, 20.9.1 cf1f180
OS: NixOS, MacOS
Browser: any supported (tested Firefox 79.0)
Device: Model 1 1.9.3 0d5f00668

App and web builds are correctly reloaded with databases deleted.
