### ISSUE TITLE
Warn in Suite if Trezor has safety checks enabled

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2282]
Let's add a warning similar to "backup needed" that informs the user that they have "safety checks" enabled.

Related to #2242. Needs https://github.com/trezor/trezor-firmware/issues/1133 and https://github.com/trezor/trezor-firmware/issues/1193.

**Comment by glacierbits** [comment]
After a brief discussion, we came to a conclusion (or rather hypothesis that needs to be verified) that since the safety checks Settings automatically reset with device reconnect, we don't need the banner notification. 

- [ ] @tsusanka will kindly check whether this is indeed true and will let us know 👆🏽 🙏🏽 

cc @goodhoko

**Comment by tsusanka** [comment]
@mmilata it is true that when safety_checks are set to Prompt they will default to Strict on next Trezor replug, correct? Only PromptTemporarily does not do that but we have decided not to have that in Suite for now.

**Comment by mmilata** [comment]
They are two distinct values, `PromptTemporarily` and `PromptAlways` (in addition to `Strict`), `PromptTemporarily` is only until next reboot.

In `trezorctl` we expose these as:
```
trezorctl set safety-checks prompt
trezorctl set safety-checks prompt --always
```
i.e. `PromptTemporarily` is the default

**Comment by prusnak** [comment]
> Let's add a warning similar to "backup needed" that informs the user that they have "safety checks" enabled.

@tsusanka by "enabled" you mean set to something else then "strict", right?

**Comment by tsusanka** [comment]
@prusnak yes indeed. Hm, so the user could have set `PromptAlways` via trezorctl and then go to Suite and they should probably see the warning there @matejzak :confused:.

**Comment by goodhoko** [comment]
> Hm, so the user could have set PromptAlways via trezorctl and then go to Suite and they should probably see the warning there.

Good point! We definitely want to show the warning when `safety-check == PromptAlways`.

The remaining question is: should the warning appear for `PromptTemporarily` too? I'd say, yes, for the sake of consistent UI and principle of least surprise. This is however mainly a product design question @matejzak .)

I'll assign this to myself to do it along #2242. Hope that's ok. .)

**Comment by glacierbits** [comment]
> The remaining question is: should the warning appear for `PromptTemporarily` too? I'd say, yes, for the sake of consistent UI and principle of least surprise. This is however mainly a product design question @matejzak .)

Let's do it. Here is the notification design: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/6047b148d44ac2bb6f429603) 
Currently being implemented by @tomasklim btw. 💡 

- Color: [type-orange](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/styleguide) (Warning) 
- CTA link to Device Settings 
- Banner notification for `PromptTemporarily` should be dismissible: (1) the user made an action to reach that particular state and (2) it will be set to `Strict` with the next device reconnect. `PromptAlways` on the other hand, should not be dismissible: User could have set it via trezorctl.

**Comment by goodhoko** [comment]
@tomasklim [is reworking](https://github.com/trezor/trezor-suite/issues/2752) the notifications/banners RN. It would be best to base the safety checks banner on top of his work. Marking this issue as blocked.

**Comment by goodhoko** [comment]
I started working on this (based the code on Tomas's not yet merged branch) and several questions sprung up. All targeted at @matejzak.

- What's the priority of the banner with respect the other ones? In other words where in the sequence of banners Tomas outlines [here](https://github.com/trezor/trezor-suite/issues/2752#issuecomment-794090799) (the banners section) should this banner be inserted? I propose to put right after `No backup` and give it priority of 6.
- The CTA button is said to [open the device settings](https://github.com/trezor/trezor-suite/issues/2282#issuecomment-800481769) but that page is quite large and the Safety Checks section isn't visible at glance. Since the Safety Checks are set via a modal we could make the CTA button open the modal right away. That's IMO a bit better UX.
- Should the banner dismisssal persist over suite restart?
- I'll need a copy for:
  - The banner content. Consider whether we should have two versions: for `PromptTemorarily` and for `PromptAlways`. A simple `Safety Checks are disabled.` might suffice?
  - The CTA button. I'd put simply a `change` there but it just doesn't feel quite right.

**Comment by glacierbits** [comment]
(1) **Agreed** — priority #6 sounds reasonable with respect to the scale of other items on the list. 
(2) I would still prefer to **link the CTA to the Device Settings** to 'teach' the user where that particular options is located. That being said, I agree it's problematic (similar to what we are trying to solve in #2208) and it would be great to fix in the future, i.e. to give the user a visual cue where they should focus their attention (component blink, scroll to the page aka anchor link etc.). Putting on my things-to-clean-up list. 
(3) **I believe so**, but no strong opinion, since it is "hard core" feature anyway and the device reconnect will reset it to default. 
(4) Feel free to **word it as you would** and add it to CrowdIn (I guess you might have already), it will be later proofread there. 

Many thanks!

**Comment by goodhoko** [comment]
@matejzak 
1) ACK
2) Ok then. I [mentioned](https://github.com/trezor/trezor-suite/issues/2208#issuecomment-828382334) this in the issue and I'll also leave a TODO in the code.
3) I'll opportunistically take the other approach and make the dismissal last only for a session. For two reasons 1) implementation simplicity 2) it's more defensive. The worst case is an user annyoed by the warning. The worst case of persistent dismissal is an user unaware of disabeld safety checks approving non-standard (trans)action.
4) Ack.

**Comment by glacierbits** [comment]
3. Got it - no objections. 

Thanks!

**Comment by goodhoko** [comment]
Done in https://github.com/trezor/trezor-suite/pull/3681. Closing.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular

**Comment by STew790** [comment]
**QA OK**

Info:

- web 21.5.1 (4d09d88476dab2e6b2fbfb833b749e9ac62251c2)
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
- OS: NixOS
- Device Model T 2.3.5 regular

**Comment by wendys-cats** [comment]
**QA OK**
- notification panel is visible when safety checks are disabled through Suite or when trezorctl set safet-checks prompt (--always) is used. 

**Info:**
- Suite version: web 21.5.1 (4d09d88)
- Browser: Chromium Version 88.0.4324.182 (Official Build) (64-bit)
- OS: NixOS 21.03
- Device:  TT 2.3.6 regular
