### ISSUE TITLE
idea: Input focus styles

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#23]
What about changing inputs border color on focus to something like `#96c3fb;` instead of doing ugly box shadow.
<img width="718" alt="Screenshot 2019-05-10 at 15 02 58" src="https://user-images.githubusercontent.com/6961901/57529257-bb564e80-7334-11e9-928b-5a61e7bdb2fb.png">

- there are no focus styles for checkbox/switch

**Comment by keip** [comment]
I think we should pick the style of it from the wallet:
<img width="747" alt="TinyGrab Screen Shot 20-05-2019, 15 09 50" src="https://user-images.githubusercontent.com/1011630/58023973-6a531100-7b11-11e9-97ac-9f8c38872a49.png">

I like the grey border more than the blue `#96c3fb;` color. 

The reason why i don't like the color on focus is because input/textarea could have state (info|error|warning...) - thah's why i like the box shadow, it can be seen on a input/textarea even if it has waring/error state.

**Comment by slowbackspace** [comment]
> I think we should pick the style of it from the wallet:
> <img alt="TinyGrab Screen Shot 20-05-2019, 15 09 50" width="747" src="https://user-images.githubusercontent.com/1011630/58023973-6a531100-7b11-11e9-97ac-9f8c38872a49.png">
> 
> I like the grey border more than the blue `#96c3fb;` color.

But this would invalidate your second argument about visibility right? I have nothing against gray/black from old wallet. I just thought blue is more common for this usecase.

> 
> The reason why i don't like the color on focus is because input/textarea could have state (info|error|warning...) - thah's why i like the box shadow, it can be seen on a input/textarea even if it has waring/error state.

warning/error state could be seen even with blue border. There is still an error message and red/orange icon inside the input.
I stopped liking box shadow because it looks really out of place in our wallet app. Hmm, Eshop is also  box-shadow, just a little bit more subtle so it looks more like a border. Maybe being consistent across trezor project could be a good thing?

<img width="352" alt="Screenshot 2019-05-20 at 18 36 18" src="https://user-images.githubusercontent.com/6961901/58037671-389c7300-7b2e-11e9-9f24-1960b8d478fd.png">
