### ISSUE TITLE
Labeling: Functionality improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2353]
- [x] ~~Dropbox session timeouts~~ (moved to #2454)
- [x] ~~Google Drive~~ (moved to #2454)
- [x] Include labels in search Accounts (resolved in d1d46bd7af51b32feec0f2ace60b2568efbbe22b)

bugs: 
- [x] https://github.com/trezor/trezor-suite/issues/2358

**Comment by mroz22** [comment]
I ll move google drive and dropbox to a separate issue, it will include:
- remove legacy implementation of authentication from dropbox
- rework google auth implementation to work with official lib 
- to make previous work it may also be needed to reregister app in google as another application type and obtain new token
- it will require to implement http server in electron instead of popup.
- cleanup of mytrezor ouath_receiver

**Comment by glacierbits** [comment]
To be continued in the next release.

**Comment by sorooris** [comment]
**QA OK**

- [x] labels in search Accounts 
- [x] bug #2358

Suite: web staging, commit 426ce98
Browser: Chromium 85.0.4183.102
OS: NixOS
Firmware Version: 2.3.4 50854b921
