### ISSUE TITLE
Saved accounts behind passphrase with disabled passphrase protection

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#2362]
steps to reproduce: 
1. save passphrase wallet
2. disable passphrase feature in device settings
3. reconnect device
4. go to receive and hit show full address

result: verify address error: passphrase is incorrect

**Comment by jerechinsky** [comment]
this is now mitigated by showing "Change passphrase settings to use this device" and also warning users if they try to receive btc to a hidden wallet because they can't verify it on their trezor
<img width="514" alt="Screenshot 2021-04-14 at 16 51 43" src="https://user-images.githubusercontent.com/75733878/114731211-12d77300-9d31-11eb-9cfd-b4a933986aec.png">
<img width="828" alt="Screenshot 2021-04-14 at 16 51 25" src="https://user-images.githubusercontent.com/75733878/114731197-10751900-9d31-11eb-9f08-fc4778309844.png">
