### ISSUE TITLE
Close button in Firmware Update modal not working when you start update before wallet is loaded

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2456]
**Info:**
 - OS: Nixos
 - Browser: Chromium , version 85
 - Wallet Version: web, commit f9d6827f67e9877bbd903a05da4469578617dd74
 - Firmware Version: model T1 , revision  0xcde8f31ec2ddcb7d35e36edbcf8a71dda983a9ea,
 
**Describe the bug**
Close button in `Firmware Update` modal not working when start update before `Select wallet type` modal is displayed
See video please

**Steps to reproduce:**
1. load suite and start onboarding
2. just before `Select wallet type` modal is displayed press update now button
3. try to close Update modal

**Expected result:**
You are able to close Update modal

**Actual result:**
You have to disconnect device or reload Suite to get rid of this modal

**Screenshots:**
https://www.youtube.com/watch?v=xrPtGjtJsOE&feature=youtu.be

**Comment by mroz22** [comment]
Ah, interesting. It hangs here 
https://github.com/trezor/trezor-suite/blob/e4ce82bf39a57e6e7a2bb37de9c9acd61ed35df1/packages/suite/src/actions/suite/routerActions.ts#L44-L49
because modal.context is set to `@modal/context-device` (ui-request-passphrase). But it happens in async mannner. I don't know before clicking "update" button that device is going to ask for passphrase so I can't wait for it. So disabling the button "until something happens" is not a way to go. 

Let me think.. :thinking:

**Comment by bosomt** [comment]
**QA OK**


No more Cancel button and Select wallet type modals is above update modal.

**Info:**
 - Suite version: desktop 21.3.2 (6dbeaf3dd28a11c5e4bc5867686f58d2920a14bd)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.2 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model One 1.9.3 regular

![image](https://user-images.githubusercontent.com/31506317/112172487-0c078580-8bf5-11eb-9b16-bf6797fb0e5f.png)
![image](https://user-images.githubusercontent.com/31506317/112172532-16298400-8bf5-11eb-9e46-642bc0efee0f.png)
