### ISSUE TITLE
CI: use "needs" instead of "dependencies"

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2526]
We might optimize CI performance by using "needs" instead of "dependencies".

This is just a reminder to try this later, after the public relase.

CCing @tsusanka as he did the switch in trezor-firmware repo: https://github.com/trezor/trezor-firmware/commit/13c11e756e7931117b3b1b90aad3ee4bcf0994fe

**Comment by tsusanka** [comment]
Just for reference: I already tried it and it [failed](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/204749618) for some reason. Will have a look later.

**Comment by prusnak** [comment]
I restarted the e2e jobs, they are quite flaky, so maybe they will pass this time :)

**Comment by tsusanka** [comment]
It passed on the retry. But the problem is that the e2e tests are starting right away because they did not depend on anything in the first place. Let's see what happens with ddca118f4ce5a13e6347da7ee422194b279b2556.

![image](https://user-images.githubusercontent.com/1835345/96592093-4d170900-12e8-11eb-87c0-e8699911f2c7.png)
