### ISSUE TITLE
Labeling: Improvements

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2532]
- [x] `loading..` _(Show only on hover)_
- [x] Cursor _(Input doesn't start on the all the way left hand side)_
- [x] Full rename account proces: [Zeplin](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/5f3bf73d694a9912ac30606f) 
- [x] Label input should have grey background and placeholder (see design)

![Screen Shot 2020-09-02 at 14 04 08](https://user-images.githubusercontent.com/29627086/91978929-3fe88f80-ed25-11ea-8b96-6fa419790bb4.png)

- [ ] New label > Click "Edit label" > Label jumps to the right by a few pixels (and vice versa when saving the label)

**Comment by tsusanka** [comment]
Also on NixOS on e6ba320 when I am about to type the label and I move the cursor in the middle of typing the input gets canceled. I did not click on anything, just moved the mouse on this video:

![Peek 2020-10-14 08-05](https://user-images.githubusercontent.com/1835345/95950039-25a9d300-0df4-11eb-9977-b5206d8bed40.gif)

It seems to happen when I move the cursor out of the transaction "row", ie the white background item.

---

will be fixed in #2632

**Comment by mroz22** [comment]
All of the above should be solved now, please test :pray:

**Comment by bosomt** [comment]
**QA OK**

Windows 10
Suite app commit b0dacc3
Device model T FW 2.3.4
