### ISSUE TITLE
Unable to factory reset or wipe a locked device 

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#2542]
OS: NixOS
Browser: Chromium 85.0.4183.102
Suite: web staging, commit 426ce98fbcb16af057d8b2f5d636f88f4e374a23
Firmware Version: any (tested 2.3.4 50854b921, regular and btc-only) 
 
**Describe the bug**
There is no way to wipe or factory reset device with Suite when device is locked (for example when user forgets their PIN code) compared to the possibility of factory-resetting device in MyTrezor Wallet.

**Steps to reproduce:**
1. Connect a device in bootloader mode,
2. Run Suite app or web version,
3. See result.

**Expected result:**
An option to factory reset or wipe device is displayed.

**Actual result:**
No option to factory reset or wipe device is displayed, only to start the firmware update flow.

**Screenshots:**
Suite with device in bootloader mode connected:
![image](https://user-images.githubusercontent.com/10185314/95352179-45a43880-08c2-11eb-956b-f74dd706fa30.png)
MyTrezor Wallet with device in bootloader mode connected:
![image](https://user-images.githubusercontent.com/10185314/95352231-52289100-08c2-11eb-8f0f-363da630f293.png)

**Comment by sorooris** [comment]
@matejzak @alex-jerechinsky could we implement a fix for this in the following releases?

**Comment by glacierbits** [comment]
Thanks for brining this to our attention. As a matter of fact, it's a good timing to include it in the new Onboarding #3332 development — to be released in May. (1) App Settings should be accessible even without connected device, and (2) we can detect Bootloader mode on the app startup screen [here](https://app.zeplin.io/project/5ee87c00f6af719a645d14c3/screen/60340959122e10b2d3800dd8).  

cc @slowbackspace 

Feature request, design needed. Assigning myself.

**Comment by slowbackspace** [comment]
> App Settings should be accessible even without connected device, and (2) we can detect Bootloader mode on the app startup screen [here]

Hold your horses, while the feature seb asks is easy to implement ad-hoc I am afraid that proposed solution is a bit more complicated than it seems.
Adding a button to new "welcome/connect your device", in case the device is connected in bootloader, will be easy, but keep in mind that means suite will need some heavy adjustments (basically we need only allow few actions in settings, forbid accessing dashboard, accounts and other stuff).

From technical POV this new screen for connecting a device is not really part of onboarding process, rather it is separate feature. Right now connecting the device in various states (seedless, bootloader, unreadable device, fw update required a some more) is handled by several separate modals shown in suite (see first screen posted by seb). Sometimes for very good reason. When user has multiple devices connected, and just the one currently selected is seedless, or there is fw update required, or some other state we cannot work with, we show a modal and he might simply chose to work with another device by clicking on "swittch device" button . Handling all this on "welcome screen" really needs tons of work and brainstorming and I really won't expect it can be done at the same time as whole onboarding rewrite. For now I would keep it simple and on welcome screen handle just connection status (connected or not) and let suite take care of various states device might be in.

For example, when you connect a device in bootloader mode you have an option to go update your firmware (which is separate modal/flow, independend of fw update in onboarding), It doesn't make sense force this user to go through onboarding process since the device might be actually initialized, we just don't know about it while it is in bootloader. Actually, In order to start the onboarding process we force user to connect device in normal mode first.

If we really want feature Seb ask for ASAP I would just focus on allowing suite to access settings with bootloader device by adding button to existing modal and making necessary adjustments to prevent triggering actions which doesn't make sense doing with device in bootloader.

**Comment by tsusanka** [comment]
@alex-jerechinsky @matejzak this is a prerequisite to the old wallet deprecation, same as https://github.com/trezor/trezor-suite/issues/2854.

**Comment by glacierbits** [comment]
Closely related to #3729

**Comment by j2d3** [comment]
I have a trezor one, which I have never transferred any funds to, thankfully, and I doubt I ever will. Feels safer on an exchange to be honest. I cannot reset the PIN. The instructions to wipe it say to dismiss the pin matrix when you connect it, but that is not possible, there is not an X to do that. I tried in the websuite using inspect to delete the pin matrix, but there is no "advanced" tab that is clickable anywhere, and I cannot get to any place that will allow me to wipe the device and start over. (When I first got the thing, I did reset it multiple times, but now, the interface has changed.) I do have my recovery phrase and did verify that it has no funds in it via metamask. Anyway - much as I like the idea in theory of "being my own bank" and caring for my own keys, trezor does not make that task simple or comprehensible at all.

**Comment by matejkriz** [comment]
Design:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3729633/144392968-e9af870b-bb12-4287-b4c6-7fcc85656715.png">

EDIT: updated design
![image](https://user-images.githubusercontent.com/3729633/148356053-51f3fb85-ea30-4e9c-a206-ac755cb15429.png)


Following states in [Figma](https://www.figma.com/file/BUMem1C7j4roQDyJf9yxQT/Exploring-Onboarding?node-id=807%3A438)

**Comment by matejkriz** [comment]
- [ ]  consider if there is another special state where it makes sense to provide wipe button directly

**Comment by bosomt** [comment]
**QA OK**

edit: disregard, it works as expected, 
wipe unlocked device: seed is wiped
wipe bootloder device: firmware is wiped

~~I'm still missing option to `Factory reset device` as was possible in old  wallet.
Even it says `factory reset `only seed is really wiped and firmware is still present.
@tomasklim @matejkriz @matejzak  is this feature planed ?~~

**Info:**
 - Suite version: desktop 22.1.1 (7e2101c6d91c14e6a0faba8b4057f04ba2422578)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular.
