### ISSUE TITLE
Nicer <title> on landing page

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2634]
The <title> on "suite.trezor.io" is "suite.trezor.io" instead of Trezor Suite. Can we change it? Tested in Chromium 85 and Firefox 81.

Might make sense to do together with https://github.com/trezor/trezor-suite/issues/2629.

**Comment by prusnak** [comment]
In HTML we have `<title>Trezor Suite</title>` but this gets overwritten by some funky Javascript magic I suppose.

**Comment by slowbackspace** [comment]
already fixed in my soon-to-be-PR branch on favicon (as I was assigned before).
it was mistakenly defined in body, not in head element but that still wouldn't work as it belong to _app, not _document file 😁  (it was copy pasted from old landing which has the same bug) 

https://github.com/vercel/next.js/blob/master/errors/no-document-title.md

**Comment by bosomt** [comment]
I don't see landing page anymore, Chrome + Firefox, restarted browsers and VPN
It worked fine before.

Nixos + Firefox 81
Suite dev web commit 4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device 2.3.3 model T commit 0d5f00668

![image](https://user-images.githubusercontent.com/31506317/96892515-02cd8d80-148a-11eb-8a3d-46226bf94cb6.png)

**Comment by tsusanka** [comment]
This might be related to the fact that our CI is f*cked. Let us fixed that first.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Chromium 86.0.4240.75
Suite dev master 91d61f884c9a17cea3e338e45f915760c44cd751
