### ISSUE TITLE
Empty screen after update succeeds.

### ISSUE THREAD

**Issue by xbach** [trezor/trezor-suite#2650]
**Info:**
 - OS: macOS 10.14.6
 - Suite Version: macOS, 20.10.1
 - Firmware Version: Model T, update to 2.3.4 
 
**Describe the bug**
Empty screen in Suite after the firmware update finishes. Clears after the device is unlocked. Not a serious issue, it just looks like Suite is stuck (see screenshot).

**Steps to reproduce:**
1. Update firmware
2. Finish updating firmware, device restarts
3. Suite shows empty screen

**Expected result:**
Expected a screen with further instructions, like unlock your device to continue

**Actual result:**
Empty screen

**Screenshots:**
<img width="1156" alt="Screenshot 2020-10-15 at 21 00 43" src="https://user-images.githubusercontent.com/9579260/96174837-378d9200-0f2a-11eb-90ad-55b4cd4241b2.png">

**Note(s):**
Nice bug reporting template!

**Comment by mroz22** [comment]
Argh, this ineed happens if you have pin enabled on T2.If pin is not enabled on model T, success screen  appears correctly. 
![image](https://user-images.githubusercontent.com/30367552/96258871-fabeab00-0fbc-11eb-80a7-4d6da62aa4f5.png)

I forgot about this feature of model T that host can't detect it until the device is unlocked.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 81
Suite dev web 4d4a9f3f493613c0a86f905414dd8071c55ac69e
Device model T fw 2.3.3 + 2.3.4 commit 50854b921
