### ISSUE TITLE
Suite doesn't kill all running processes when closing the app

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2655]
**Info:**
 - OS: Windows
 - Wallet Version: app, commit 99959260d5639480dfb11e53a4f2ab1d789b0e7b
 
**Describe the bug**
See screenshot, when you close Suite app, one process is left in memory and can significantly drain OS resources.
I checked after 30 minutes and it was still not idling. Please implement some feature that will detect that will kill Trezor Bridge if ti was started along with Suite start.  

**Steps to reproduce:**
1. install and start Suite app
2. close Suite /you can interrupt coin discovery like i did/
3. check Task manager

**Expected result:**
Trezor Bridge is closed with Suite 

**Actual result:**
One process is left in memory.

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/96248988-c7742000-0fac-11eb-9494-d43775446a83.png)

**Comment by slowbackspace** [comment]
I think this is expected behaviour. it was decided long time ago that bridge should keep running even if suite is closed, but I also find it weird and would prefer we kill the bridge when user closes the app.
I've even experienced memory leaks in the bridge process in the past that caused it to eat over 1gb of memory, simply killing bridge would prevent it from eating all my ram.

**Comment by tsusanka** [comment]
> it was decided long time ago that bridge should keep running even if suite is closed, but I also find it weird and would prefer we kill the bridge when user closes the app

Btw was this decided in some larger audience? Because I find it also a bit ugly and unprofessional. I am okay with it in case we have specific reasons for that (such as that the discovery is X% faster) but I would like to have this decision based on some concrete arguments. Do we have that? We can discuss this on some standup :).

**Comment by slowbackspace** [comment]
@tsusanka I don't really know, probably suite team was present 😀 
@szymonlesisz do you remember why we want to keep bridge process running even after user exits the app?

**Comment by bosomt** [comment]
QA OK

Fedora + Windows 10 /current versions/
Suite app commit 513631a
Device 1.9.3 model One commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8

tested with Trezor Bridge present and not present in system and Suite behaved correctly
