### ISSUE TITLE
Cancel fw update: cannot read read property error of null

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#2659]
https://user-images.githubusercontent.com/31506317/95347757-8a79a080-08bd-11eb-99b4-306357c994e6.png

I suspect something in trezor-link / trezord

**Comment by szymonlesisz** [comment]
and i suspect connect :) since it works with "typed errors" now, obviously there is some bug there.
if you are able to simulate it try to track it near:

https://github.com/trezor/connect/blob/develop/src/js/device/DeviceList.js#L328
or
https://github.com/trezor/connect/blob/develop/src/js/device/DeviceCommands.js#L695
or
https://github.com/trezor/connect/blob/develop/src/js/device/Device.js#L255
or
https://github.com/trezor/connect/blob/develop/src/js/core/Core.js#L321

**Comment by mroz22** [comment]
I skimmed through connect looking for this but didn't spot it there. But will give it try another time.

**Comment by mroz22** [comment]
from the suite perspective, this should be fixed in https://github.com/trezor/trezor-suite/pull/2587
please test :pray:

**Comment by bosomt** [comment]
**QA NOK**

TT cancel update OK 
T1 not OK

but there one more issue: https://github.com/trezor/trezor-suite/issues/2710
@slowbackspace close this issue and move to merged or wait till it's fixed ?

![image](https://user-images.githubusercontent.com/31506317/96979359-5ccc6280-151f-11eb-8323-dab3f611e833.png)

Nixos + Firefox 81
Suite dev web 4d4a9f3
Device model One 1.9.1 commit 0xc6b2580cd245ee924507f45e9675f857a3d78768,

**Comment by mroz22** [comment]
Ah, I see. This was hotfixed for chrome only by error string matching and replacing it with something reasonable only until this is fixed where it should be fixed (connect or maybe even lower). But different browsers vary in "copy" for errors. So I guess this workarounding does not make sense and I shall focus on fixing it in connect.

**Comment by szymonlesisz** [comment]
should by fixed by https://github.com/trezor/connect/commit/966f51d897e7d84cffe169a51aed13fb0377da31

**Comment by wendys-cats** [comment]
**QA NOK**

NixOS + Chromium 85
Suite web 20.11.1 39d1b9690756482310a3970de0d1a29b0d4d2e89
Device TT 2.3.3 

**note:** Still spams the Network with requests (status 400 named null) every second after canceling TT FW update - even when the device is disconnected and reconnected. Got more than 500 requests by the time I recovered a wallet. T1 does not exhibit this quirk.

**Expected**
"Error: Firmware installation failed"

**Actual**
TT and T1 update both show "Error: Firmware install failed" instead of "Error: Firmware installation failed"

**Comment by mroz22** [comment]
Expectations by QA differ from actual behaviour only in copy. That can be seen as low priority and moved to the next project.

**Comment by wendys-cats** [comment]
Closing issue. Reported separately [here](https://github.com/trezor/trezor-suite/issues/2919) on @mroz22´s request.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device 1.9.2 + 2.3.2
