### ISSUE TITLE
Discreet mode: Blur effect cut off

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2688]
Last commit: 95e158346c92d61492c40e7f66eae33f3101f864

<img width="1483" alt="Screenshot 2020-10-20 at 11 37 03" src="https://user-images.githubusercontent.com/29627086/96569192-209fc480-12c9-11eb-9ccf-02f52df9535c.png">

**Comment by slowbackspace** [comment]
fixed even before you opened PR! what a hard-working team! https://github.com/trezor/trezor-suite/pull/2669 😁

**Comment by slowbackspace** [comment]
grr, but probably not in transactions, only in accounts menu

**Comment by slowbackspace** [comment]
woah, guys @robertbrada @tomexx I don't see an easy way out of this for txs list(and in general). The effect is cut off because of `overflow: hidden` which is rather essential. Any ideas? 

The best I can think of is to add horizontal padding in the blurred overlay when discreet mode is activated, but this has a potential to break things and can look weird even when animated (I am gonna try it anyway 😬).

edit: here it is: https://suite.corp.sldev.cz/suite-web/fix/discreet-overlay/web/ super laggy

**Comment by tomexx** [comment]
I'll check and try to find a workaround

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox 82.0 (64-bit)
Suite web dev master commit a5b13d5
Device model TT FW 2.3.3 commit 0d5f00668
