### ISSUE TITLE
Loader default stroke width to 2px

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#27]
Could we change it to 2px please? It really helps with visibility especially with smaller loaders (and doesn't change that much with huge ones)
1px (now default):
<img width="85" alt="Screenshot 2019-03-18 at 15 10 44" src="https://user-images.githubusercontent.com/6961901/54536026-2bc59c80-4990-11e9-9beb-4e1446122871.png">
2px (proposed)
<img width="63" alt="Screenshot 2019-03-18 at 15 10 50" src="https://user-images.githubusercontent.com/6961901/54536027-2bc59c80-4990-11e9-8d9c-ba633d289045.png">

**Comment by keip** [comment]
I'm thinking why do we even have this option to change the stroke width?
I think it's unnecessary because we would like to have the same loader everywhere and the only thing that we want to change (imo) is the size of it, from which you could calculate the stroke width (or even the font size)... 

Something like this:
loader.size <= 80px; stroke width = 1px;
loader.size > 80px; stroke width = 2px;
loader.size > 160px; stroke width = 3px;

@slowbackspace what do you think?

**Comment by slowbackspace** [comment]
Idk, could you post some screenshots? I don't understand  where are the advantages of removing options. I would hate with the passion every UI lib that's doesn't let me specify custom size of spinner/loader. Let's just setup good defaults (2px are fine with me) that works in most cases and let devs handle the rest.

Saying that for 79px loader there is gonna be 1px stroke but for 81px loader it is 2px is somewhat too opinionated (and not in a good way) without a good enough reason. In the end it doesn't really matter, but why do weird things that doesn't really help anyone and apply restrictions when it is not necessary?

Simpler argument, what if someones really like having 20px small fatty loader with 10px stroke width. We should let these people have fun. 😁

**Comment by keip** [comment]
I was thinking about it like a scalable thing.
Imagine for eg. scaling an SVG of a loader, everything in that image is scaled proportionally.

But ok i agree with you that having more props is more fun 😄 

So i will set the default width to 2 px.
