### ISSUE TITLE
Rework launching and killing of the bundled bridge

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2719]
1. We should not try to start bridge if there is already one running on https://127.0.0.1/21325 and use that instead
2. We should kill the bridge on exit ONLY if it was started by us

We will use the same logic for launching the bundled Tor as well

**Comment by tsusanka** [comment]
To elaborate on this: yes if the user has an older bridge installed they will use the older one than what is bundled inside suite. We believe we can live with that since:

1) If the older bridge is working just fine then why not.
2) Bridge changes are quite rare.
3) If any problem arises we can simply instruct the user to uninstall.

**Comment by bosomt** [comment]
**QA OK**

**Fedora + Windows 10** /current versions/
Suite app commit 513631a9fa62c438e60397a9942b04275bcd621a
Device 1.9.3 model One commit 0x0d5f00668fb3d1c093ff3c879311a91d3a7175c8

tested with Trezor Bridge present and not present in system and Suite behaved correctly

**Comment by wendys-cats** [comment]
**QA OK**

Tested with and without Trezor Bridge present and Suite behaved correctly.

**OS** Windows 10 home
**Suite** app 513631a
**Device** TT 2.3.4 public

**Comment by sorooris** [comment]
**QA OK**

OS: macOS Catalina 10.15.7
Suite: app 513631a9
Device: model T 2.3.4 50854b921
