### ISSUE TITLE
Button misalignment: Add hidden wallet

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2845]
Browser: Chome
Version: 8f4d1eedd6eb7648b17853a9a780a0688c0370e6

The button should be centered. 

<img width="912" alt="Screenshot 2020-11-03 at 10 13 48" src="https://user-images.githubusercontent.com/29627086/97967263-45ae3000-1dbd-11eb-9d12-4efd0cb43b60.png">

**Comment by slowbackspace** [comment]
This got broken in  [Tor navigation design](https://github.com/trezor/trezor-suite/pull/2576/commits/c4a75cfae084db5d424023e5e7e279473efaef1d)


Moving classname from Tooltip's wrapper to Tippy is ~potentially~ breaking change and probably not necessary. `className` is used by styled components to... style components, (re)moving it like that is almost always bad idea unless you want to cause headache to your coworkers while they are trying to figure out why can't they restyle a component (and break existing components that are depending on it). 

https://github.com/trezor/trezor-suite/commit/a7de14133635e6632cb2db1da3aafe0dee0acaed#diff-cca5f70a161b190985a39adbeadf2b3c9da3819d71e45e7a444471f4ccefd5d2R116

Instead of passing classname string, create a new prop for the Tooltip and based on that add necessary styles:
https://github.com/trezor/trezor-suite/commit/a7de14133635e6632cb2db1da3aafe0dee0acaed#diff-c5d52a0b01db1e0f234b46b1aaf2db914d7eda703fa58131aad4b6b79777d8cbR159

@tomexx let's talk about it when you are available, maybe I am missing something here.

**Comment by bosomt** [comment]
**QA OK**

Nixos + Firefox Browser 82
Suite web dev master commit 374d027
Device model T fw 2.3.4 commit 50854b921

![image](https://user-images.githubusercontent.com/31506317/99369390-ac9f0f00-28bc-11eb-8972-276b789f015d.png)
