### ISSUE TITLE
Device refresh: Disconnected

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2846]
Platform: Chrome
Version: 8f4d1eedd6eb7648b17853a9a780a0688c0370e6

It seems the `disconnected` animation replaced the refresh option altogether. 

User is no longer able to refresh the device session from the navigation. 

Steps to reproduce: 

- Make device unacquired (e.g. reload page on passphrase input modal)
- Navigation says device disconnected, even though that's not the case
- Switch device modal has the correct "refresh" button

<img width="320" alt="Screenshot 2020-11-03 at 10 16 59" src="https://user-images.githubusercontent.com/29627086/97967640-ca994980-1dbd-11eb-9ba5-1ac3d2d790ba.png">

<img width="885" alt="Screenshot 2020-11-03 at 10 18 39" src="https://user-images.githubusercontent.com/29627086/97967769-f7e5f780-1dbd-11eb-8c2f-d89e48da9834.png">

**Comment by glacierbits** [comment]
FYI I am unable to reproduce this. So just heads up, perhaps try to look at it just briefly and feel free to close afterwards.

**Comment by slowbackspace** [comment]
This is a legit state. How Suite sees it: You have one remembered wallet "Ferda" and one connected device which couldn't be acquired so Suite doesn't know anything about it. It can't tell if it is the same device or not until it is acquired. It might be the case that you have connected completely different device, that's why you see 2 devices.

There is not much we can do about it. If you have any question feel free to send me a message!

**Comment by bosomt** [comment]
**QA OK**

Firefox 82 + Nixos
Suite web dev master commit 9a39d54
Device model TT FW 2.3.4 commit 50854b921
