### ISSUE TITLE
React-select SSR warning

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#290]
Warning: Prop `id` did not match. Server: "react-select-39-input" Client: "react-select-2-input"

**Comment by vladimirvolek** [comment]
![image](https://user-images.githubusercontent.com/3112191/61642293-f6fc8580-aca0-11e9-8d05-9995fe9851f8.png)

**Comment by vladimirvolek** [comment]
react-select issue https://github.com/JedWatson/react-select/issues/3590

**Comment by slowbackspace** [comment]
this issue/comment seems related and could help https://github.com/JedWatson/react-select/issues/2629#issuecomment-473037019.

My understanding is that the issue, in our case, **occurs only on dev server and only once nextjs reloads the app** (you see the wallet loader spinning), so on the server side app was rendered multiple times, each time bumping the select id while it stays the same on a client. My quick test showed the issue **doesn't happen while serving the app from static export** (and it makes sense since there is no nextjs server in this instance).

**Comment by smitd21** [comment]
Select component needs an instanceId, id mandatory
So Just add

**id="long-value-select"
instanceId="long-value-select"**

to your Select component it will remove the Warning :)
