### ISSUE TITLE
CDN throws away the GET parameters in the URL

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#2903]
**Describe the bug**
See screenshots, we are experiencing lots of errors in browser logs during accounts/transactions loading in Suite

**Info:**
 - Suite Version: /web, commit 513631a9fa62c438e60397a9942b04275bcd621a
 - Browser: Chrome, version 86.0.4240.111 + Firefox 82
 - OS: Nixos
 - Firmware Version: model T 2.3.3 , revision 0d5f00668

**Steps to reproduce:**
1. Load suite
2. Enable all coins
3. open browser console during/after account exploring 

**Expected result:**
No errors in console
**Actual result:**
See screenshots from both supported browsers

**Screenshots:**
![image](https://user-images.githubusercontent.com/31506317/98340674-062a5280-200e-11eb-90d7-15026917dd0c.png)

![image](https://user-images.githubusercontent.com/31506317/98341425-1abb1a80-200f-11eb-8462-3cdd39b97f9a.png)

**Comment by prusnak** [comment]
This is a CDN issue - I'll take care of this

**Comment by prusnak** [comment]
Found the culprit - our CDN does throw away the GET arguments, which was not a problem for most of the requests, but since this particular request has 2 URL arguments, it causes trouble.

Coingecko throws HTTP 422 error in case no GET arguments are provided, but this error response does not have CORS headers, that's why this looked like a CORS error.

Fix is on the way.

**Comment by prusnak** [comment]
The issue with the CDN should be fixed now - https://cdn.trezor.io/dynamic/coingecko/api/v3/coins/ripple/market_chart?vs_currency=usd&days=7 returns correct data now.

@bosomt please re-test

**Comment by wendys-cats** [comment]
**QA OK**

Console shows no CDN errors during transactions/accounts loading.

**Suite** web 513631a
**Browser**: Chromium 85
**OS**: NixOS
**Firmware** Version: TT 2.3.4 public
