### ISSUE TITLE
Coin filter disappears after clicking on a TX Sent notification

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2906]
**Describe the bug**
Suite disables the coin filter after Sent transaction (view details) is clicked on. Clicking on this notification redirects the user to account transaction history and simultaneously disables the coin filter.

**Info:**
 - Suite web 513631a9fa62c438e60397a9942b04275bcd621a
 - Browser: Chromium 85
 - OS: NixOS
 - Firmware Version: TT 2.3.4 public

**Steps to reproduce:**
1. Activate several coins
2. Enable coin filter and make a transaction on one of the filtered coin´s accounts
3. Click on the "Transaction x.xxx COIN on COIN #number successfully confirmed View Details" 
4. Check that coin filter is disabled

**Expected result:**
Clicking on  "Transaction x.xxx COIN on COIN #number successfully confirmed View Details" notification will not disable coin filter.

**Actual result:**
Clicking on  "Transaction x.xxx COIN on COIN #number successfully confirmed View Details" notification disables coin filter.

**Comment by slowbackspace** [comment]
I looked into it and it is technically valid behaviour as the same logic is used for all notifications 😁 
 
Imagine scenario where you have active BTC filter, you get notification about recv transaction that was sent to your LTC account, it is necessary to reset the filter otherwise you will be redirected to LTC account but only see BTC accounts due to activated filter.

Technical reasoning why we reset the filter  is that before the redirect to the account, we need to select a correct wallet. And switching the wallet resets the filter (for obvious reasons). 

We probably could change the behaviour and select the device (wallet) only when user has some other wallet active and I tried it, but I am not sure if it is worth the added complexity. Then there is still a problem that you can click "view details" on older tx in activities screen. This definitely has to reset the coin filter (you may have active XRP coin filter, click on view details on BTC tx, you will be redirected to BTC account but in accounts panel all you see would be XRP accounts which could be confusing).

@matejzak What are your thoughts? Do we really want to work around this somehow and find some solution? I personally don't find it as a problem since it concerns only the users that meet ALL of following requirements:
1) user has active coin filter
2) user sent tx and clicks on "view details"
3) user has to find it weird that the filter would reset (and I think most of them would be ok with this)

There might be some users (I would say 5 of them in total) that could find this a bit annoying, but I can live with that 😁

**Comment by glacierbits** [comment]
@slowbackspace I agree the issue/fix is not worth pursuing (unless user feedback proves us otherwise). So far I haven't seen a single user complaint about the coin filter. 

@wendys-cats Don't let that demotivate you. Thanks for challenging the functionality and make us think.

**Comment by bosomt** [comment]
QA OK
nothing to test

Nixos
Suide app dev maser commit 9a39d54
Device mdoel T fw 2.3.4 commit 50854b921
