### ISSUE TITLE
Remember desktop Suite window size

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#2938]
**Describe the bug**
Maybe this is a NixOS thing but when I launch Suite via appimage-run and resize the window it is not remembered on a next launch.

**Info:**
- Suite Version: desktop 36c7716
- OS: NixOS
- Firmware Version: 1.9.3
- Viewport: 1920 x 975

**Steps to reproduce:**
1. Launch Suite
2. Enlarge its window
3. Close it
4. Lauch again

**Expected result:**
The window size is remembered.

**Actual result:**
The window size is restored to the default setting.

**Note(s):**
Related to https://github.com/trezor/trezor-suite/issues/2937.

**Comment by prusnak** [comment]
I am wondering whether this is a:
- [ ] NixOS issue
- [ ] all Linux issue
- [ ] all OS issue

**Comment by slowbackspace** [comment]
macOS build from staging works fine on my machine ™️ 
so that's leaving all linuxes or NixOS :)

**Comment by tsusanka** [comment]
@slowbackspace forgetting Bill Gates :P.

**Comment by slowbackspace** [comment]
@tsusanka ohh right, the windows people. I just checked with @wendys-cats and it indeed doesn't work on Windows, same with my Ubuntu. Kinda weird it only works on macOS. I'll investigate a bit more since I already started digging into it :)

**Comment by prusnak** [comment]
It seems Electron does not do that automatically, so most macOS does that instead of Electron

There are several ways how to do this:
* use of the shelf solution: https://github.com/mawie81/electron-window-state
* store stuff manually in the current storage (probably preferred as it does not add any new dependency): https://medium.com/@hql287/persisting-windows-state-in-electron-using-javascript-closure-17fc0821d37

**Comment by slowbackspace** [comment]
@prusnak Where did you find that mac is handling this by itself ? We have an implementation for storing window size in desktop suite for a long time, imo that's why it works at least on macOS. Now for some reason it is broken on windows and linux.

edit: hehe, it was there in nov 2019 already! https://github.com/trezor/trezor-suite/issues/813

**Comment by prusnak** [comment]
> Where did you find that mac is handling this by itself ?

It was just my speculation, which was obviously wrong if there is already our custom code dealing with that. :-)

**Comment by prusnak** [comment]
I confirmed that when I edit `$HOME/.config/@trezor/suite-desktop/config.json` manually and modify the `winBounds` object there, the Suite will pick-up the settings from there. However, when I close the Suite these will get overwritten with the default values. This is all aligned with @slowbackspace's observation in https://github.com/trezor/trezor-suite/issues/2937#issuecomment-725441722 so I believe that fix in https://github.com/trezor/trezor-suite/pull/2943 is the way to go.

**Comment by bosomt** [comment]
**QA OK**

Nixos
Suide app dev maser commit 9a39d54
Device mdoel T fw 2.3.4 commit 50854b921
