### ISSUE TITLE
Bridge issues

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#2954]
Related: 

- [ ] https://github.com/trezor/trezor-suite/issues/2949 
- [ ] https://github.com/trezor/trezor-suite/issues/2950 

### Bad UX 

(To be solved by Stick's patch: Notification in desktop app populated only if Bridge version 27 and/or older detected.)

**General concern:** 

- User never used Bridge, doesn't know what is it for or why they need to download it now 
- They might have come across it during the onboarding (long time ago) or never (Suite + webUSB on Chrome)

**Chrome specific:** 

- User is forced by notification to download standalone Bridge even though Chrome supports webUSB (no Bridge needed) 
- Only restarting the system (MacOS) make the notification to disappear 

**MacOS specific:** 
- User is forced by notification to download standalone Bridge even though it comes bundled with the app 
- The user didn't even have standalone Bridge before, yet the notification makes it sound as there is update available

**Comment by szymonlesisz** [comment]
3rd party concern:
- `suite-desktop` opened (bundled trezord running) => go to suite-web or 3rd party app web/webextension => 3rd party app is working
- `suite-desktop` closed (bundled trezord IS NOT running) => go to 3rd party app => 3rd party app forces you to install bridge (via connect popup)
  confusion: yesterday it was working today it's not and forces me to install something new, why?

Uninstall/update concern:
- `suite-desktop` prompts you to uninstall standalone trezord => other apps will not work with `suite-desktop` closed (see 3rd party)
- uninstall on mac needs detailed explanation
- previous `suite-desktop` release has a bug where `trezord` was running even after you kill the suite. (see @matejzak issues with restart)
- regarding to this bug installation of standalone 2.0.30 didn't help because bundled trezord is still running, 2.0.30 wont start - port in use

@prusnak fix #2953 concern:
- you will not see this prompt in`suite-desktop` but you will in web or 3rd party app (via connect popup)

I think it should be partially solved by the valid copy:
- show optional/cancelable notification that we detect that you are using standalone version and it's outdated
- explain what happens if you uninstall it (not be able to use WEB/3rd party implementations with disabled suite)
- let user decide:
  - download and install standalone (with explanation, this will require some more work, because uninstalled/stopped standalone trezord will immediately start bundled trezord :] )
  - uninstall/stop standalone and use bundled one (with explanation)
  - ignore and don't bother me again

**Comment by szymonlesisz** [comment]
the best solution is to rewrite trezord-go and reverse desktop app architecture where trezord is the MAIN/parent daemon app which handle intents like: device-connection, 3rd party request and opens electron app (suite) as a child process :)

**Comment by glacierbits** [comment]
Fixed
