### ISSUE TITLE
Invity features in Tor mode

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#2956]
We should think about how to handle Invity features (which contact our API server and in case of buy also partner's payment gateway) with regards to increased anonymity requested by user by switching to the Tor mode.

My suggestion is to show, when you choose a Trade tab while in Tor mode, a confirmation page with text like "Trade functionality requires to contact our API server and possibly partner's payment gate. Do you want to proceed.", which will show the Trade forms only after the user confirms the action by pressing OK button.

**Comment by prusnak** [comment]
Here I am not worried about our API server, which should work via Tor with no issues IMHO.

The problem lies in the steps after, where some payment gates may either:
a) actively block Tor connections
b) open a popup-window outside of desktop Suite breaking anonymity

I am not sure if b) is even possible - maybe @keraf knows more?

So maybe the Trade tab should be hidden behind a bar that says something among the following?

 "You are in a Tor mode. Some of our Trade partners might actively block Tor traffic. Continue at your own risk."

If b) is possible, we should be even more careful and verbose about explaining the risks.

**Comment by keraf** [comment]
A popup can be opened from Suite-Desktop (just by opening an external link). A warning will be displayed (with the link) when Tor is enabled. I think displaying a warning on the Trade tab when using Tor is a good idea.

**Comment by sime** [comment]
This is happening as described. ![Screenshot 2023-05-12 at 20 40 44](https://github.com/trezor/trezor-suite/assets/216917/6cd9bd31-7ada-486b-a2db-b103f925b0b7)
