### ISSUE TITLE
Normal fee for DOGE too small

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2973]
**Describe the bug**
There has been a change recently in fees for DOGE coin where any transaction with fee under 1 DOGE will be labeled as zero fee transaction and gets stuck in mempool without proccessing, blocking any coins in that transaction from further use. 

**Info:**
 - Suite : app 20.11.1 36c7716bd5c2a01de4b8981a2ac680f80c79164c
 - OS: Windows 10 home
 - Firmware Version: TT model , revision 2.3.4 public

**Steps to reproduce:**
1. Make a transaction on DOGE coin with normal fee

**Expected result:**
The transaction will go through and get confirmed and proccessed into blockchain

**Actual result:**
Transaction will remain [unconfirmed](https://doge1.trezor.io/tx/fa15a35566fdcd1fb0e85d98264c84b4a9044c1af0b7e3a86071ee9660ce19c2). Mempool is full of these transactions.

**Comment by szymonlesisz** [comment]
ah, yes. DOGE miners changed some fee policies

looks like minimum fee for a transaction is now 1 DOGE. They are claiming that this is an attempt to fight with spam transactions.

there is a lot of similar issues in their repo:
https://github.com/dogecoin/dogecoin/issues/

**Comment by bosomt** [comment]
1 DOGE base fee
1 DOGE per 1000 bytes
1 DOGE for every output below 1 DOGE (to prevent dust)

source: https://github.com/dogecoin/dogecoin/issues/1650#issuecomment-722229742

**Comment by langerhans** [comment]
Just to set some facts straight: The fee structure has not changed, it is just enforced more strictly now. We are aware that is an issue and are working on a fix. It just turns out to be not as easy as it may look like. For now we'd advise people to use a custom fee. For a bog standard 1 in 1 out tx you'd use about 520k sat/byte. With change that needs to go up accordingly. Not sure how Trezor Suite does fee calculation, but in the end it needs to be fixed there too.

If any of the devs have a question regarding this, shoot me a message on Discord at langerhans#2409

**Comment by shibe2** [comment]
AFAIK, transactions with less than recommended fee were always treated the same way as free transactions. These transactions were processed, but only a small part of the bock was available for them. This feature was inherited from Bitcoin. Then this feature was deprecated in Dogecoin but worked until recently. In the latest version of Dogecoin Core it's disabled or maybe just broken. When all miners had to update the software because of protocol upgrade, free transaction processing stopped.

**Comment by szymonlesisz** [comment]
hi @langerhans, @shibe2 
thanks for clarification

i did some [workaround in calculation ](https://github.com/trezor/hd-wallet/blob/0e466a1d5362d220ac31a26e62b142e65e2ebb6b/src/build-tx/coinselect-lib/utils.js#L85-L97)
now we basically do: `1 DOGE for every started kb` (regular tx < 1kb = 1 DOGE, above 1kb = 2DOGE, above 2kb = 3 DOGE and so on...) not dealing with `satoshi` anymore

do you think it's too much?
i've also noticed that one of the [transaction](https://doge1.trezor.io/tx/c3582e9acde501f8b7fa64d04ca4df7d8a4eeab068bf184228528d0d58c93547) was mined with lower fee than expected (1.518 kb for 1.00001545 DOGE) - but it takes like 4-5 hours

also i need to remove this `1 DOGE per output below dust` part.
looks like amounts below 1 DOGE are not allowed at all and they are rejected by the network with `-26 64 dust` error even if i set much higher fee (like 4 DOGE)

**Comment by langerhans** [comment]
This seems fine to me, thank you for taking the time to work on this! What you say about dust being rejected is curious. I wasn't aware of that. I saw a bunch of transaction below 1 DOGE. I'll look into checking that out.

**Comment by tsusanka** [comment]
@szymonlesisz is this closed by https://github.com/trezor/trezor-suite/pull/3026 ?

**Comment by szymonlesisz** [comment]
right, closing

**Comment by wendys-cats** [comment]
**copied from:** https://github.com/trezor/trezor-suite/pull/3026#issuecomment-740518108

**QA OK**

**OS** NixOS okapi (21.03)
**Suite** web /develop branch a3f8029
**Device** TT 2.3.4 public

Fee below 100000 sat/b (1DOGE) is not allowed.
If remaining balance after calculating transaction is below 1DOGE (example: there is 2.5DOGE in the account, 1DOGE will be sent, 1DOGE is tx fee, leaving 0.5DOGE), it will be used as fee for [transaction].(https://doge1.trezor.io/tx/6f01f5b338a979fbfdd84b366527a35602daad985b3d76d0ab975c2205efb4ad)
Transfering less than 1DOGE is not allowed.
