### ISSUE TITLE
Error loading page when running on Linux and no udev rules are installed

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#2977]
**How to reproduce:**

1. run Suite on a Linux machine where no udev rules are installed (and ideally no bridge)
2. observe Error occured - Loading takes too long screen

**Description of the problem:**

1. The Suite runs the bundled Bridge as expected
2. Bridge cannot access USB devices so it responds with `{error: "LIBUSB_ERROR_ACCESS"}`
3. Suite thinks the bridge is not responding, so it tries that again and again
4. After ~10 retries (5 seconds) the "Error occured" screen is shown

**Fix:**

If we are on Linux and we detect `LIBUSB_ERROR_ACCESS` from the bridge, we should show a newly created dialogs with contents copied from our wiki page: https://wiki.trezor.io/Udev_rules

**Comment by bosomt** [comment]
is this same problem ?

i have `Loading takes too long` in Firefox Browser 82.0 (64-bit) in private window, in standard window suite loads immediately.
It was confirmed that there are colleagues with same problems.I was not able to resolve it via clear cache
OS Nixos

**Screenshots**

![image](https://user-images.githubusercontent.com/31506317/99351916-f75f5d80-28a1-11eb-88ae-05040cfa61d0.png)

![image](https://user-images.githubusercontent.com/31506317/99352116-558c4080-28a2-11eb-8a48-62ac105aa445.png)

**Comment by prusnak** [comment]
> is this same problem ?

I don't know if this is the same problem, but pleased open a separate issue for this

**Comment by tsusanka** [comment]
I just tried this on a completely new Ubuntu install and:

- If no Trezor is plugged in I am getting the correct dialog "Connect and unlock your Trezor..." with a udev link below.
- If Trezor is plugged in I am indeed getting `Loading takes too long screen`

@alex-jerechinsky this is a must-have before the public release (as written in the acceptance criteria).

**Comment by prusnak** [comment]
We should fix this issue and possibly also install udev rules on Linux automatically - https://github.com/trezor/trezor-suite/issues/3664

**Comment by bosomt** [comment]
@prusnak 

to properly test it all we have to do is to 

1) kill bridge 
2) remove 
```
tbosansk@tbosansk-Latitude-3410:/lib/udev/rules.d$ ls | grep trezor
50-trezor.rules
60-trezor.rules

```
3) start Suite 

right ?

**Comment by prusnak** [comment]
> right ?

Right.

If for some reason the system does not register you have deleted the udev rules, you can try running this:

`udevadm control --reload-rules && udevadm trigger` as root.

Or restart the computer after deleting the udev files.

**Comment by bosomt** [comment]
This is what i see in Firefox when i removed udev rules and bridge  Version: 2.0.31 (rev 5f53132)  is running.
I don't see any information about udev rules / i was not able to test it yet in app because there is no current master build/


Version 21.7.0 Commit 8b018e2f06a7e36d9a650c2b7327c13da125dcdc
Kubuntu 21.04
Trezor T

![image](https://user-images.githubusercontent.com/31506317/124570511-4238e000-de47-11eb-884d-97054fa7d9f7.png)

and after i kill bridge 

![image](https://user-images.githubusercontent.com/31506317/124570778-7a402300-de47-11eb-932a-fcfabbb4f347.png)

**Comment by tsusanka** [comment]
The CI died for some reason, so you were testing on old commit (8b018e2) instead of https://github.com/trezor/trezor-suite/commit/9d473f00215843741241e13ff3b857667fdf3e3f which contains these changes. I have [restarted the CI](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/pipelines/332125913) so let's wait for it.

**Comment by bosomt** [comment]
@tsusanka my bad :( :) haven't checked commit :)  i will wait for CI :)

**Comment by tsusanka** [comment]
@bosomt it did not finish completely yet but the deploy should be done to `https://suite.corp.sldev.cz/suite-web/develop/`, so try now :).

**Comment by bosomt** [comment]
**QA OK**


works as expected in app and in browser when there is app with bridge running in background


**Info:**
 - Suite version: desktop 21.7.0 (9d473f00215843741241e13ff3b857667fdf3e3f)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.7.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: KUbuntu 21.04 Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.4.1 regular

![image](https://user-images.githubusercontent.com/31506317/124580383-59300000-de50-11eb-8bbf-ccf72a71c48b.png)
