### ISSUE TITLE
colors should be abstract

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#30]
colors in config/colors are trezor-wallet specific. For example: 

https://github.com/trezor/trezor-ui-components/blob/ba37c723372b46a8a8b3e371ac2c1546e5b88bbb/src/config/colors.js#L6

colors should provide a common theme configuration only.

**Comment by keip** [comment]
For start we could unify the variables of the same color:

#333333 = TEXT = HEADER_DIVIDER = TOOLTIP_BACKGROUND
#F9F9F9 = LANDING = SELECT_HOVER
#E3E3E3 = BODY = DIVIDER = INPUT_BORDER
#A9A9A9 = LABEL_COLOR = INPUT_FOCUS_BORDER
#01B757 = GREEN_PRIMARY = SUCCESS_PRIMARY
#00AB51 = GREEN_SECONDARY = SUCCESS_SECONDARY

to this:

#333333 = BLACK
#F9F9F9 = GRAY_LIGHTER
#E3E3E3 = GRAY
#A9A9A9 = GRAY_DARKER
#01B757 = SUCCESS_PRIMARY
#00AB51 = SUCCESS_SECONDARY

Then all the GREEN_* variables should be replaced by SUCCESS_*

Change some variable names:
BACKGROUND => WHITE_DARKER
GREEN_TERTIARY => SUCCESS_TERTIARY
HEADER => BLACK_DARK

INPUT_FOCUS_SHADOW is not necessary, i would use GRAY_DARKER

Then we are left with these 24 variables:
<img width="403" alt="TinyGrab Screen Shot 20-05-2019, 16 13 08" src="https://user-images.githubusercontent.com/1011630/58028036-2dd7e300-7b1a-11e9-9e9a-a405383e14a7.png">

**Comment by slowbackspace** [comment]
> For start we could unify the variables of the same color:
> 
> #333333 = TEXT = HEADER_DIVIDER = TOOLTIP_BACKGROUND
> #F9F9F9 = LANDING = SELECT_HOVER
> #E3E3E3 = BODY = DIVIDER = INPUT_BORDER
> #A9A9A9 = LABEL_COLOR = INPUT_FOCUS_BORDER
> #01B757 = GREEN_PRIMARY = SUCCESS_PRIMARY
> #00AB51 = GREEN_SECONDARY = SUCCESS_SECONDARY
> 
> to this:
> 
> #333333 = BLACK
> #F9F9F9 = GRAY_LIGHTER
> #E3E3E3 = GRAY
> #A9A9A9 = GRAY_DARKER
> #01B757 = SUCCESS_PRIMARY
> #00AB51 = SUCCESS_SECONDARY
> 

1) I don't think it's a good idea to merge multiple vars to single variable just because they reference the same color. I remember we already discussed this somewhere. In the future you could want to change the text color to something little bit darker.  If it is would under one variable then you would also change the color of divider inside the header (and now maybe it is so dark that it couldn't be even seen) and tooltip bg. There is no reason for that. They are not related. It just happen they share the same color.

> Then all the GREEN_* variables should be replaced by SUCCESS_*
> 
2) Yup, this is basically already done. All that is needed is to remove GREEN_* colors and replace them by SUCCESS_* where needed. IMO green_tertiary isn't needed right now.

> Change some variable names:
> BACKGROUND => WHITE_DARKER
> GREEN_TERTIARY => SUCCESS_TERTIARY
> HEADER => BLACK_DARK
> 
> INPUT_FOCUS_SHADOW is not necessary, i would use GRAY_DARKER
> 

3) With these generic color names you are losing a bit of information what is the color used for. I can't tell just by looking at `WHITE_DARKER` what is its purpose. I would need to search all files and take a look where it is actually used (also 1). point applies). They are even misleading. Eg.`BLACK_DARKER`, how can be BLACK even darker? Is `WHITE_DARKER` lighter or darker than `GRAY_LIGHT`, `GRAY_DARK`, `GRAY_DARKER`?

I would like to keep "semantic" naming where it makes sense. We don't have to merge variable just for the sake of it.

Current state isn't so bad anymore. Pretty much last few color names I don't like are `BODY`, `MAIN`, `LANDING`, `GRAY_LIGHT`, `BACKGROUND`. Even if I could tell their purpose I can't grasp the difference between them. If we could  figure out more clever names for these then I would be satisfied.
Maybe also rename `TEXT`, `TEXT_PRIMARY`, `TEXT_SECONDARY` to `TEXT_PRIMARY`, `TEXT_SECONDARY`, `TEXT_TERTIARY` if all three are used.
What do you think?

current state for reference:
<img width="319" alt="Screenshot 2019-05-20 at 18 20 41" src="https://user-images.githubusercontent.com/6961901/58036686-ff630380-7b2b-11e9-8ccf-278f957aeb1f.png">

**Comment by keip** [comment]
I like this concept described here (https://medium.com/codyhouse/create-your-design-system-part-3-colors-798e4729921f):

<img width="789" alt="TinyGrab Screen Shot 21-05-2019, 11 23 49" src="https://user-images.githubusercontent.com/1011630/58088732-94650b80-7bc3-11e9-8386-9471964908eb.png">

After changing variable names and organize colors by this concept (except step 2. we don't have accent color), it looks like this:

<img width="372" alt="TinyGrab Screen Shot 21-05-2019, 12 26 31" src="https://user-images.githubusercontent.com/1011630/58088786-af378000-7bc3-11e9-8ab2-56d3a8ae2fc7.png">

It doesn't use primary/secondary anymore just dark/ligt (because each color has a dark and light version);
It doesn't use component names;
All Grays are scaled from 1-9;

What do you think?
