### ISSUE TITLE
trezor-suite AppImage displays an empty window when using ssh X11 forwarding

### ISSUE THREAD

**Issue by mercurytoxic** [trezor/trezor-suite#3091]
When running Appimage version of trezor-suite using ssh X11 forwarding, in Linux, will cause a blank/white/empty screen locally.

 - 20.11.2
 - Linux archlinux 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux 

When creating an X11 forwarding environment

sshd_config on host/remote
```
X11Forwarding yes
```

env on client/local
```
config.ssh.forward_x11 = true
```

and trezor-suite is run in remote, the screen that appears locally is empty. All other graphical applications that don't rely on electron behave correctly.

This behavior does not appear in beta versions of trezor-suite I believe because of changes in docker/docker-compose.suite-dev.yml and/or docker/docker-compose.suite-test.yml, but I might be wrong, that include 
```
QT_X11_NO_MITSHM=1
```
as referenced in https://github.com/electron/electron/issues/22775#issuecomment-616023334 

running trezor-suite with the environment variable QT_X11_NO_MITSHM set to 1 the local window shows the correct images.

**Comment by mercurytoxic** [comment]
This is solved by running trezor with the environment variable QT_X11_NO_MITSHM set to 1
```
QT_X11_NO_MITSHM=1 trezor-suite.AppImage
```

**Comment by prusnak** [comment]
This is not a Suite issue, but Electron issue. You can't use X11 forwarding with Electron unless you set `QT_X11_NO_MITSHM=1` or provide `--no-xshm` command-line argument as mentioned in the comment you found: https://github.com/electron/electron/issues/22775#issuecomment-616023334

The changes you see in `docker/docker-compose.suite-*.yml` files are used to achieve exactly this.

Older releases of Suite might have worked, because they were using older Electron releases.
