### ISSUE TITLE
Labels Dissapearing

### ISSUE THREAD

**Issue by grantwest** [trezor/trezor-suite#3093]
I created labels for multiple wallets and multiple accounts. After reconnecting my Trezor and starting up Suite again some of the labels are missing, but not all. I am using Dropbox for the storage. I tried turning labeling off and then back on, but it did not restore all of the labels.

 - Suite Version: 20.11.1
 - OS: macOS 11.0.1
- Device: Model T
 - Firmware Version: 2.3.4

I did connect a second Trezor with a different seed and enable labeling on that device. I'm not sure if this is causing the problem or not. Labeling seemed to be intermittent even before connecting the second Trezor.

**Comment by mroz22** [comment]
> I tried turning labeling off and then back on, but it did not restore all of the labels.

It seems like some of the labels did not save correctly and UI still let you think they did. I ll keep an eye open for this.

Please @trezor/qa could you try to reproduce this?

**Comment by bosomt** [comment]
i was able to replica it via 20.11.2 in Firefox
Looks like connection to Dropbox is not reestablished after i woke up my Linux laptop.

**Comment by mroz22** [comment]
Didn't have luck reproducing it so far, but I ll keep trying.

**Comment by glacierbits** [comment]
To be tested.

**Comment by bosomt** [comment]
**QA OK**

looks like issue was fixed in recent changes of labeling connection to servers

**Info:**
 - Suite version: desktop 21.1.0 (fa7d200c62499405ae63b6bcc873edc15f79d318)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.1.0 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model One 1.9.4 regular
