### ISSUE TITLE
Hidden wallet number is missing 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3133]
**Info:**
 - Suite version: web 21.1.0 (ff99ab56c3837e41ad0c243d242dceea22bedf6e)
 - Browser: Chrome
 - OS: MacIntel
 - Screen: 1792x1120
 - Device: model T 2.3.4 regular

<img width="350" alt="Screenshot 2020-12-04 at 19 29 49" src="https://user-images.githubusercontent.com/29627086/101200861-28dc7500-3667-11eb-8151-e6e4d109ee63.png">

**Comment by mroz22** [comment]
confirm that this happens when user adds hidden wallet first without pre-existing standard wallet. If user adds hidden wallet after there is already a standard wallet, everything works smooth as covered in this test https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/892753023/artifacts/file/packages/integration-tests/projects/suite-web/videos/suite/passhprase-numbering.test.ts.mp4

**Comment by mroz22** [comment]
fixed in #3136 
with a [test](https://gitlab.com/satoshilabs/trezor/trezor-suite/-/jobs/892787566/artifacts/file/packages/integration-tests/projects/suite-web/videos/suite/passhprase-numbering.test.ts.mp4) we shall never see this again

**Comment by bosomt** [comment]
**QA OK**

looks OK now
![image](https://user-images.githubusercontent.com/31506317/101740116-bafdd680-3ac8-11eb-9834-a35490e94155.png)

Nixos
Firefox 82.0.3 (64-bit)
Suite web dev master commit f93bd32
Device 2.3.5
