### ISSUE TITLE
Allow generating addresses in advance like in the web wallet

### ISSUE THREAD

**Issue by matronator** [trezor/trezor-suite#3213]
**Is your feature request related to a problem? Please describe.**

It seems one major feature from the web wallet is missing in the Suite app and that is the ability to generate addresses in advance. When I click on the receive tab, there's only one address shown and no button to generate new ones.

**Describe the solution you'd like**

Add a button to generate new receiving address EVEN if the previous one(s) were not yet used to receive any transactions.

**Describe alternatives you've considered**

Creating multiple accounts for that, but that's a bit more cumbersome and seems like an overkill.

**Additional context**

In the web client, there is a button or a link to generate a new receiving address, even if the previous one was not yet used. This is useful when I'm expecting transactions from couple of different people and want each of them to send coins to a separate address to not mix the transactions together.

**Comment by tommyz7** [comment]
This is a mighty annoying issue among advanced users. When I try to create a new account I get a message "Previous account is empty" which is correct, the previous account is empty indeed. The issue is that that account is used for authentication only so I just locked myself from creating a new Trezor wallet. Even funnier thing is that I used MetaMask to create another wallet and I funded it so now I have wallets: "funded. funded, empty, funded" that are all visible in Trezor Suit and I still get that message "Previous account is empty". I'd really want to be able to create as many empty accounts as I like. Perhaps some advanced settings and confirmation popup could be used but locking a user in is really bad UX.

I can use MetaMask to go around this issue but the moment Trezor stops working with MetaMask I'm 100% locked and that already happened in the past so it's a real risk. I'd be on the mercy of MM and Trezor devs to do the fix. It's a bad place to be if your wallet is holding a big responsibility.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by ArchBirdie** [comment]
This is still an issue, and it is very much neccesary.

**Comment by RiVal-cz** [comment]
Hi. There still is this issue in the Trezor Suite UI.

**Comment by gary-rowe** [comment]
Hi. Still present in the latest release `23.10.1 (23.10.1.177)`. This is very annoying and needs fixing.

**Comment by Hannsek** [comment]
I just tried it on 23.11.2 and it works.
<img width="673" alt="image" src="https://github.com/trezor/trezor-suite/assets/57008159/2916b405-c55b-4ff0-8396-7b63919987aa">
If you need to generate more than 20 fresh addresses you can use trezorctl.

**Comment by fedealconada** [comment]
This is still a present issue nowadays... I'm on the latest version 1.12.1
<img width="289" alt="image" src="https://github.com/user-attachments/assets/ed73b012-9185-4638-90d9-523e8085ee39">
