### ISSUE TITLE
Exchange should warn about minimum sell price

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#3299]
**Describe the bug**
I've brought a little amount of USDT, lets say 10, now i want to change it back to BTC but the minimum of exchange is 20

**Expected result:**
I should be warned that i will not be able to sell it back

**Actual result:**
I need to do another exchange transaction (BTC > USDT) to fulfill required amount, im losing my time and money on fees

**Comment by LukasRada** [comment]
Unfortunately, it's impossible to determine the minimum threshold reasonably, because of the market volatility. One day the threshold could be $10 and the day after it could be $30 or similar. The question is what's the signal to set the threshold. We suggest to close this issue or if anyone has an idea/solution let's hear it.
