### ISSUE TITLE
Transaction incorrectly displayed when Sent to myself 

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3351]
**Describe the bug**
Please see transaction details. I sent 0.23 LTC to my self but amount is same as fee in transaction detail.
I was able to reproduce it via LTC or DOGE 

**Steps to reproduce:**
1. send transaction from/to same account 
2. compare blockbook information and tx detail information

**Info:**
 - Suite version: desktop 21.2.1 (a63b29d19ff08ece94be28d2997d4265ac1c84fc)
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
Transaction detail shows amount that you sent and not fee
**Actual result:**
Transaction detail shows fee twice

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/107142819-b0798500-6931-11eb-87a7-513b62c9ee25.png)
![image](https://user-images.githubusercontent.com/31506317/107142826-ba02ed00-6931-11eb-8183-8cbbda305f2e.png)

https://ltc1.trezor.io/tx/07fc10025f940a452c3348830eff80804c472ce17775d13a1683e17ade012a4f

![image](https://user-images.githubusercontent.com/31506317/107142840-d2730780-6931-11eb-9fb5-c22ab36251a1.png)

![image](https://user-images.githubusercontent.com/31506317/107142909-444b5100-6932-11eb-9d20-d36acc72e801.png)

![image](https://user-images.githubusercontent.com/31506317/107142927-61801f80-6932-11eb-8a5c-b65c862602a4.png)

https://btc1.trezor.io/tx/8e462d31c818e92fe13b11969a7c1f133a87af1b367ff7d29d1adbe60bf5ada4

**Comment by jerechinsky** [comment]
@szymonlesisz Please suggest if someone else is better fit to fix this issue.

**Comment by mcudev** [comment]
This seems like it is working as intended and not a bug. The transaction summary is telling you about the net effect to your account since both addresses are within the same account. When you send to an address not in the same account (including to an address not controlled by you), then the data are shown as you mentioned in this issue.

For an example of sending from one of your accounts to another of your accounts, see the following transaction for the litecoin segwit wallets of the mnemonic: `all all all all all all all all all all all all`

https://ltc1.trezor.io/tx/1c636b6a0e55a9ae9200535848d0aeb3a1b058638e5af50b7860cc3040dbac3d

That sends from the Litecoin segwit account 1 to the Litecoin segwit account 2 (address MBTPRsFs4vqXorh8skX3DrtERwgBtDTrqC aka m/49'/2'/1'/0/1).

**Comment by bosomt** [comment]
Still same behavior / you see only fee in transaction history but real amount in transaction detail when you send funds to your self.
But it's expected and noone else has complained about it so closing
