### ISSUE TITLE
It is not possible to exchange ERC20 token to ETH

### ISSUE THREAD

**Issue by martinboehm** [trezor/trezor-suite#3389]
Select ETH account, then Trade/Exchange. Choose any ERC20 token to exchange. Then try to choose ETH from the list of coins to exchange to. ETH is missing.

![image](https://user-images.githubusercontent.com/11609674/107617800-d31cde00-6c50-11eb-8f73-22cc9b518388.png)

**Comment by sorooris** [comment]
**ETH is offered correctly**, however we're currently unable to complete the exchange flow because of insufficient funds on ERC20 tokens (we have an exchange in progress) and also due to super-high fees. We'll complete the flow after receiving the exchanged amount.

![image](https://user-images.githubusercontent.com/10185314/108226067-d4607600-713c-11eb-9213-adf33c8adbc3.png)

Suite Version: app 21.2.3 9cf47b5
OS: macOS Big Sur 11.2.1
Bridge: 2.0.27
Firmware Version: model T 2.3.6 b19cbf67c

**Comment by bosomt** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/31506317/108336102-fa852500-71d3-11eb-93a6-5d8d8f74d121.png)

**Info:**
 - Suite version: desktop 21.2.3 (9cf47b5b526bbb5cda585e717fbbf0f5b93b8cc0)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.2.3 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular
