### ISSUE TITLE
Not able to add custom ERC20 token to fresh account

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3392]
**Describe the bug**
I'm not able to add custom ERC20 token to fresh account. `Add token`  never changes to green/active version.
I was able to reproduce issue in app and in Firefox

**Steps to reproduce:**
1. Load Ethereum wallet
2. add new account
3. Add ERC20 token

**Info:**
 - Suite version: web 21.2.2 (7e8958e206885cd7946f431b63dad3bd446ef82e)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.4 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/107634718-467f1980-6c6a-11eb-9cfd-70eed6ef9ecd.png)

**Comment by slowbackspace** [comment]
Soo Blockbook returns unexpected response when fetching token info for an empty account... It will be fixed on the backend. Then probably small change is required in the suite - manually toggle `account.isEmpty` to false after user adds a token. Will be fixed in the next release :)

some thoughts: I am not completely sure if this is real world scenario. Can user have some token on account which we think is totally empty? I can't properly test this case cause when I want to create a token I need to send some eth to this account to pay for a fee, making it non empty in the process and I am not in the mood to learn how to do airdrops 😁

**Comment by tsusanka** [comment]
> some thoughts: I am not completely sure if this is real world scenario. 

This was brought up in the feedback form from a real user so I guess it is :thinking:. @slowbackspace so this needs a modification in blockbook? Is there an issue for that?

**Comment by slowbackspace** [comment]
> > some thoughts: I am not completely sure if this is real world scenario.
> 
> This was brought up in the feedback form from a real user so I guess it is 🤔. @slowbackspace so this needs a modification in blockbook? Is there an issue for that?

Hmmmm, there is now! 😅 https://github.com/trezor/blockbook/issues/566 
Martin is fixing so quickly that I never bother to create issues 😁

**Comment by slowbackspace** [comment]
@trezor/qa fix implemented on dev eth blockbook. Pls if you could find spare few mins to make sure it works as expected I will be grateful 🙏 
https://blockbook-dev.corp.sldev.cz:9136

**Comment by bosomt** [comment]
QA OK

@slowbackspace works fine with https://blockbook-dev.corp.sldev.cz:9136
as soon it gets deployed we can retest it and close this issue

**Comment by slowbackspace** [comment]
new blockbook should be deployed by now, closing the issue.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.4.0 (ab673f9777b6ddaf13234e5e6b3b3ab5be46852c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.4.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
