### ISSUE TITLE
Accounts discovery - Skeletons misleading

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#3450]
**Describe the bug**
During discovery loading skeletons are suggesting that you have more accounts that you really have.
See GIF that I recorded in Firefox and Chromium. You always see +1 account per account type that you really have.
I know it's only cosmetic issue but you can consider to turn it off if possible.

**Info:**
 - Suite version: web 21.3.0 (a0f694411d85fca4a35acedbdf3b07702517c120)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - Bridge version: Version: 2.0.28
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Expected result:**
You only see skeletons for accounts for existing accounts.

**Actual result:**
You see more accounts loading than you really have

**Screenshots:**

`Chromium`
![skelet2](https://user-images.githubusercontent.com/31506317/108605272-61ad0000-73b3-11eb-8af6-2d1c95ee0bfb.gif)
`Firefox`
![skelet](https://user-images.githubusercontent.com/31506317/108605274-6376c380-73b3-11eb-8f49-87f1cbc4af39.gif)

**Comment by slowbackspace** [comment]
Just so I won't forget...
These skeletons visualise that the discovery process is running, and I think it really is running because of the one additional account we retrieve, but keep hidden. So one question is: it is fine to stop showing skeletons even if discovery has not completed? And even if so, It is probably irrelevant as I am afraid we can't tell in advance that this was the last (visible) account and now we don't have to show skeleton anymore. In other words, we don't know that the account discovery is completed till we find an empty account (which we keep hidden by default). I'll check if I am correct.  cc @matejzak

**Comment by glacierbits** [comment]
I agree with the comment above. In general, this skeletons (anywhere across web) are not a pixel-perfect representation of the shape of the content that is going to load. I think there isn't much we can do about this.
