### ISSUE TITLE
Cant add second ETH wallet

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [trezor/trezor-suite#3451]
**Describe the bug**
So i have ETH in my main account, but i want to create a second account to transfer a bit of ETH to, but to my surprise i couldn't open a new account. Error that I'm getting is that i don't have any ETH in my main account, but this is incorrect, because i have ETH in my main wallet.

**Info:**
 - Remembered Wallet: yes
 - Suite Version: app latest version
 - OS: win10 20h2
 - Bridge: latest build version
 - Firmware Version: latest firmware version

**Steps to reproduce:**
1. Check if u have some ETH in ur first ETH account.
2. Try to create a second account.
3. See error.

**Expected result:**
It should create the second account

**Actual result:**
It didnt create the second account.

**Screenshots:**

**Note(s):**

**Comment by slowbackspace** [comment]
Hello @efb4f5ff-1298-471a-8973-3d47447115dc, thanks for the report! Could you check if it is the same issue as in https://github.com/trezor/trezor-suite/issues/3402? Basically you see non-zero balance on first account yet Suite is saying there are no transactions.  If so, it will be fixed in the next release. 🙇

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes its the same. Thanks for informing me. I'll close this issue because it is a duplicate.
