### ISSUE TITLE
Tokens not included in portfolio value on the dashboard

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#3452]
<img width="598" alt="Screenshot 2021-02-21 at 13 03 12" src="https://user-images.githubusercontent.com/6961901/108624431-38d54b00-7445-11eb-8fdd-99719d11029c.png">
<img width="418" alt="Screenshot 2021-02-21 at 13 04 35" src="https://user-images.githubusercontent.com/6961901/108624462-64f0cc00-7445-11eb-97e4-96e106c47f01.png">

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (8f87283e689a17ec573d1326c9849cf263e17d8c)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.3.0 (09ffd1606ded46c05ac55e98c912f8b61c948657)
 - Browser: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.3.5 regular

**Comment by sorooris** [comment]
**QA NOK**

All coins are enabled; Portfolio section on the Dashboard screen displays a non-zero balance. 
**Actual**: Balance in the Assets section on all coins is zero (because ERC20 tokens are not included).
**Expected**: Assets section includes any supported tokens as a subgroup of the relevant coin.

- ERC20 tokens on the seed:
![image](https://user-images.githubusercontent.com/10185314/114843955-a2852c00-9dda-11eb-8679-9e9f1584ddf2.png)
- Portfolio with non-zero balance:
![image](https://user-images.githubusercontent.com/10185314/114843640-50dca180-9dda-11eb-98bb-ab9814837d0c.png)
- Assets with all coins with zero balance:
![image](https://user-images.githubusercontent.com/10185314/114843657-53d79200-9dda-11eb-908b-8d15e6af136e.png)
- Settings with all coins enabled:
![image](https://user-images.githubusercontent.com/10185314/114843684-5c2fcd00-9dda-11eb-8a7b-6cc655f36e5b.png)

Suite: web 21.4.1 1baa8ce
Browser: Chromium 89.0.4389.82
OS: NixOS 20.09
Device: 1.9.4 public
