### ISSUE TITLE
Configurable gap limit

### ISSUE THREAD

**Issue by jooray** [trezor/trezor-suite#3504]
**Is your feature request related to a problem? Please describe.**
I am using my Trezor as a wallet for btcpayserver. The problem is with gap limit - if there are 20 "empty" addresses, which is quite common (customers goes to checkout and does not complete it or chooses lightning as a payment method), I stop seeing transactions on my Trezor. 

**Describe the solution you'd like**
Advanced settings per coin to configure gap limit to an arbitrary number.

**Describe alternatives you've considered**
There are options (electrum, btcpayserver's vault), but they all have limitations. Trezor Suite is the most current way to use my Trezor.

Of course I could send coins to addresses within the gap limit and then the transactions would appear. But that's just unnececssarily spamming the blockchain.

**Additional context**
https://docs.btcpayserver.org/FAQ/FAQ-Wallet/#missing-payments-in-my-software-or-hardware-wallet

**Comment by prusnak** [comment]
We might have to decide whether this feature should be only enabled if a user is running their own blockbook backend or their own [full node](https://github.com/trezor/trezor-suite/issues/2737) to limit the load on our public blockbook servers, but maybe that's not a big issue afterall.

**Comment by stepmes** [comment]
Thanks very much for this input, we're noting it down and will consider it when working on future improvements.

**Comment by karliatto** [comment]
Configurable gap limit was added as experimental feature to Trezor Suite in last release.


In order to use it for now it should be enabled in "Experimental Features" in settings.

1. Enable it in experimental features in "Settings"

<img width="1353" height="196" alt="Image" src="https://github.com/user-attachments/assets/dbd7d16c-ba66-44f4-bbd8-004adc1ba23a" />

2. Go to "Coins" configuration -> Bitcoin

<img width="655" height="642" alt="Image" src="https://github.com/user-attachments/assets/82769c33-2348-4594-9778-ae952026cad5" />

3. Change it.
