### ISSUE TITLE
Performance tracking via Sentry

### ISSUE THREAD

**Issue by jerechinsky** [trezor/trezor-suite#3526]
Raf mentioned that there's a performance tracking feature in Sentry.

**Comment by keraf** [comment]
- More info: https://sentry.io/for/react/
- Setup: https://docs.sentry.io/platforms/javascript/guides/react/performance/

It would be also worth measuring the impact this has on performance. And of course, we shouldn't load the tracer if the user disabled analytics.

**Comment by slowbackspace** [comment]
I was more interested in cpu/memory usage which, after quick reading through docs, won't be included in these reports. But we can enable it anyway since it should be rather trivial, although I am not sure if metrics like first contentful paint are helpful in case of long-running app which needs few seconds to setup communication with bridge/connect/device anyway 😁 This is more useful for websites where loading things as quickly as possible is important in order not to lose customers, which isn't really our case.

<img width="805" alt="Screenshot 2021-03-09 at 13 19 53" src="https://user-images.githubusercontent.com/6961901/110469607-24967c80-80da-11eb-890a-a0e00cc9293a.png">

**Comment by keraf** [comment]
Yeah we definitely won't need these metrics. But looking at the info page, it looks like it's possible to get some more insightful metrics on how the app performs in general:
![](https://www.sentry.dev/_assets2/static/performance-waterfall-4cf0f3924387628fb6f537dc050f9871.png)

It looks like quite a lot of info, so I'm really wondering what's the trade-off. 

Edit: The screenshot looks like it's taken from a back-end, but as it's displayed on the React page, I guess it should be possible to do something similar with front-end? Never really used Sentry, so just guessing.
