### ISSUE TITLE
Exchanging ERC-20 Token uses wrong target (exchange) address

### ISSUE THREAD

**Issue by tylkomat** [trezor/trezor-suite#3547]
**Describe the bug**
I tried to exchange STORJ to ETH using changelly from inside the suite and the transaction failed. Gaslimit and price looked fine, but then I noticed that target address was the contract address of the token. I'm no expert in this, but I think this is wrong.

**Info:**
 - Remembered Wallet: no
 - Suite Version: 21.3.1
 - Browser: firefox, 86.0.1
 - OS: windows 10, 19041
 - Bridge: 2.0.27
 - Firmware Version: model T, 2.3.5 

**Steps to reproduce:**
1. Try to exchange a ERC-20 token using builtin exchange options.

**Expected result:**
Tranaction should succeed and tokens should be exchanged

**Actual result:**
Transaction fails. On trade tab the transactions are shown as pending.

**Screenshots:**
![transaction-failed-2](https://user-images.githubusercontent.com/815915/111275718-bd774b80-8636-11eb-9bcf-693200e86470.png)
![transaction-failed](https://user-images.githubusercontent.com/815915/111267572-62405b80-862c-11eb-984b-6ae46bfb4f5c.png)

**Comment by martinboehm** [comment]
The transaction is correct, just run out of gas. Because the transaction failed, only the ETH part of the transfer is shown, not the ERC20 contract transfer.
While the limit seems reasonable, it may have been an unlucky case that it consumed more gas than usually, see https://ethereum.stackexchange.com/questions/44643/why-gas-used-are-different-for-same-transfer-tx. 

When looking at the successful transactions around https://eth1.trezor.io/address/0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC?page=22, many consumed more than the limit of 32296 from this transaction. It brings up a question if the estimate from `geth` is not too optimistic and we should not increase the limit of ERC20 transaction by multiplication by some constant (like 2), to make it more reliable.

Maybe @szymonlesisz could check that too.

**Comment by tylkomat** [comment]
@martinboehm It is still strange for me that the target address is the [token contract (0xB64ef51C888972c908CFacf59B47C1AfBC0Ab8aC)](https://ethplorer.io/address/0xb64ef51c888972c908cfacf59b47c1afbc0ab8ac) address and not some other address (of the exchange).

**Comment by martinboehm** [comment]
This is the way ERC20 transfers are done. Check a successful transfer [here](https://eth1.trezor.io/tx/0x51f7556e3112d63672d802e4af417440370fd35180ea4f4cf14381feca9a7c04). The ETH part is from the source address to the contract address, the token part is from the source address to the destination address.

**Comment by tylkomat** [comment]
> ERC20 transaction by multiplication by some constant (like 2), to make it more reliable.

I just saw that the [gastracker](https://etherscan.io/gastracker) is basing their estimate for ERC-20 tokens on 65000 gas limit, maybe that is a good value for you too
