### ISSUE TITLE
Labels incorrectly shortened in Firefox

### ISSUE THREAD

**Issue by Dehumanizer77** [trezor/trezor-suite#3549]
Labels are incorrectly shortened in the web suite in Firefox

**Steps to reproduce:**
1. Log in to suite
2. Go to accounts and add label to any transaction or check a transaction that already has a label set
3. Label is always shortened by cutting last two characters and adding 3 dots (e.g. "test" is shortened to "te...")

**Info:**
 - Suite version: desktop 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.3.1 Chrome/87.0.4280.141 Electron/11.2.1 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1843x1152
 - Device: model T 2.3.2 regular

**Expected result:**
Short labels are not shortened

**Actual result:**
Short labels are shortened

**Screenshots:**
![Untitled](https://user-images.githubusercontent.com/1876451/111318168-152cab80-8665-11eb-82ba-089f7761c0cc.png)
(the original label was "->Binance")

**Note(s):**
Apparently the problem is only with Firefox. Chrome is OK, electron app is also ok.

**Comment by jerechinsky** [comment]
I could replicate this. 

 - Suite version: web 21.3.1 (1dbc5b720515c39a47f1dc58391dbebf1d766394)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:86.0) Gecko/20100101 Firefox/86.0
 - OS: MacIntel
 - Screen: 2560x1080
 - Device: model T 2.3.5 regular

Labels are always cut off by one or two characters no matter how long they are in Firefox. 

![short labels](https://user-images.githubusercontent.com/75733878/111455775-811b1c80-8716-11eb-890f-1a3a8feff84a.gif)
---

I'm guessing this is a frontent issue. @tomexx please suggest if otherwise.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.4.0 (e9429cf6d1aa7af9466cc93d9fd842e9c219aa3f)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
 - OS: Linux x86_64
 - Screen: 2560x1440
 - Device: model T 2.3.6 regular
