### ISSUE TITLE
Allow using custom blockbook backend for coin not present in the list

### ISSUE THREAD

**Issue by yura-pakhuchiy** [trezor/trezor-suite#3566]
In wallet.trezor.io user can specify custom backend for coin supported by Trezor, but not officially supported by the wallet. Eg. it works with https://blockbook.firo.org. But the suite allows adding custom backends only for officially supported coins by the suite. Would be great to be able add custom coin/blockbook like it was possible in the wallet.

**Comment by tsusanka** [comment]
I am a bit confused here @yura-pakhuchiy. If you set your custom blockbook for Firo, how do you use the coin then when it is not supported by wallet.trezor.io?

**Comment by yura-pakhuchiy** [comment]
> I am a bit confused here @yura-pakhuchiy. If you set your custom blockbook for Firo, how do you use the coin then when it is not supported by wallet.trezor.io?

By not officially supported I've meant it is not present in the list on the left side. But it works (and many other coins I believe), try it yourself, just enter custom blockbook server.

**Comment by yura-pakhuchiy** [comment]
https://firo.org/guide/using-trezor-with-firo.html

**Comment by tsusanka** [comment]
I see. Sorry but we do not plan to support such feature in Suite. It is out of our capabilities to support each and every altcoin and 
the fact that Firo works with wallet.trezor.io is not really something we supported, more like a side-effect of how wallet.trezor.io works. It seems very specific to Firo because most of altcoins have different signing process which the Suite would have to support.

**Comment by yura-pakhuchiy** [comment]
I believe it is not only Firo, but the most of bitcoin-like coins defined in https://github.com/trezor/trezor-firmware/tree/master/common/defs/bitcoin. Most of them are implemented via only JSON definition file which covers all their's differences to bitcoin and major supported altcoins without any extra code in firmware. The only exception is few coins like Decred and Groestcoin which indeed will not work, because they use different hashes for transaction signing and implemented in Trezor firmware via special curve names. But most of the coins use different hashes only for mining, while keeping double SHA256 for transaction signing. All other differences are already supported in firmware, connect and web wallet via parameters in JSON definition file.

I do not ask to add official support for all these coins, just a way to extend https://github.com/trezor/trezor-suite/blob/47f38ff53cb28c8d1e2953758b13140d81598cfa/packages/suite/src/config/wallet/networks.ts (and maybe few other files) without rebuilding trezor-suite myself. Some interface to enter parameters for coin (maybe just blockbook server url and all the details probably can be fetched from it), or just ability to read custom coin parameters from a file on user's computer (coin developers can provide these files to users).

BTW, this will also fix https://github.com/trezor/trezor-suite/issues/3568, allowing to use not only signet and LTC testnet, but all testnets supported by Trezor.

**Comment by stepmes** [comment]
Thanks, @yura-pakhuchiy! I'm adding your request to our list of suggestions related to improving the support of external projects. This way, it will be included in the prioritization of future work on Suite.

**Comment by nextux** [comment]
> I believe it is not only Firo, but the most of bitcoin-like coins defined in https://github.com/trezor/trezor-firmware/tree/master/common/defs/bitcoin. Most of them are implemented via only JSON definition file which covers all their's differences to bitcoin and major supported altcoins without any extra code in firmware. The only exception is few coins like Decred and Groestcoin which indeed will not work, because they use different hashes for transaction signing and implemented in Trezor firmware via special curve names. But most of the coins use different hashes only for mining, while keeping double SHA256 for transaction signing. All other differences are already supported in firmware, connect and web wallet via parameters in JSON definition file.

100% agree with this comment.  There would be a lot of Bitcoin derived projects that happen to use Blockbook based explorers that have used the Trezor Wallet feature of switching to a custom backend.

https://wiki.trezor.io/Fujicoin_(FJC) on the wiki describes the how.   Given that Wallet support is going, I'll be moving my FJC off this method, but feel that other coins that have taken advantage of this process, may have difficulty accessing their coins.

**Comment by fujicoin** [comment]
To address the retirement of Trezor Wallet, fujicoin.org has released the Fujicoin Trezor Suite because of the need to support users.
https://github.com/fujicoin/trezor-suite/releases/tag/f21.12
https://www.fujicoin.org/en/hardware_wallet

The following three codes seem to be crucial when implementing Fujicoin in Trzor Suite.
https://github.com/fujicoin/trezor-suite/blob/c00b9f2e4b0e0db3c4acd5f46e444d81231aceaa/packages/suite/src/config/wallet/networks.ts#L57
https://github.com/fujicoin/trezor-suite/blob/c00b9f2e4b0e0db3c4acd5f46e444d81231aceaa/packages/utxo-lib/src/networks.ts#L100
https://github.com/fujicoin/trezor-suite/blob/c00b9f2e4b0e0db3c4acd5f46e444d81231aceaa/packages/suite/src/utils/wallet/__fixtures__/accountUtils.ts#L433

Most of the information needed to write these codes is in the trezor-firmware repository.
https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/fujicoin.json

The only missing information seems to be the blockbook URL.

From the above, if you want to make Bitcoin-like coins other than the default coins available to users in Trezor Suite, it seems that users only need to enter the coin name and blockbook URL.

We look forward to the development of Trezor Suite.
