### ISSUE TITLE
INVITY Suite mistakenly marks destination address (XTZ, XLM) as invalid during Exchange Flow

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#3626]
**Describe the bug**
During Exchange flow, to be exact when user is specifing which address should the exchanges coins arrive at, Suite checks whether or not that address (not in Suite!) is correct or not. 

**Info:**
 - Remembered Wallet: No
 - Suite Version: app version commit 95311f19
 - Browser: , version N/A
 - OS: Windows 10 Version 10.0.19042.867
 - Bridge: 2.0.3.1 rev 5f53132
  - Firmware Version: T1 1.9.4. public

**Steps to reproduce:**
1. Go to Accounts > Trade > Exchange
2. Select either XTZ or XLM coin, fill the rest of the form correctly for an exchange
3. Click compare offers
4. Select a deal, confirm it
5. Fill the "Receiving address" properly
6. Get error notification when trying to proceed 

**Expected result:**
Suite will accept the addresses as valid and exchange can be completed

**Actual result:**
Suite incorrectly marks these destination addresses for XLM and XTZ as invalid, even though the are not (copied directly from our 3.rd party wallets and checked on blockchain explorers).

XML
GAF6GF7PBMZ7EN6RFTTIWO5NVGEP75EW4UI3W5I6ZTMAM45CV6E6G6X4
GAEB3R4UTE5F47XOVOJ5REFVR6A5O7NQL2UAJGTQGN2ECPCXNMLYVCER

XTZ
tz1V9HTZ7UjoQLL97z4KUh1Xb2UY9HxJBfr3

**Screenshots:**
![image (8)](https://user-images.githubusercontent.com/58593111/114449833-89f7f480-9bd5-11eb-8fd9-cde97852ea72.png)
![image (7)](https://user-images.githubusercontent.com/58593111/114449840-8c5a4e80-9bd5-11eb-8f5b-a2d3f6f805ea.png)
![image (9)](https://user-images.githubusercontent.com/58593111/114449953-b0b62b00-9bd5-11eb-97e4-70dd7064c77e.png)
![image (6)](https://user-images.githubusercontent.com/58593111/114449847-8e241200-9bd5-11eb-831c-3ea8516b69aa.png)

**Comment by martinboehm** [comment]
@wendys-cats The issue is confusing:

The address `tz1V9HTZ7UjoQLL97z4KUh1Xb2UY9HxJBfr3` is a valid Tezos (XTZ) address, see https://tzstats.com/tz1V9HTZ7UjoQLL97z4KUh1Xb2UY9HxJBfr3, and is correctly validated as Tezos address by Suite. It is not an ADA address.

The Stellar (XLM) addresses `GAF6GF7PBMZ7EN6RFTTIWO5NVGEP75EW4UI3W5I6ZTMAM45CV6E6G6X4` and 
`GAEB3R4UTE5F47XOVOJ5REFVR6A5O7NQL2UAJGTQGN2ECPCXNMLYVCER` are validated correctly in the Suite, but they are neither ADA nor XTZ addresses.

You did not give an example of any Cardano (ADA) address, but picking a random one from the Cardano explorer, `DdzFFzCqrhst9sFs2cCM8QAmHqHC4rvkN6iH5gYNhjUHyVXgkH5vwkKdLV4aKLp4HM33WXd9awi5oV4sZCK95M2je9BsUQUvFxHsRzPR`, you can check, that Suite is validating it fine.

**Comment by wendys-cats** [comment]
@martinboehm sorry for the confusion, wrote it in a hurry and mixed something else into it, it is sorted now (issue is for Tezos and Stellar, there is no Cardano). 
The issue, however, still stands, as can be seen on the screenshots - Suite did not validate correctly neither the XLM nor XTZ address, even though both of them are valid and existing addresses.

**Comment by martinboehm** [comment]
Actually, the problem is not in the Suite. The error was returned from our partner, CoinSwitch, which probably had a temporary issue with validation of addresses. I am not able to reproduce it now as they probably fixed the error on their side.
I recommend to close the issue.

**Comment by wendys-cats** [comment]
@martinboehm thank you for looking into it! Closing the issue now.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 21.5.0 (130b17ff0d52b67079d29b4e7250637528be1def)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.5.0 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model T 2.4.0 regular
