### ISSUE TITLE
Suite is not detecting the previously configured passphrase and showing hidden wallet as empty.

### ISSUE THREAD

**Issue by akshay-na** [trezor/trezor-suite#3682]
**Describe the bug**
I have a hidden wallet in Trezor Suite Desktop App with a passphrase. When I try to use the same passphrase to access the hidden wallet from the Web version of the Trezor suite, it will show that the hidden wallet is empty. I tried to access the hidden wallet through the Web version of Trezor Suite both from Mobile and Desktop but the result was same, empty wallet. If I access the hidden wallet from the Desktop app on which I had it configured in the past, it will show the funds and detects the hidden wallet. Even the Desktop apps that are installed on another desktop/laptop have the same problem.

But the balance is showing up in the web wallet regardless of what device am using. 

**Info:**
 - Remembered Wallet: No
 - Suite Version:  21.4.1
 - Browser: Chrome Version 90.0.4430.93
 - OS: Windoes 10, Build 19042.928
 - Bridge: Version 2.0.27
 - Firmware Version: 1.9.4 , Trezor One

**Steps to reproduce:**
1.  Create a hidden wallet with a passphrase="Password123" on the Desktop version.
2.  Go to the Web version of Trezor Suite and try to access the hidden wallet with the same passphrase="Password123"
3.  It will say that the hidden wallet for the passphrase="Password123" is empty.
4.  Go back to the Desktop App eject the hidden wallet and try to access it again, it will detect the wallet.
5.  Try the Desktop app on another desktop/laptop and again the hidden wallet won't be discovered with the same passphrase="Password123".
6.  Check the balance in the Web wallet with the same passphrase="Password123" and it will show all the balance.

**Expected result:**
To get access to my funds via Trezor Suite regardless of what device am using.

**Actual result:**
Am able to access my funds only on the Desktop version of Trezor Suite in which I created my hidden wallet in the first place.

**Note(s):**
1. Web wallet is working completely fine and I can still access my funds via web wallet through Desktop/Mobile.

**Comment by randallmbriggs** [comment]
Hi Akshay! How did you resolve this issue? I was experiencing something similar. Thank you!

**Comment by TwoLamps** [comment]
Hi Akshay! I am having a similar problem. See my post on Reddit. How did you resolve this? https://www.reddit.com/r/TREZOR/comments/10fc13o/exact_same_passphrase_is_no_longer_working_to/

**Comment by TwoLamps** [comment]
Thanks is advance for your help!

**Comment by TwoLamps** [comment]
Here's what I posted on Reddit:

A year ago I got a Trezor Model T to store some ETH, ERC-20 tokens, and some NFTs (all on the Ethereum blockchain). I used the new passphrase feature and made several hidden wallets to store the assets using those passphrases. It all worked fine many, many times to access those hidden wallets with those passphrases both using Trezor Suite on my Mac and the MetaMask Trezor plugin. Now, after a year of not touching my hardware wallet or anything related to crypto, I am trying to access my assets in those hidden wallets, but now when I use those exact same passphrases (and I know I'm using the same ones since I have them written down on a piece of paper) the Trezor Suite software (and MetaMask) are opening up empty wallets with different addresses that have no transaction history at all. I have no idea what happened. It's almost like the Trezor Suite software was updated during that time and now uses a different algorithm to calculate the hidden wallet address and private key pair based on the text of the passphrase. I know that sounds crazy, but I don't know what else could have happened since nothing else has changed. I did find one other case of someone using the same passphrases on Trezor Suite on different computers and having different, empty hidden wallets come up. See the link below. They didn't say what resolved the problem. I even tried upgrading the firmware on my Trezor Model T since a new version had come out to see if that would help, but the passphrases were still producing the same empty wallets with no transaction history as before. Any help with this would be greatly appreciated. As you can imagine, this is a scary and bewildering situation. Thank you so much!



https://github.com/trezor/trezor-suite/issues/3682

**Comment by DEN123-create** [comment]
TWOLAMPS! решили проблему????

**Comment by ghost** [comment]
Having similar issue, as many others are too. My seed phrase is correct, My passphrase is correct. I am not unable to add or access my Passphrase wallet except on the one browser extension it was on, but no transactions will go through. Have tried multiple browsers, wallets, different versions of the Suite software, Trezor T firmware. Nothing works.. https://forum.trezor.io/t/passphrase-is-no-longer-working-empty-wallet/11336

This is very frustrating and I know from the hundreds of transactions I've completed that I am not making an error.
