### ISSUE TITLE
Feedback | Bug submission

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3714]
**Design:** [Zeplin](https://zpl.io/aBzxkDq), Spec: [Notion](https://www.notion.so/satoshilabs/Feedback-Bug-report-d7cfccbacf084ce3b2bb97ce8c24e8e2#ddfe5670679f4e039a598c3a35d9c3b2)

**Entry point:**
- Learn & Discover › Bottom of the panel › Feedback / Bug report

**Comment by tsusanka** [comment]
The design also has "upload image" feature. We need to think about it in the back-end architecture.

**Comment by goodhoko** [comment]
@matejzak it would be very nice if answers to these questions could be incorporatedv into the feature spec (Notion) and, if applicable, to the design (Zeplin). I don't have privileges to edit Notion so asking you.

- Do we really want to constraint the lenght of the submitted text as hinted by the designs?
    - **no**
- How the bug submission feature relate to the feedback submission feature?
    - **Importantly, we need to be able to triage these two streams by different pople. Eg. feedback by UX researchers bugs by QA or Product managers.**
- Do they need to be shipped together?
    - **If we can't ship both features with the official release we can ship just the feedback submission with slightly altered wording that would fit both usacases. However, don't consider that as much of an option. 😅**
- Shall the screenshot be taken automagically by merely clicking the button?
    - **No. We rather want to give users full control over what they share with us. Clicking the button should open the classic "Select a file" system dialog.**
- Do we want to allow users to add more screenshots?
    - **No. One is enough. (for now).**
- Shall we give users back some kind of ID of the reported bug?
    - **For now a simple confirmation (or error) toast will suffice.**

_For the record: these questions were asked by me (and @tsusanka) and answered by @matejzak personally in the office._

**Comment by goodhoko** [comment]
@matejzak One more product consideration I just realised is that the feature as designed now gives us no way to reach the person who reported a bug or feedback. That could render big portion of the reports useless as it's usually pretty rare for people to provide all information needed for reproducing a bug on a first try.

An optional email input could be a good idea. .)

**Comment by tsusanka** [comment]
@goodhoko I have added your info into Notion.

@matejzak I think we really should split this into two Specs and two Github isses. It is somewhat connected in design but apart from that these are two distinct features.

@goodhoko I am actually not sure this is a good idea. Asking for email might give users the idea we will get back to them which is unrealistic at the moment. On the other hand when Support's capacity would clear up we _could_. I am just not sure asking for email doesn't give a false hope to our users that we'll get back to them because that might not be the case.

**Comment by goodhoko** [comment]
> I have added your info into Notion.

Thanks!

> I think we really should split this into two Specs and two Github isses. It is somewhat connected in design but apart from that these are two distinct features.

The underlying infrastructure is basically identical for both. I think it's good to have this single issue where we can design and implement the common parts. But yeah I'd be for two other sub-issues for each of the features especially for the UI and data processing parts wich will differ the most.

> I am actually not sure this is a good idea. Asking for email might give users the idea we will get back to them which is unrealistic at the moment. On the other hand when Support's capacity would clear up we could. I am just not sure asking for email doesn't give a false hope to our users that we'll get back to them because that might not be the case.

Very good point! (Though a bit sad.) Let's leave that to @matejzak. .)

---

Anyway I finally wrote down the BE tech spec for this and posted it as a [pull request](https://github.com/trezor/trezor-suite/pull/3764) so that it's easy to comment on it. Please take a look at it. Once we agree on that we can start provisioning the needed infra.

**Comment by glacierbits** [comment]
Email: 

- The feature is not meant to open a 2 way communication channel, but rather quantify problems and point in the the direction where we should look for them  
- Bear in mind, the fact user thinks it's a bug and/or feature request doesn't necessarily means it's in fact bug and/or feature request. Again, this distinction is just suppose to help us label them and triage with that user story in mind. 
- A different feature "Contact support" (that may come in many shapes and forms) may appear in Suite eventually, but certainly not now for the reasons mention by @tsusanka and since this need to be evaluated from the support & business point of view

**Comment by goodhoko** [comment]
> The feature is not meant to open a 2 way communication channel, but rather quantify problems and point in the the direction where we should look for them

@matejzak Ack. Makes sense. Thanks.

_meta: this bit would be a perfect non-goal for the product spec. 😉_

**Comment by goodhoko** [comment]
@trezor/qa Sorry for late update. We had some troubles in the development and it resulted in scoping down this feature for this release. Here are acceptance criteria for *this release*:
- The user can open the bug/feedback submission forms by clicking on the bulb icon floating on the bottom-right corner of the app and then clicking on 'Feedback or Suggestion` button at the bottom.
- There should be two forms one for submitting bugs and one for giving a general feedback about the app.
- The bug form should consist of
    - category drop-down. **The designs in Zeplin indicate the correct category should be pre-selected automatically, but this is the first thing we postponed for the next release**.
    - The body.
    - The screen-shot feature. **Was postponed as well.**
- The feedback submission should consist of:
    - rating scale represented by emojis.
    - The body.
- Submitting bug or feedback should
    - Fire a GET request to `data.trezor.io/suite/[bug|feedback]` with the data encoded in query string.
    - Result in a toast notification indicating success or failure (in case the app is offline for example).

Here's an issue that tracks tasks originally required for this feature that didn't make it to this release: https://github.com/trezor/trezor-suite/issues/3817 (Note that it mixes the Bug/Feedback submission feature with the [Guide feature](https://github.com/trezor/trezor-suite/issues/3713) 😕 .)

Sorry for any inconveniences caused by changing the requirements on the go. Don't hesitate to ping me if more questions arise. .)

**Comment by STew790** [comment]
I have 2 questions regarding this.

1. Should the points from screenshot 1 in the "Suite guide" article be links or not? 
2. Shouldn't the button in the screenshot 2 say "Send suggestion" rather then "Send report"?

Scr.1
![image](https://user-images.githubusercontent.com/48477147/120818367-d8c96700-c552-11eb-9b7f-30ce4baee94e.png)
Scr.2
![image](https://user-images.githubusercontent.com/48477147/120818430-e848b000-c552-11eb-9dee-cbcf7170d27e.png)

**Comment by goodhoko** [comment]
1. I believe they should.
2. Yeah, that sounds better. 

Can you file an issue for these fixes (and any more you'll find) so that we can track and fix them in this release? .)

**Comment by bosomt** [comment]
Maybe we can now  remove link to typeform feedback ? 

<img width="187" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/120934952-7742fd00-c6f8-11eb-9dc0-7f00ff220c33.png">

**Comment by goodhoko** [comment]
> Maybe we can now remove link to typeform feedback ?

@matejzak should know the answer to this. .)

**Comment by tomexx** [comment]
beta badge will be removed with this PR
https://github.com/trezor/trezor-suite/pull/3833

**Comment by STew790** [comment]
@goodhoko Issues created here https://github.com/trezor/trezor-suite/issues/3852 and here https://github.com/trezor/trezor-suite/issues/3851

**Comment by sorooris** [comment]
Reported an issue as well https://github.com/trezor/trezor-suite/issues/3823

Anyway, let's approve yo!

**Comment by bosomt** [comment]
**QA OK**

Info:
 - Suite version: desktop 21.6.1 (4f358fd151fc1962f30f84a855b82213d958aae7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4_0) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.6.1 Chrome/89.0.4389.69 Electron/12.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.3.6 regular
