### ISSUE TITLE
Investigate required firmware feature

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#3727]
We have a feature to enforce firmware update in Connect by marking the firmware "required". We should investigate both from the technical and UX point of view if it works in Suite so we can start using it again.

**Comment by tsusanka** [comment]
We currently have versions 1.6.1 and 2.0.5 labeled as required. @STew790 could you please investigate if Suite when accessed with older firmware forces you to update? In another words if you can send BTC for example or you are blocked by a firmware update modal.

**Comment by STew790** [comment]
I tried it with FW 1.6.1 (BL 1.4.0) as you mentioned and this one lets you in just fine without any restrictions. I tried an older FW as well, 1.5.2 (BL 1.3.2), and this one requires you to update the FW otherwise it won't let you into the suite at all.
With TT, the FW 2.0.5 lets you in the suite as well without any restrictions.

**Comment by tsusanka** [comment]
Awesome, so it seems to work! Just in case you still have the FW available could you please printscreen/record how it looks when you plug in 1.5.2?

**Comment by tsusanka** [comment]
Ping @STew790

**Comment by STew790** [comment]
Sorry for the delay. Yes, it works just as described. You can see a video with 1.5.2 below.

https://user-images.githubusercontent.com/48477147/119959236-1a32a300-bfa4-11eb-8722-27b9766e9fde.mp4

**Comment by tsusanka** [comment]
Great, thx. Closing then!
