### ISSUE TITLE
Non-onion custom backends stay enabled when Tor is enabled

### ISSUE THREAD

**Issue by sorooris** [trezor/trezor-suite#3744]
**Describe the bug**
Enabling Tor seemingly does not disable any custom backends that are set in the Advanced settings which could compromise the level of protection provided by connecting to the Tor network. 

**Info:**
 - Suite Version: app 21.5.1 (4d09d88)
 - OS: macoS Big Sur 11.3.1
 - Bridge: any
 - Firmware Version: any (tested T1 1.9.4 public)

**Steps to reproduce:**
Precondition: custom backend of an arbitrary coin is set.
1. Launch Suite,
2. Let discovery finish,
3. Enable Tor,
4. Navigate to Settings -> Coins -> Advanced settings (of an arbitary coin from the precondition) and observe the links.

**Expected result:**
Custom backend URLs are either disabled and circumvented in favor of onion links, or the user is warned the custom URLs are a security risk after enabling Tor.

**Actual result:**
Non-onion custom backends stay enabled when Tor is enabled.

**Comment by jerechinsky** [comment]
@matejzak @tsusanka do you agree with the expected result?

**Comment by glacierbits** [comment]
Looping in @tomexx since we talked about this particular case, and came to a conclusion the current behavior is OK (for now at least since it is an advance feature). 

That being said, OK is not necessarily perfect, therefore I kindly ask @tsusanka to weigh in and provide an opinion whether the custom BE URLs should be automatically routed through the Tor network once Tor is enabled. 

If so, 2 UX cases need to be handled: 

- Tor enabled first › Placeholder for the onion address in the Custom BE input (?) 
- Custom BE enabled first › Custom BE addresses automatically turn into onion address (?)

**Comment by tsusanka** [comment]
Hm, this is a complicated topic IMHO. Because you might want to set up a private non-tor BE and you still want to route to there via Tor. What makes more sense is if you enable Tor and as well have a custom .onion BE. But I can image a use case where you want to enable Tor, don't want to use our .onion service and for some reasons can't run your own .onion BE, you can run only the traditional one. I am not sure we should proclaim such solution as incorrect, I guess it depends on the user's setup.

I would like to know what @prusnak thinks he is far the most knowledgeable in the are of Tor.

**Comment by prusnak** [comment]
Yes, connecting to clearnet backends via Tor is a legit use-case. But in this case the clearnet BE has to run HTTPS. Connecting to clearnet HTTP via Tor is dangerous and should not be allowed.

**Comment by tsusanka** [comment]
How about we simplify it altogether and warn if user enters a HTTP (non-HTTPS) backend? For both Tor enabled and disabled. We want to push HTTPS everywhere anyway. It is a nice feature, simple and useful.

**Comment by prusnak** [comment]
> We want to push HTTPS everywhere anyway. It is a nice feature, simple and useful.

Well, there are still many people who run their nodes on local network (Raspberry Pi) reachable via IP address with no HTTPS on it (you can't issue a HTTPS cert for an IP or local hostname).

**Comment by keraf** [comment]
I think using non-HTTPS backends on non-local domains/IPs will break because of the browser policy (mixed content). To be confirmed but I would still think having validation on the input would be nice.

I'm not sure if it would make sense to have two settings for custom backends, one for normal and the other one for Tor,  defaulting to t.io and t.onion backends respectively.

**Comment by tsusanka** [comment]
I am personally in favor of closing this. It seems to me as too niche and having too many different variants to deal with it. We should try setting up HTTP backend though to validate what Raf is saying but we should make a new issue about that.
