### ISSUE TITLE
Remove the discovery loading modal

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#3785]
Please remove this loading modal

<img width="629" alt="Screen Shot 2021-05-23 at 23 32 50" src="https://user-images.githubusercontent.com/29627086/119278868-f841c500-bc1f-11eb-8bb2-0f779dc102dc.png">

_If I am not mistaken, the modal is shown only on a Hidden (passphrase) wallet._ 

**Rationale:** 

1. It's redundant › The user has a clear feedback the accounts are being loaded via skeleton loaders and progress bar
2. If it wasn't present, the user could start interacting with the first loaded accounts right away
3. For some reason this modal is shown for just a few first accounts, than it disappears & other loaders continue to run

**Comment by slowbackspace** [comment]
I think the arguments for removing this modal are wrong (not saying it couldn't be replaced with something else). The purpose of this loading is to prevent a user making a typo. That modals indicates that we are looking through accounts on given passphrase and searching for non-zero balance. If there is such an account we can be sure that the passphrase was used before and thus it was not a typo by a user. If we don't find any non-empty accounts then we will ask for passphrase confirmation in order to prevent coin loss.

**Comment by szymonlesisz** [comment]
this modal was added exactly to prevent (2), we didn't want to allow interaction with the account until we (and the user) were sure that he is using a proper passphrase.
Example: prevent copy receive address before passphrase confirmation.

Another motivation is to keep the context and prevent navigation. Example:
- accounts are loading
- user goes somewhere else (let say settings)
- user goes back to "dashboard" and after a while "passphrase confirmation modal" appears out of nowhere

Ad 3. Modal is shown until discovery process hits first used/non-empty account
