### ISSUE TITLE
Settings - Inappropriate Usage data switch text

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4094]
**Describe the bug**

Looks like `Usage data` switch text in Suite settings got mixed with different description or something similar. 

**Steps to reproduce:**
1. Load Suite 21.6.1 
2. Load suite 21.7.1 or 21.8.0
3. Compare `Usage data` texts

**Info:**
 - Suite version: web 21.7.1 (24cc565a3badd85ab48b30348022471dfd85f90e)
 - Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
 - OS: Linux x86_64
 - Screen: 3072x1728
 - Device: model 1 1.10.2 regular

**Screenshots:**

![image](https://user-images.githubusercontent.com/31506317/127981233-b8427098-416b-4046-9f33-31efcd1cbf1c.png)

![image](https://user-images.githubusercontent.com/31506317/127981290-e8c69d8e-0fb8-4d98-bd77-27aef5f895a4.png)

**Comment by jerechinsky** [comment]
It appears that the original "default" messages are used instead of the corrected "english" from Crowdin. Could you please investigate? @mroz22 

Szymon discovered another one
![Screenshot from 2021-08-05 13-03-46](https://user-images.githubusercontent.com/75733878/128489289-8233cbd1-c994-4995-b8c5-ca8b9a79031a.png)

**Comment by mroz22** [comment]
this should be already fixed I believe (?)
