### ISSUE TITLE
render content to static html for suite-web-landing

### ISSUE THREAD

**Issue by dimasivan** [trezor/trezor-suite#4147]
After removing next.js from the project and using webpack for builds, there is no html content rendered in static file, but just a simple html with `meta`, `noscript` and `div#app` tags.

It causes to crawlers and users without javascript cannot see any content except `this website requires javascript` which is send in response from server. All the content is rendered by javascript on client side.

@trezor/product can help us to specify which content should be rendered to static files for better SEO and also for users without javascript enabled and tech can use webpack to build static files with that content pre-rendered from build.

**production build:**
![image](https://user-images.githubusercontent.com/42174681/129553210-47b525c5-3f6b-4b66-91b7-61b79c130a67.png)

**webpack build:**
![image](https://user-images.githubusercontent.com/42174681/129553439-73a418fa-af61-4282-8108-4432db444845.png)

**Comment by tsusanka** [comment]
@pingpwned I am having problems understanding the issue. You mean "After removing next.js from the project and using webpack for builds, there is no html content but just a 'this website requires javascript' send in response **for those with JS off**"? Or?
What else then HTML it is? Please rephrase the issue so it is clear and provides more context.

**Comment by matejkriz** [comment]
I see this more as a technical question than product question. 

As I see it:
Right now in production, we have the suite landing page (https://suite.trezor.io and https://suite.trezor.io/start/ are the only two pages so far) **prerendered** - it means better SEO, but most of all better UX (user see some content as soon as possible)

This feature we have with Nextjs out of the box. As we are getting rid of Nextjs, we have to ask if we want to implement it in webpack to keep the best SEO/UX or it's not worth the time (or if we should keep the Nextjs there because of that).


I see a product question, but totally unrelated to Nextjs:
**What about to turn off the initial animation of main title and download button completely?** I believe this animation makes the UX worse, because user has to wait longer than necessary for some relevant content (especially download button).

**Comment by Hermez-cz** [comment]
Hi @matejkriz (FYI @pingpwned ) - agreed, static page would be much better than the animation setting main CTA to after a delay...

Without the animation, is the "webpack question" still valid? It will be a bit hard to assess the value/priority of it.

**Comment by matejkriz** [comment]
Yes, "webpack question" is still valid, but as I mentioned, I believe it's more "technical question" - it's obvious, that prerendered page is better than client side rendering from product perspective, but we have to discuss in dev team how to do it and find the best solution.

**Comment by tsusanka** [comment]
What I also see as a production question is whether we need to support Suite download with JS turned off (I would prefer yes as there is no technical need for the JS IMHO).

**Comment by Hermez-cz** [comment]
Thanks, I've created a separate issue for removing the animation #4160
Will be waiting for further tech inputs. Assigning this one back to @alex-jerechinsky

**Comment by jerechinsky** [comment]
Since we're not getting rid of next, I'm closing this.
