### ISSUE TITLE
Improve copy in macOS offering

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#4149]
We are introducing native builds for M1 Apple notebooks (https://github.com/trezor/trezor-suite/pull/4082). The offering now looks like this:

![image](https://user-images.githubusercontent.com/1835345/129559063-5f92a84e-32d2-47c9-8e3a-6e2015e7ab9f.png)

I think both "macOS" should be capitalized the same :). As `macOS` is indeed spelled like `macOS` I suggest two options:
- `for Mac` and `for Mac (Apple Silicon)`
- `for macOS` and `for macOS (Apple Silicon)`

**Comment by jerechinsky** [comment]
Changed to `for macOS` via Crowdin. I am closing it now so it gets moved to the **Needs QA** column and QA can test it during freeze after we sync the copy from Crowdin.

**Comment by Hermez-cz** [comment]
Thanks @tsusanka 
I'd prefer `macOS` over `Mac` for consistency, as `Windows` and `Linux` are OS's, not computer types.
But indeed, it's spelled `macOS`, so I'd go with:
- `for macOS` and `for macOS (Apple Silicon)`

I don't have any strong opinion (or moreover knowledge) about whether to use `for macOS (intel-based)` or similar. But the 2 options above are easy to distinguish even without. Similarly, we might use `for macOS (with M1 chip)` but Apple Silicon should be more future proof and more correct (It's the Mac having some kind of chip, not macOS - so that would have to be Mac with Intel chip vs. Mac with Apple chip, which would be inconsistent with Windows/Linux...)

The `for` seems a bit redundant to me, but completes the possible sentences like "Get desktop app **for** macOS" and similar, so no real harm here.

**Comment by STew790** [comment]
**QA NOK**

The build is present in the selection but it is not unified, as you can see from the screenshot.

**Info**:
 - Suite version: web 21.9.0 (55e489c47ec58c2cddbd05c47d577bec7a28a252)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
 - OS: Win32
 - Screen: 1440x900
 - Device: model T 2.4.1 regular
 
 **Screenshot**
![image](https://user-images.githubusercontent.com/48477147/129576266-3033ebaf-9edf-409a-bd81-b140351c24c4.png)

**Comment by tsusanka** [comment]
Btw @alex-jerechinsky @Hermez-cz we currently do not have a language picker on the landing page. That's something we should have right?

**Comment by Hermez-cz** [comment]
> Btw @alex-jerechinsky @Hermez-cz we currently do not have a language picker on the landing page. That's something we should have right?

@tsusanka Currently, we have a variety of different controls and designs in our navbars and footers all around our "platform". We're working on new designs and their complete unification together with Ondra. It would make sense to improve at least some legacy pages on the go. Will assess this with Ondra and Matej. And the Suite landing page should absolutely be one of the meanwhile improved pages.

**Comment by bosomt** [comment]
**QA OK**

<img width="251" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/131244760-c13ea83a-1cd9-41a3-ad8a-dbf89bc82a9f.png">

**Info:**
 - Suite version: web 21.9.0 (f9ecf819ac9cc809aa78295793c065c508f74e72)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular
