### ISSUE TITLE
Suite Landing Page - Remove animation

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4160]
**Is your feature request related to a problem? Please describe.**
https://suite.trezor.io
Hero section animation delays content and CTA. Rest of the page is loaded and present earlier than the hero section, which is confusing.

**Describe the solution you'd like**
Please remove the animation and make it static.

**Describe alternatives you've considered**
Not needed, static is better than "as is"

**Additional context**
Loosely related to #4147

**Comment by marekrjpolak** [comment]
Fixed in https://suite.corp.sldev.cz/suite-web/fix/4160-remove-hero-animation/.

**Comment by marekrjpolak** [comment]
Still for review in https://suite.corp.sldev.cz/suite-web-landing/fix/4160-remove-hero-animation/.

But because of #4095 and removal of some packages, I've also changed two other animations:
- Fade-in of feature titles/descriptions on landing page
![image](https://user-images.githubusercontent.com/26326960/130606247-aa009bef-c4d1-4a4d-b78a-8f8b1dbfe447.png)
- 'Learn' button expansion in Guide tooltip in Suite
![image](https://user-images.githubusercontent.com/26326960/130605921-c09268ce-c268-4e01-802f-0255620bfaa5.png)

Both animations should look almost exactly as before, but should be checked anyway.

**Comment by sorooris** [comment]
**QA OK**

Animation removed from hero section correctly, content loaded immediately. :heavy_check_mark: 

Environment: [develop](https://suite.corp.sldev.cz/suite-web/develop/), [remove hero animation branch](https://suite.corp.sldev.cz/suite-web/fix/4160-remove-hero-animation/)
Browser: MS Edge 92.0.902.73, Chromium 92.0.4515.107, Firefox 89.0.2
OS: Win10, NixOS 21.05
