### ISSUE TITLE
Start using Bitcoin regtest from trezor-user-env

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4454]
Introduce first e2e test using Bitcoin regtest from [trezor-user-env](https://github.com/trezor/trezor-user-env)

**Comment by karliatto** [comment]
## Thoughts
* The purpose of this task is to make changes in the e2e tests that currently are using the production blockbook websocket API to use a blockbook that will have backend  regtest instance of bitcoind running in locally/CI.
* If we use a regtest instance of bitcoind, we will have to initially "mine" until we get segwit activated so we can use bip84 type of addresses as we use in the e2e tests. It requires to mine 432 blocks as per https://bitcoin.stackexchange.com/questions/110446/why-do-you-have-to-mine-432-blocks-to-activate-segwit-on-regtest
* I guess for some testing scenarios it will be required to have some communication from the test to the regtest, for example:
    1. Broadcast a transaction from suite app
    2. Tell the regtest to mine a block with that transaction
    3. We can find that transaction was confirmed in suite app
* Regtest addresses are different than mainnet ones, regtest are starting like "bcrt..." instead of "bc1". 
* It looks like we could use in the test the function `blockchainSetCustomBackend` to use the localhost/CI blockbook but if we use a `regtest` coin it wouldn't be necessary. 

## Questions
* Since regtest uses different type of address (starting by "bcrt" instead of "bc1") and this coin is not currently in `trezor-suite` we will probably need to add it, as well as to `connect` to [connect](https://github.com/trezor/connect/blob/4037c992b2f265f1b41ff590e65daa303dbd7a08/src/data/coins.json) ?

**Comment by bosomt** [comment]
Anything needed on QA side or we can move it to approved section ?

**Comment by karliatto** [comment]
> Anything needed on QA side or we can move it to approved section ?

@bosomt This adds possibility to do automated test using `regtest` instead of `mainnet` bitcoin backend. There is nothing that can be tested at the application layer.
