### ISSUE TITLE
Update ready for installation in Settings contextual improvement

### ISSUE THREAD

**Issue by Hermez-cz** [trezor/trezor-suite#4463]
Design is OK, we just should differentiate two states:
1. When an update is available to download and install (this state is covered well):
<img width="790" alt="image" src="https://user-images.githubusercontent.com/88533514/140507758-f07bf923-bbee-4bc2-a598-832335a0573b.png">
2. When the update has already been updated, but not installed well:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/88533514/140507869-39ef5e96-92d3-43bf-830f-2e82a7815500.png">

A quick copy improvement could help here.
When the update has been downloaded, but not installed yet, we could show copy:

```
Update ready for installation // EDIT this line is omitted, approved by b-irving
You are currently running version [current version nr.]
Version [downloaded (updated) version nr.] has been downloaded and is ready for installation.
```

**Comment by b-irving** [comment]
Update ready for installation
You are currently running version [current version nr.]
Version [downloaded (updated) version nr.] has been downloaded and is ready for installation.

This is totally fine, very clear for the user @Hermez-cz

**Comment by tomasklim** [comment]
(I contacted Alex about the `.`)
<img width="830" alt="Screenshot 2021-11-11 at 15 18 38" src="https://user-images.githubusercontent.com/33235762/141313856-e470caf2-263e-44c0-831e-317a174f0d5b.png">
<img width="799" alt="Screenshot 2021-11-11 at 15 18 45" src="https://user-images.githubusercontent.com/33235762/141313869-524190a6-0034-4463-8454-f4296d10e246.png">
<img width="802" alt="Screenshot 2021-11-11 at 15 19 05" src="https://user-images.githubusercontent.com/33235762/141313871-bfcf98ff-7934-4e94-9498-2f6392b60743.png">

I omitted `Update ready for installation` because I think it is not required there.

**Comment by STew790** [comment]
**QA OK**

![image](https://user-images.githubusercontent.com/48477147/145394148-4763aacd-812b-4372-a59f-dce17d728ba7.png)
![image](https://user-images.githubusercontent.com/48477147/145394242-b986ce1c-466e-47f6-8425-2a4a670450f2.png)
![image](https://user-images.githubusercontent.com/48477147/145394698-9b40eeac-f558-44b9-b87f-b44f3d1360db.png)


**Info:**
 - Suite version: desktop 21.12.2 (8cedeed1d1da121ab6b3dff4cb6365b9030634a2)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.12.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.4.3 regular
