### ISSUE TITLE
XRP Sign transaction error

### ISSUE THREAD

**Issue by soucek87** [trezor/trezor-suite#4631]
**Describe the bug**
Recently, a few users reported this error: "Sign transaction error: extends Failed to forward request to p2p node" when trying to send out XRP from their Trezor wallet connected to Trezor Suite.

Looks like XRP network is really busy and the default fee is the problem. 

**Info:**
Occurs no matter what Suite version and FW is used.

**Expected behavior**
XRP tx should go through without errors.

**User story**
See forum 
https://forum.trezor.io/t/sign-transaction-error-extends-failed-to-forward-request-to-p2p-node-xrp/5036

**Additional context**
Read this "All global XRP Ledger nodes have a full Transaction Queue"
https://status.xrpl-labs.com/incidents/p4dg7m41cpzt

**Comment by bosomt** [comment]
I can confirm that in recent weeks we have problem to send XRP transactions due to low fees /no idea if there is any fee estimation for XRP/ 
Of course this behavior changes from time to time and probably it depends on network congestion. 


Transaction via exodus - fee 0.005 XRP - no problem
Transaction via Suite    - fee 0.000031 XRP - set manually `Transaction signing error: Held until escalated fee drops.`
Transaction via Suite    - fee 0.000012 XRP - default fee - `Transaction signing error: Can not queue at this time: fee insufficient to replace queued transaction.`


<img width="772" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/145556609-954206c1-3322-4b1e-bac6-44d1f9fb34c9.png">

<img width="773" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/145556695-1e10d99f-7424-41d2-9b1a-fa0b8d249750.png">

<img width="768" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/145557934-4cd23e99-7b50-410a-913b-9b22b6c73da6.png">

**Comment by tsusanka** [comment]
@soucek87 this is due to Ripple backends being congested 😢 . Please inform the user to set the fee manually and if more tickets come up we'll raise the fees for Ripple in Suite. But I would not deal with this until there is more users concerned.
