### ISSUE TITLE
Management of Crowdin's translation source files should be improved

### ISSUE THREAD

**Issue by fujicoin** [trezor/trezor-suite#4803]
@mroz22

Although mesages.ts have been improved by #4777 and #4778, the message improvements proposed in #4769 are not reflected in Crowdin's translation source file (master.json).

As you can see in the screenshot below, the translation is an improved message, but the original text is still out of date. 
This will cause new translators to translate old English sentences.

![crowdin1](https://user-images.githubusercontent.com/7656623/150868410-917ea41f-1beb-4762-95f3-47786bb34811.png)

The contents of messages.ts and Crowdin's master.json should always be in sync.

Anyone who modifies message.ts should contact the Crowdin master.json administrator to ensure that it is updated.

Trezor Suite is a great application. However, if the translation is bad, the evaluation will be lowered.

**Comment by fujicoin** [comment]
@pingpwned
The key name of messages.ts was changed in commit 45cddef.
https://github.com/trezor/trezor-suite/commit/45cddef53f7dbb72752f19df37643c55ecee969c

It is very annoying for the supporters who are helping the translation with crowdin to make such corrections.
---------------------------------------------------------------------------------------------------------------

When a key is added, the supporter can immediately recognize it by the mechanism of crowdin.
However, in the case of the above commit with the key name changed, `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_3` and `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_4` will not be noticed by the supporters even though the English text of the source to be translated has changed at all.

**Comment by fujicoin** [comment]
A key called `TR_SUITE_WEB_LANDING_BANNER_CTA_FROM_MYTREZOR_WRAPUP` has been added to the translation source (master.json), but it does not exist in `messages.ts` or in any other program code.
Why was this added?

**Comment by jerechinsky** [comment]
> The contents of messages.ts and Crowdin's master.json should always be in sync.

100% agree. We **are** trying to do the backports regularly. However, the process **could** be improved. 
	For now, I've cleaned up the English in Crowdin, so we can more easily keep track of the changes in English copy. Only the strings that were actually changed and differ from `default message` are "translated" and approved now, i.e., the ones that will need to be backported. You can see for yourself here: https://crowdin.com/translate/trezor-suite/103/en-en?filter=basic&value=4


> @.pingpwned The key name of messages.ts was changed in commit [45cddef](https://github.com/trezor/trezor-suite/commit/45cddef53f7dbb72752f19df37643c55ecee969c). [45cddef](https://github.com/trezor/trezor-suite/commit/45cddef53f7dbb72752f19df37643c55ecee969c)
> 
> ## It is very annoying for the supporters who are helping the translation with crowdin to make such corrections.
> When a key is added, the supporter can immediately recognize it by the mechanism of crowdin. However, in the case of the above commit with the key name changed, `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_3` and `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_4` will not be noticed by the supporters even though the English text of the source to be translated has changed at all.

I would generally agree that changing a key is a bad idea it should be always avoided. It could lead to loss of valuable work of many translators at once. However in this case I must clarify, that @pingpwned only slightly changed the numbering sequence of a series of keys and added a new key (`TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_5`). His commits didn't create or destroy any keys, `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_3` and `TR_SUITE_WEB_LANDING_DEPRECATION_BANNER_PARAGRAPH_4` were preexisting and still remain there so no data loss could occur. The only change that crowdin registered is in default message. AFAIK when you change default message, Crowdin will un-approve whichever translation was previously approved, so translator can spot it. But it's definitely far from perfect because if there was no approval previously, then it could be hard to spot, so I understand your concern.

These keys are intended for a landing page that is under active development, so I will try to figure out a way to somehow mark these new strings as under active development to warn translators so they can wait until development is finished. Apologies for that.

> A key called `TR_SUITE_WEB_LANDING_BANNER_CTA_FROM_MYTREZOR_WRAPUP` has been added to the translation source (master.json), but it does not exist in `messages.ts` or in any other program code.
> Why was this added?

This was in a different PR at the time, but has been merged since.

https://github.com/trezor/trezor-suite/blob/develop/packages/suite-web-landing/components/FromMytrezorBanner/index.tsx#L146
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/support/messages.ts#L6351
