### ISSUE TITLE
Not possible to change Coins settings when model T in bootloader mode

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4810]
**Describe the bug**
it's possible to change Coins settings when model T in bootloader mode.
Model One works as expected but when model T connected it reports `Update required
`

**Steps to reproduce:**
1. Start latest dev or production version of Suite
2. Connect Trezor model T
3. Observe Coins tab in Settings

**Info:**
 - Suite version: desktop 22.1.1 (e7262e597f6af0487e17ef055a2583425c7a5302)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.1.1 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.3 regular

**Screenshots:**

_Trezor model T in bootloader mode_ 

<img width="772" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151136604-962dd112-adcb-4fbc-bd80-e097420effa7.png">

_Trezor model One in bootloader mode_ 

<img width="795" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/151136658-14447f18-7c54-44d8-af47-878d6f15850d.png">

**Comment by karliatto** [comment]
After investigation:
The issue seams to be that in [connect](https://github.com/trezor/connect) when in bootloader mode we are using "major_version, minor_version, patch_version" that Model T reports as bootloader version to check `UnavailableCapabilities` that are defined by Firmaware version.

Therefore we see that those coins are not available for the current firmware version but it is not true, because we are comparing with bootloader version.

The issue is the same in Trezor One, but it just happens that required firmware version is smaller that bootloader version, so this issue is not happening in this model.

**Comment by karliatto** [comment]
The proposed solution is to remove Coins settings when in bootloader mode since there is not real use case for that.
It still has to be decided how to do the UI for that.

**Comment by karliatto** [comment]
After conversation with @hynek-jina and @Hermez-cz  the final decided solution is to keep the coin selection in bootloader mode active for Trezor One/Trezor Model T and ignore that might be some coins that are not going to work with the current firmware because it is desired to have suite configuration  device-agnostic.

When device is in normal mode it will display that some coin is not working with the current firmware as it is doing now.

**Comment by bosomt** [comment]
**QA OK**

fix is not included in 22.3.1 release checked on staging

**Info:**
 - Suite version: web 22.3.0 (ad6c9cf31495f39f54515365a1d8e48393d29b1c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1  regular + model TT
