### ISSUE TITLE
Suite uses outdated Zcash logo

### ISSUE THREAD

**Issue by yohaaan** [trezor/trezor-suite#4901]
**Zcash logo is outdated**
New logo available here https://z.cash/press/

**Comment by prusnak** [comment]
There is one logo in the coin selection:

![](https://user-images.githubusercontent.com/42201/152782200-dd08bc2e-46b6-4941-a872-a86c7c8db5ca.png)

and another is in the homescreen selection.

**Comment by dahaca** [comment]
The linked official logo does not fit the style of all other logos we have and because of the black border does not look too good on darker backgrounds.

![image](https://user-images.githubusercontent.com/45338719/153041086-07f21cdd-5da3-42a3-bb5e-8efd3eec1565.png)

![image](https://user-images.githubusercontent.com/45338719/153041740-3f48c2ac-577f-4510-9d8c-4ea2bcd0e287.png)
