### ISSUE TITLE
Consider using Turborepo/Nx

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-suite#4936]
I stumbled upon Turborepo - https://turborepo.org - and it seems we might gain some benefits by using it, especially in the area of incremental builds and maybe later with remote caching. OTOH, it might be still overkill for the monorepo of our size. Please have a look and decide whether it makes sense for us to use that : https://turborepo.org/docs

Edit: There is also Nx - https://nx.dev - with slightly different focus.

**Comment by Nodonisko** [comment]
@prusnak Already on my radar, but we are not here yet. I believe that turborepo uses "per package cache" and we need to break `suite` package into smaller ones first, because most of code of suite is here and nearly every changes happens here, so it will be rebuild everytime anyway.

At least we will have "incremental" builds for TS soon (#4851) also cache for `eslint` is now working.

**Comment by prusnak** [comment]
@Nodonisko Great, thanks for the info. I agree with your observation - if we gain incremental builds via #4851 we are fine without Turborepo for now.

**Comment by Nodonisko** [comment]
To be accurate, it is inceremental type-check rather than build. It will improve mostly DX during development builds, impact on production builds will be very low.

Also one tool that we should consider is https://nx.dev

**Comment by Nodonisko** [comment]
https://dev.to/tolgee_i18n/is-turborepo-overhyped-416n
