### ISSUE TITLE
Warn about non-ASCII characters in passphrase

### ISSUE THREAD

**Issue by sime** [trezor/trezor-suite#4941]
## User story

**[Instructions + Design](https://github.com/trezor/trezor-suite/issues/4941#issuecomment-2338726186)**

As a Trezor Suite user
I want to protect my privacy
So that my funds are safe when my seed is compromised

As a Trezor Suite user
I want to create a hidden wallet passphrase on suite
And I want to confirm it on my device
So that I can trust I have create a hidden wallet securely

As a Trezor Suite user
I want to access my hidden wallet
And I want to enter my passphrase on a device I trust (Model T)
So that I can access my funds

## Acceptance criteria
Given I am on 'Select wallet type'
When I type '€'
Then I should see a 'Unable to create a wallet with this passphrase'
And the 'Access Hidden wallet' button should be disabled
And the 'Enter passphrase on Trezor' link should be disabled

**Caveat**: Backwards compatibility issue, potentially blocking users with UTF-8 characters in passphrases.

### Passphrase 'Š'
![IMG_20220214_155118](https://user-images.githubusercontent.com/216917/153898595-48d8a950-bf5d-4253-a14c-f08ef01563fc.jpg)

### Passphrase '€'
![IMG_20220214_160314](https://user-images.githubusercontent.com/216917/153898669-c19af75c-3c7a-4a21-a51a-744400daef19.jpg)

**Comment by prusnak** [comment]
> **Caveat**: Backwards compatibility issue, potentially blocking users with UTF-8 characters in passphrases.

There should probably be some way how to override this and get back to the old behaviour?

**Comment by sime** [comment]
> > **Caveat**: Backwards compatibility issue, potentially blocking users with UTF-8 characters in passphrases.
> 
> There should probably be some way how to override this and get back to the old behaviour?

My current thinking is to inform (warn) the user when they enter a passhrase with non-sanctioned characters, on-device entry is then impossible.

This way there is no 'go back feature', and suite remains backwards compatible.

**Comment by Hannsek** [comment]
I would put there only warning that you won't be able to type the passphrase directly on device. That's it.

**Comment by Hannsek** [comment]
Let's put there this: 

ℹ️  Special characters cannot be entered on the device.

"Learn more" button with the link: [tps://trezor.io/learn/a/trezor-suite-settings#ASCII-chars](https://trezor.io/learn/a/trezor-suite-settings#ASCII-chars)

**Comment by Hannsek** [comment]
@Hermez-cz consider bumping a prio or put it into some of the upcoming releases.

**Comment by AdamSchinzel** [comment]
A bit related to #9044

**Comment by andrewkozlik** [comment]
FTR, although the BIP 39 [spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#from-mnemonic-to-seed) allows any unicode characters in the passphrase, the SLIP 39 [spec](https://github.com/satoshilabs/slips/blob/master/slip-0039.md#passphrase) (Shamir backup) allows only printable ASCII, which is the character set that can be entered on Trezor. Unfortunately the firmware does not enforce this restriction for SLIP 39, which means that some users may have created passphrases that are incompatible with the spec.

**Comment by andrewkozlik** [comment]
After realizing the discrepancy between the SLIP-39 spec and Suite behavior, I think that we should prioritize this issue.
1. If a user with a SLIP-39 backup enters a character into the passphrase field that is not printable ASCII, then Suite should warn them: "_Non-standard passphrase. Passphrases should only contain ASCII characters. Using this passphrase may lead to compatibility issues in the future._" The user should be allowed to continue though, so that those who are already using a non-standard passphrase can still access their wallet.
2. If a user with a SLIP-39 backup enters a non-standard passphrase and Suite discovers that all wallets for the passphrase are empty and have no history, then instead of offering the user to open the wallet and continue to the "_Confirm passphrase_" dialog, Suite should force them to use a printable ASCII passphrase. For example: "_This wallet is empty and hasn't been used before. To create a new wallet please use a passphrase with ASCII characters only._"

FTR, these are printable ASCII: `A` - `Z`, `a` - `z`, `0` - `9`, space, `!`, `"`, `#`, `$`, `%`, `&`, `\`, `'`, `(`, `)`, `*`, `+`, `,`, `-`, `.`, `/`, `:`, `;`, `<`, `=`, `>`, `?`, `@`, `[`, `\`, `]`, `^`, `_`, `` ` ``, `{`, `|`, `}`, `~`.

**Comment by Hermez-cz** [comment]
> After realizing the discrepancy between the SLIP-39 spec and Suite behavior, I think that we should prioritize this issue.
> 
> 1. If a user with a SLIP-39 backup enters a character into the passphrase field that is not printable ASCII, then Suite should warn them: "_Non-standard passphrase. Passphrases should only contain ASCII characters. Using this passphrase may lead to compatibility issues in the future._" The user should be allowed to continue though, so that those who are already using a non-standard passphrase can still access their wallet.
> 2. If a user with a SLIP-39 backup enters a non-standard passphrase and Suite discovers that all wallets for the passphrase are empty and have no history, then instead of offering the user to open the wallet and continue to the "_Confirm passphrase_" dialog, Suite should force them to use a printable ASCII passphrase. For example: "_This wallet is empty and hasn't been used before. To create a new wallet please use a passphrase with ASCII characters only._"
> 
> FTR, these are printable ASCII: `A` - `Z`, `a` - `z`, `0` - `9`, space, `!`, `"`, `#`, `$`, `%`, `&`, `\`, `'`, `(`, `)`, `*`, `+`, `,`, `-`, `.`, `/`, `:`, `;`, `<`, `=`, `>`, `?`, `@`, `[`, `\`, `]`, `^`, `_`, `` ` ``, `{`, `|`, `}`, `~`.

Hi, the part of "Suite discovers that all wallets for the passphrase are empty and have no history" might become tricky if the user might have some funds on a coin that is currently not enabled. Otherwise all sounds like the right solution, thanks.

**Comment by Hannsek** [comment]
Therefore this should be done together with the idea of silent discovery of all coins. But we must think it through from the privacy pov.

**Comment by Hermez-cz** [comment]
### Design and short spec

Since only the Printable ASCII character set is fully compatible with SLIP-39 backups, we’ve prepared two slightly different designs: a less strict one for BIP-39 and a more strict one for SLIP-39. Therefore, we’ll need to display the appropriate version based on the user’s current backup type.

**Common for both versions**
If the user uses only Printable ASCII characters, don't bother the user with any extra instructions. Keep the current interface design please.

<img width="559" alt="Screenshot 2024-10-24 at 12 45 31" src="https://github.com/user-attachments/assets/721e8993-61b9-43b5-b677-3c21c2852b52">

______


**BIP-39 combination**
If the user writes any non-Printable ASCII character:

- show a blue recommending element as per design
    - Copywriting TBD
- change the CTA copy to "Confirm (with non-recommended "[unsupporrted character]")"
    - Or "Confirm (with non-recommended characters)" if there's more than one

<img width="438" alt="Screenshot 2024-10-24 at 12 51 58" src="https://github.com/user-attachments/assets/7f646ce7-4625-4bf3-9ff0-bdd143b46835">

If the user deletes the non-recommended character(s):

- keep the recommending element, so it doesn't hop in and out, and keeps providing instructions what characters can the user use.
- Turn the "Confirm" CTA back to normal as per design 


<img width="448" alt="Screenshot 2024-10-24 at 12 52 11" src="https://github.com/user-attachments/assets/ff2d170b-ac57-468e-97ed-458e1704c895">

In case of an error message shown together with the recommending element, it should look like this. The button should be inactive and carry the same copywriting as when active according to the situation.


<img width="447" alt="Screenshot 2024-10-24 at 12 52 28" src="https://github.com/user-attachments/assets/a658f3ee-6c60-410c-a6be-a699ddfc83c2">

_____

**SLIP-39 combination**
It's basically the same as for BIP-39, only the informational element and the non-recomended CTA are in a yellow warning state:

- Non-recommended character(s) present 

<img width="439" alt="Screenshot 2024-10-24 at 12 53 26" src="https://github.com/user-attachments/assets/3d54c78c-832f-4ab4-9680-d7ed3e0888fd">

- Non-recommended character(s) deleted 

<img width="447" alt="Screenshot 2024-10-24 at 12 53 54" src="https://github.com/user-attachments/assets/bb8b0bb0-4856-46c2-b98e-eb96e43c0447">

- Error state combination

<img width="443" alt="Screenshot 2024-10-24 at 12 54 14" src="https://github.com/user-attachments/assets/1e270d6f-176c-4a55-964a-8f975ff6069f">

Note: Users won’t be blocked in any of the non-error states described above, as they may already have such a passphrase. We will enhance this in a future Passphrase UX, where we’ll consider the user’s mental model—whether they expect funds in the passphrase or if it’s new for them. Another improvement opportunity will come with the potential for automatic coin discovery and activation for wallets where funds are expected. (another issue related to it: https://github.com/trezor/trezor-suite/issues/14229)

**Comment by tomasklim** [comment]
How to:

https://github.com/user-attachments/assets/a63ca237-c730-4004-8574-db34ee2f50ba

**Comment by bosomt** [comment]
**QA OK**

![Image](https://github.com/user-attachments/assets/7b773815-6788-4162-a55a-0f7b58b73fe6)

**Info:**
 - Suite version: desktop 24.11.1 (9e9dadff47c5243bf4a10f539a898fe48da46506)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.11.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.5 regular (revision d72aab0bf75a9cfe6679da87efc4ac33382468dc)
 - Transport: BridgeTransport 2.0.33
