### ISSUE TITLE
Tor and custom backend potential troubleshooting

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#4963]
When a user enter an onion address, but Tor is turned off:

<img width="744" alt="Snímek obrazovky 2022-02-21 v 13 53 40" src="https://user-images.githubusercontent.com/26002916/155154772-96d6790a-5d9e-4f8a-8bef-1555d66611b5.png">

When a user wants to disable Tor but only uses onion addresses for their custom backend:

<img width="747" alt="Snímek obrazovky 2022-02-21 v 13 52 17" src="https://user-images.githubusercontent.com/26002916/155155167-b2b7d185-0739-4d2b-9630-d826ced87d0a.png">

**Comment by tomasklim** [comment]
Do not forget:
I proposed some improvements in the PR which we can discuss.

QA:
@trezor/qa I proposed to test our app in the browser with Tor to check that we do not have any inconsistencies there. If you launch Suite in Brave with Tor, Suite detects that tor is used. However, I am aware that it has to be tested on production as we do not have stg onion link, or do we?

Btw we should check with @kolomaznikt that there is anyone who uses Suite with tor browser. Otherwise, we can kill it?
`suite-ready` event, `tor` attribute in `web/stable.log`

EDIT: maybe user has analytics disabled, so we do not have this info.
