### ISSUE TITLE
Redact new cardano-related actions

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#4978]
We have to redact all possibly sensitive data for logging.

current utils here:
https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/utils/suite/logUtils.ts

Consider at least stacking info https://github.com/trezor/trezor-suite/blob/c9f41ce5b05750b77ee862c1917e4c337750135e/packages/suite/src/reducers/wallet/accountsReducer.ts#L26-L31

and pending stacking TXs https://github.com/trezor/trezor-suite/blob/c9f41ce5b05750b77ee862c1917e4c337750135e/packages/suite/src/reducers/wallet/cardanoStakingReducer.ts#L7

**Comment by slowbackspace** [comment]
👍  `staking.address`, `staking.rewards` should definitely be redacted.
What about `account.misc.staking.poolId` (staking pool to which the user is delegating to)? should it be also considered as sensitive information?

Regarding `pendingTx` from staking reducer, I think it is not logged anywhere since logging has to be enabled explicitly for any new redux action or did I miss something?

**Comment by slowbackspace** [comment]
For now I redacted `staking.address` and `staking.rewards`. https://github.com/trezor/trezor-suite/pull/4144/commits/54881d47aef9520e9631fa5bf020e03f7eb4bd5d

**Comment by matejkriz** [comment]
Thanks for the `address` and `rewards` 👍  I'm not sure about the `poolId` but would rather redact it too. 

You are right about the `pendingTx`, only the action type is logged by default.

**Comment by slowbackspace** [comment]
done ef36b0fa61363257b2af4b9cbfed05c580e03380
