### ISSUE TITLE
Storage error

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#506]
![image](https://user-images.githubusercontent.com/3112191/64686404-eb4f6300-d488-11e9-853c-b265e772cfbd.png)

**Comment by slowbackspace** [comment]
yup, it happens when someone changes storage structure without bumping the version (and writing migration script), which we are not doing for now. So you had old version of the storage and app with updated storage structure tried to do some operation which wasn't supported before. When you delete the DB error goes away.

I guess even during development we could bump the version with each change to the structure, just instead of writing proper migration script we'll just delete whole db. Anyway we are good for now, so I am closing the issue.
