### ISSUE TITLE
Link our data analytics document directly from Suite

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-suite#5129]
In https://github.com/trezor/trezor-suite/pull/4516 we have improved our data docs. We would like to link [this page](https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/index.md) from this screen directly:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1835345/158581075-cfa424a1-6aa0-4b20-b74a-50041eca17d2.png">

I would simpy change the sentence "Read more in [Terms & Conditions](https://data.trezor.io/legal/wallet-terms.pdf)" to "Read more in our [technical documentation](https://github.com/trezor/trezor-suite/blob/develop/docs/analytics/index.md) and [Terms & Conditions](https://data.trezor.io/legal/wallet-terms.pdf)" or similar.

@b-irving could you come up with the sentence please? Or is my suggestion good enough?

**Comment by b-irving** [comment]
@tsusanka your suggestion is fine

**Comment by matejkriz** [comment]
If we put the url in the app, we'll have to keep it available for backward compatibility. Not a big deal, just something to consider. I believe it's fine as far as it is link to analytics "index" docs. 

I would put there the link to the deployed version instead of link to github 
https://docs.trezor.io/trezor-suite/analytics/index.html

but then we should fix the links at the bottom of the page, because they should lead to README files, but those are not in docs/ folder, so the relative links are not working.

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 22.6.0 (d72ff4c5b9f3cbe2ccb4be47170f88c08e9271d1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.0 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.11.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
