### ISSUE TITLE
LTC address scan from QR not working

### ISSUE THREAD

**Issue by davidbodnar** [trezor/trezor-suite#5241]
**Describe the bug**
LTC address scan is not working when sending to mobile Coinomi wallet.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app version 22.3.2.16437
-   OS: MacOS, 12.3.1 (21E258)

**How to reproduce**

1. Go to Wallet
2. Select Litecoin token
3. Click on Send
4. Scan address from QR code
6. Receiver address won't show in the input box

**Expected behavior**
Address should be present in the input.

**Comment by forgiSL** [comment]
Also reported on XRP,Doge and Dash,ETH, same version of Suite, WIndows 10

**Comment by STew790** [comment]
Hello, this is due to the prefix that Coinomi puts into their QR codes (litecoin:, doge:, dash:,etc.) which Suite is not recognizing, except of Bitcoin (Bitcoin is using an officially recognized scheme https://en.wikipedia.org/wiki/List_of_URI_schemes).

Nonetheless, this is more of a feature request than a bug. Thank you for the report.

**Comment by petrkr** [comment]
URI scheme was introduced 10 year ago in BIP-21 so it should be supported in order to be compatible with this BIP (https://en.bitcoin.it/wiki/BIP_0021)

**Comment by hynek-jina** [comment]
@petrkr 
BIP-21 specify only Bitcoin.. And it is already implemented in Trezor Suite.
This could be for some coins resolved by https://github.com/trezor/trezor-suite/issues/5266

**Comment by petrkr** [comment]
Other currencies mostly does not copy&paste BIPs for they own, it would make just duplicates, instead they implement them too. 

So by this logic for example Litecoin does not have own LIP for BIP32 for example, so we do not need to implement deterministic wallet for them, because they do not have LIP32.

Maybe someone in cryptocummunity had to replace BIP as "Bitcoin" to some CIP (sorry guys from Ostrava :) ) as Cryptocurrency or something, what could be generic for all coins to avoid those missunderstandings (like it is only for bitcoin).
