### ISSUE TITLE
"Accounts" layout is used on "Notifications" page on small screen

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#5253]
**Describe the bug**
If I go to notifications from "Accounts" page, notications are opened in "Accounts" layout.

**Info:**

-   Suite Version: 22.3.2, 22.4.1

**How to reproduce**

1. Small screen
2. Accounts
3. Menu
4. Notifications

**Expected behavior**
![Screenshot 2022-04-11 at 12 27 03](https://user-images.githubusercontent.com/33235762/162721637-585539f8-98c2-4bcf-872c-4d09369a7d9c.png)

**Screenshots**
![Screenshot 2022-04-11 at 12 27 28](https://user-images.githubusercontent.com/33235762/162721754-0c07d919-0c7a-48c7-a0a7-85e66723d709.png)

**Comment by STew790** [comment]
**QA NOK**
This is still present in the latest version. Although, I am not sure if it is even a bug, since the notifications are "hidden" in the hamburger button. Also, this only applies when I switch to "mobile" view. In my opinion, this should be on product, since we have also a mobile app coming.

cc @hynek-jina 

**Info:**
 - Suite version: web 22.7.3 (8eddb2accd31c78577f276df2e9ecf773d2c3c17)
 - Browser: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Mobile Safari/537.36
 - OS: Linux x86_64
 - Screen: 370x667
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by MiroslavProchazka** [comment]
@STew790 can you check this please?

**Comment by STew790** [comment]
**QA OK**
The notifications were moved and this is no longer an issue.

**Info:**
 - Suite version: desktop 24.5.1 (f64356923761ba0d81299f5e165177a742b6fb78)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.5.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: Trezor T2T1 2.7.0 regular (revision 45e8a842a31e62a6d43d7f6ccac62a45e1198ef0)
 - Transport: BridgeTransport 2.0.33
