### ISSUE TITLE
SlideDownModal component

### ISSUE THREAD

**Issue by Nodonisko** [trezor/trezor-suite#5421]
**Design:** [Figma](https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/s2-Mobile?node-id=68%3A7562)
![Screenshot 2022-05-17 at 20 57 11](https://user-images.githubusercontent.com/5837757/168891475-51839d55-54cb-4689-a855-8c8431e79423.png)
![Screenshot 2022-05-17 at 20 48 01](https://user-images.githubusercontent.com/5837757/168891483-ecd45570-a412-4034-b66b-783bcad8d401.png)

**Spec:** 
1. Props
```tsx
type SlideDownModal = {
	children: React.ReactNode,
	onClose?: () => void,
	title: React.ReactNode,
	isTitleCentered?: boolean
	isVisible: boolean
}
```
2. Left arrow icon doesn't makes too much sense here, ask Ondra before you implement it
3. Content of modal is not part of component, it will be passed as `children`
4. This overlay should be made using RN [Modal component](https://reactnative.dev/docs/modal)

**Comment by juriczech** [comment]
@Nodonisko I think the left icon makes sense because its a form of breadcrumbs if I understand the design correctly.

For example you can click on some settings button which will open modal and inside that modal one of the items will be Language options, you click on that and it will take you to "next section" of settings where you can select language or go back (with the left arrow icon).

**Comment by juriczech** [comment]
@Nodonisko I think the left icon makes sense because its a form of breadcrumbs if I understand the design correctly.

For example you can click on some settings button which will open modal and inside that modal one of the items will be Language options, you click on that and it will take you to "next section" of settings where you can select language or go back (with the left arrow icon).
