### ISSUE TITLE
Firefox: no "blurred background" while modal is opened

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5492]
**Describe the bug**
see screenshots in [this issue](https://github.com/trezor/trezor-suite/issues/5470)

**Info:**
-   Suite Version: web
-   Browser: Firefox
-   OS: linux but i guess it doesnt matter

**Comment by bosomt** [comment]
@szymonlesisz You are using Firefox see : https://github.com/trezor/trezor-suite/issues/2165
`Solution is way too complicated compared to benefit of solving it.`

**Comment by szymonlesisz** [comment]
i dont understand why are you closing this and why is it so hard to do it?

10 minutes on googling, 1 line of css code in SuiteLayout `filter: blur(3px);`

and voila:


![Screenshot from 2022-05-26 11-18-29](https://user-images.githubusercontent.com/3435913/170458742-abfa7866-9a10-4aa0-9c0e-1a496c003b7c.png)
![Screenshot from 2022-05-26 11-18-11](https://user-images.githubusercontent.com/3435913/170458747-00129e80-66e0-444d-9ec0-bab313203d57.png)

**Comment by szymonlesisz** [comment]
btw this is exactly the reason why i didnt noticed a "request to confirm on device" in [this issue](https://github.com/trezor/trezor-suite/issues/5473) because this element was above the menu which has the same (or very similar) bg color

**Comment by tomasklim** [comment]
Can be done when `EAP` and `Skip onboarding` modals start using redux.

However, instead of one line `backdrop-filter: blur(5px);` we need to add conditional `filter: blur(5px);` to `SuiteLayout` and `OnboardingLayout` when `usePreferredModal().type !== 'none'`.

IMHO not sure if we need to fix it this way. We do not have many `Firefox` users. I believe, it would be enough to change opacity in `Backdrop` component from `background: rgba(0, 0, 0, 0.3);` to `background: rgba(0, 0, 0, 0.6);` for `Firefox` browser.

**Comment by szymonlesisz** [comment]
in browser detection we are claiming that from the all browsers out there only two [are supported](https://github.com/trezor/trezor-suite/blob/develop/packages/suite-data/src/browser-detection/index.ts): Chrome and Firefox.
from what you are saying i can assume that only Chrome is supported and our claim is false

i guess changing opacity for Firefox is still better than nothing

**Comment by szymonlesisz** [comment]
closing via https://github.com/trezor/trezor-suite/pull/5600
