### ISSUE TITLE
Transactions do not show in account, but balance is correct/Custom Backend

### ISSUE THREAD

**Issue by Alex71btc** [trezor/trezor-suite#5512]
Latest Transaction BTC is missing when connected to electrum server backend. When opening Suite web version or Trezor backend it shows correctly. Also total amount of BTC in that account is shown correctly. When i search for the transaction ID in Suite it shows up, but disappears again and doesnot show in my account. Whats up with this?

**Comment by hynek-jina** [comment]
@Funman2 Is your node updated and synced?

**Comment by Alex71btc** [comment]
Thanks for your reply, yes updated and fully synced...



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Hynek Jína ***@***.***>
Datum: 06.06.22 13:42 (GMT+01:00)
An: trezor/trezor-suite ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [trezor/trezor-suite] Transactions do not show in account, but balance is correct/Custom Backend (Issue #5512)


@Funman2<https://github.com/Funman2> Is your node updated and synced?

**Comment by wendys-cats** [comment]
QA could not reproduced this issue, even after multiple tests (on several Suite version). 

I am sorry we were not able to solve the issue for you, but hopefully information below will be of some help!
Based on the problem described and the fact QA has not encountered this problem before, and even after extensive tests, I was unable to reproduce this, I believe one of these scenarios is most likely what is going on:
1. Suite is correctly connected and synced with your electrum backend. The newest transactions are not showing in full transaction history because of cache problem. 
In this scenario, Suite should allow you to send a transaction (you can try it, just do not sign with device). 
Should be solved once you clear all your cache (Settings>Application).

2. Suite is NOT correctly connected and synced with ytour electrum backend. The newest transactions not showing in full transaction history is reflecting the state your connection is in. They show up on search because of cache (sometimes when you go through discovery with standard backends and everything loads and then you change backend, it might look like it is synced, but what you are seeing is information loaded with backends you are not connected to anymore).
In this scenario, Suite will not allow you to sign a transaction.
If you go to wallet modal (click on device icon in top-left corner) and press Eject wallet, everything will dissapear and discovery starts anew. OR you can not connect your device when you open Suite, go to Settings, change connection to your custom electrum server and after that connect device, so you avoid discovery with standard backends. Or try another electrum server.

**Comment by Alex71btc** [comment]
Closed, but i could reproduce three same issue on different computers connecting to same electrum backend,  always some(the same) transactions are not showing when connected to jut umbrel node, other wallets like sparrow show  correct also using electrum. 
When I search for the missing transaction ID in the transaction  search tab they are displayed but as soon as I empty the search field the vanish again from history
But suite definitely has  a bug there!

**Comment by Alex71btc** [comment]
I am not the only person with this issue, see here:
https://forum.trezor.io/t/transaction-history-missing-no-loss-of-funds/7465

**Comment by hynek-jina** [comment]
@Funman2
Please have a look on @wendys-cats comment first.

**Comment by ondracja** [comment]
@Funman2 hi, since you can reproduce the issue, can you please provide steps for the reproduction? Also some additional info would help us narrow down the problem.

**Comment by Alex71btc** [comment]
@wendys-cats I have tried to send, was possible! Deleted all trezor folders and made my suite forget all user datas, still the same bug, recent transactions not listed in acount history, but in the graphic overviev it shows! Also i can search for ech missing transaction, it will show up, but vanish again once i clear the search field.
Only connected to my umbrel electrum server this time, not conncetion to trezor backends at all.
if i connected to trezor servers, all transactions where vivible though. This is reproducable with all windows machines running trezor suite, connecting to my electrum server, wich is fully sycned and works fine with all other wallets.(Nunchuck, Blue wallet, Sparrow)

**Comment by Alex71btc** [comment]
Dear Marek,
Thank you very much, i downloaded the prerelease software of Suite, all transactions are listed correctly now! Issue solved indeed.
Congrats to great developer team!
Love Trezor Wallets!

Von: Marek Polák ***@***.***
Gesendet: Montag, 27. Juni 2022 18:02
An: trezor/trezor-suite
Cc: Funman2; Mention
Betreff: Re: [trezor/trezor-suite] Transactions do not show in account, but balance is correct/Custom Backend (Issue #5512)


Closed #5512<https://github.com/trezor/trezor-suite/issues/5512> as completed via #5684<https://github.com/trezor/trezor-suite/pull/5684>.

**Comment by Alex71btc** [comment]
Wait, now only transcations of June are displayed, but other Month/Years missing now! Lol

**Comment by marekrjpolak** [comment]
For the sake of clarity, current fix hasn't been released yet as commented in https://github.com/trezor/trezor-suite/pull/5684#issuecomment-1167881481

**Comment by Alex71btc** [comment]
Thank you very much for your kind answers and the great work you are doing for empowering my self sovereign custody! More important than ever!
Trezor rocks.



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Marek Polák ***@***.***>
Datum: 27.06.22 22:57 (GMT+01:00)
An: trezor/trezor-suite ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [trezor/trezor-suite] Transactions do not show in account, but balance is correct/Custom Backend (Issue #5512)


For the sake of clarity, current fix hasn't been released yet as commented in #5684 (comment)<https://github.com/trezor/trezor-suite/pull/5684#issuecomment-1167881481>

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 22.6.2 (926eb295b846e82a4352f508d6e1275efe76fbf7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31

**Comment by Alex71btc** [comment]
Just want to say thank you again, latest update solved all my issues with custom backend electrum server! Balances and transactions show correctly now! Great step for using Trezor Suite again!
