### ISSUE TITLE
Potential issues with TrezorConnect while switching between passphrases

### ISSUE THREAD

**Issue by marcin-mazurek** [trezor/trezor-suite#5598]
Hello! Would you guys advise please if this is a potential bug or misunderstanding on our side?

**Context**
Daedalus supports multiple wallets which can be paired with a single device using different passphrases.

We noticed that once a passphrase is typed on the device while exporting a public key, that passphrase is then used for all subsequent transaction signing operations.

We needed to give users the ability to sign transactions for different wallets, we tried multiple approaches and none of them worked as we would expect.

Imagine the following call sequence:

1. Exporting xpub for wallet A
2. Signing transaction for wallet A
3. Signing transaction for wallet B

In the third step, Trezor device keeps using passphrase provided for wallet A, and what we wanted is another prompt to provide a passphrase, that would allow us to switch to a different wallet.

What we tried:

**Approach 1**
We tried setting the save parameter to false on the REQUEST_PASSPHRASE event handler, but that didn’t make any difference.

![Screenshot 2022-06-08 at 13 59 06](https://user-images.githubusercontent.com/6684554/172999604-40ea2aa0-bb2d-48d6-bd2b-24f7c50f9413.png)

**Approach 2**
According to the documentation there is an instance parameter under device parameter which can be passed while making TrezorConnect calls. This parameter is meant to be provided under the TrezorConnectEvent payload, however we couldn’t find any property called instance or similar. Perhaps the documentation should be improved in this area, or some usage examples should be provided.

**Approach 3**
We tried setting keepSession to true on first TrezorConnect call, and then calling TrezorConnect.getFeatures()with keepSession set to false, but that didn’t make any difference.

![Screenshot 2022-06-08 at 13 59 43](https://user-images.githubusercontent.com/6684554/172999625-912e212b-0989-4d37-87ca-10c1d3511ace.png)

**Our workaround - disposing and re-initing TrezorConnect**
We ended up calling TrezorConnect.dispose() and TrezorConnect.init() again before any operation which requires switching to a different wallet, however we’re unsure if this is the best way to do this, but it seems to do the trick. Unfortunately this requires to re-register all event listeners.

https://github.com/input-output-hk/daedalus/blob/develop/source/main/trezor/connection.ts#L21
https://github.com/input-output-hk/daedalus/blob/develop/source/main/ipc/getHardwareWalletChannel.ts#L765

**Comment by szymonlesisz** [comment]
Hi @marcin-mazurek 🇵🇱 :),

It's not exactly a bug but rather not well documented feature since no one except for TrezorSuite was using it till now.
What you are looking for is `device.state` parameter [described here](https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connect/methods/commonParams.md)

device.state could be obtained by calling `TrezorConnect.getDeviceState` (you can [see here](https://github.com/trezor/trezor-suite/blob/develop/packages/suite/src/actions/suite/suiteActions.ts#L504-L512=) how suite is doing this)

once you have it you can use it for addressing this passphrase in the future.
example:
```javascript
const response1 = await TrezorConnect.getDeviceState({
    device: {
        instance: 0, // identificator for wallet A
        state: undefined, // by using undefined you are making sure that passphrase will be requested
    },
});

// use first passphrase (now you should not be asked for it anymore)
TrezorConnect.getPublicKey({
    device: {
        instance: 0, // identificator for wallet A
        state: response1.payload.state,
    },
    ...
});

// force change the passphrase (you will be asked for passphrase)
const response2 = await TrezorConnect.getDeviceState({
    device: {
        instance: 1, // identificator for wallet B
        state: undefined, // by using undefined you are making sure that passphrase will be requested
    },
});

// use second passphrase/instance (you should not be asked anymore)
TrezorConnect.getPublicKey({
    device: {
        instance: 1, // identificator for wallet B
        state: response2.payload.state,
    },
    ...
});

// use first passphrase again (you should not be asked anymore)
TrezorConnect.getPublicKey({
    device: {
        instance: 0, // identificator for wallet A
        state: response1.payload.state,
    },
    ...
});
```

This way you can create as many passhpase/states/intances as you want and you may be sure that the user is using correct passphrase for wallet A and wallet B.
`device.state` is validated in connect and it will throw an error if requested state doesn't match the passphrase provided by user later on.
For example if you store device.state for wallet A (let say using passphrase "A" => state "abcd") in you app, then you disconnect the device (or restart app) and then you use remembered device.state in the future call regarding wallet A but you put passphrase "B" instead of "A" you should receive an error.

i hope my explanation is understandable :)

edit: i've udpated the code to get rid of confusion regarding the path and DEVICE event

**Comment by szymonlesisz** [comment]
in other words:

`device.instance` - number, identifiaction of your wallet A or wallet B
`device.state` - string, passphrase representation of your wallet A or wallet B

**Comment by sime** [comment]
@marcin-mazurek Created a doc for the getDeviceState method, which was mentioned here. Shout out if you think it is missing something.

**Comment by szymonlesisz** [comment]
also missing passphrase testing vectors [were added here](https://github.com/trezor/trezor-suite/blob/develop/packages/integration-tests/projects/connect/tests/device/passphrase.test.ts)

**Comment by sime** [comment]
And one month later I actually link to the mentioned doc (sorry): https://github.com/trezor/trezor-suite/blob/develop/docs/packages/connect/methods/getDeviceState.md

**Comment by marcin-mazurek** [comment]
It's perfect, thanks guys!
