### ISSUE TITLE
Tor toggle is slow and doesn't reflect connection state

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#5612]
**Describe the bug**
It takes about 10 seconds to switch on the Tor.
If you click twice, the toggle switches right away, but it doesn't mean Tor is immediately connected.

**Steps to reproduce:**
1. Go to Setting/Device
2. Turn on Tor
3. Wait

**Info:**
 - Suite version: desktop 22.6.2 (f45c75705f153ec0dc44cb72fec2e5ec4a031b7c)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.2 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: 
 - Transport: bridge 2.0.27

**Expected result:**
- After turning Tor on from anywhere the `Loading` state is initiated
- Toggle in settings is green on `ON` or `Loading`
- When `Loading` the indicator on the Tor icon in the header becomes a blinking orange dot to signify the loading state
- When `Loading`,  in settings show "Enabling Tor" and a spinner to the left of the toggle on desktop and a spinner next to the header on mobile.
- When `Loading`, in onboarding show a loader in the button until loaded, then proceed.
- When `Loading`, in custom backends don't enable onion backends until Tor is finished loading and enabled.
- When loading fails - revert the Tor state to OFF and show a notification 
- In onboarding and custom backends that means that the processes do not continue and simply stay the same as before attempting to enable Tor 

**Actual result:**

https://user-images.githubusercontent.com/26002916/173539627-9e17611f-36c2-44a0-818b-db49ee7a3793.mov

**Comment by szymonlesisz** [comment]
Reflecting tor current status in suite **was designed** on the diagram while discussing the design of `request-manager` lib.
I cant find it in github (closed PR/edited PR comment?) fortunately we do have it on [slack](https://satoshilabs.slack.com/archives/C0363D1FDL2/p1646855487778909) and [notion](https://www.notion.so/satoshilabs/d3c3fe72632c42fe93128a4857484b5e?v=b97cf771318d4b1fa19501a3b6df2e0b&p=73b86a20ebe843379f743f20fa7772b3) archives (see `status: loading/error/ok` in `Enable TOR --> Enabled` processes) cc: @matejkriz, @karliatto, @marekrjpolak, @dahaca 

Desired app flow after desktopApi.handshake is done  #5627

We can split the task in to two phases:

#### Before store preloading  #5534
1. desktopApi.handshake is starting the tor process using `loadModules` fuction. https://github.com/trezor/trezor-suite/issues/5627
2. desktopApi.handshake returns current tor settings to suite and it's stored in reducer
3. `TrezorConnect.init` is called with `proxy` field from the handshake data (`TrezorConnect.setProxy` on the electron-main layer can be removed then)
4. `TrezorConnect.setProxy` is called **only** on the renderer side in reaction to `tor/status` event from the desktopApi

#### After store preloading  #5534

1. desktopApi.handshake receives data from preloaded indexedDB (tor settings)
2. tor process is starting using data from the handshake (there is no need to keep tor settings in electrum-storage anymore, source of truth will be only in indexedDB)

**Comment by matejkriz** [comment]
Notes for QA:
- behaviour in Tor Browser can also be affected by this

**Comment by tomasklim** [comment]
**Follow-up:**

- New user is offline and wants to start tor in onboarding. However, the user is now blocked for 1 minute because the continue button is disabled until tor is successfully enabled.
- You cannot enable tor if you are offline. (Both in onboarding and settings)

**QA:**
Please test on STAGING.

Prerequisites:
- network tab to check that requests go through `tor`/`clearnet` according to Tor status in the app

Check:
- Tor switch should be disabled when tor is enabling/disabling (to prevent double clicks)
- The switch value should be changed immediately and loader next to Tor label should be visible
- Green checkmark should be visible on the tor icon in the navigation bar when tor is running and a white loader if tor is loading.
- User should get an error notification when tor enabling/disabling fails (e.g. offline in case of enabling)

How to manipulate with tor:
- Enable/disable tor in onboarding
  - Check that it is really enabled
  - Loader should be visible next to "Enable Tor" label, loader should be visible in "Continue button" and button should be disabled
- "Tor" in settings
  - Loading next to "Tor" label
  - Disabled switch on state change
  - State should be reflected in the navigation bar
- If only custom onion backends are set and the user chooses to disable tor, it should display modal and allow to disable tor

Note: 
- distinguish 2 states
  - user enables tor in the current session
  - tor is enabled based on settings from previous sessions
