### ISSUE TITLE
Parse transactions with external inputs

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#5628]
Prerequisite for coinjoin:

- blockchain-link: properly parse/mark inputs/outputs of tx which isn't "mine" (external) do not calculate them in to "totalSpent" field

**Comment by andrewkozlik** [comment]
https://www.notion.so/satoshilabs/Parsing-tx-history-for-external-inputs-033868327c3a4ff4a0eb936b97027bdc

**Comment by andrewkozlik** [comment]
Here is a Testnet CoinJoin transaction as an example:
https://tbtc1.trezor.io/tx/22d859f9edab52e6d9af3ac1422ed137b4a01fcc45ed7845d4d4ade6505e89ce

The first two inputs belong to the "all all ... all" seed SegWit v0 account #1:
354294 sats tb1qkl9nxlt0e7e0mn8jd6drkxt0tqh3uqy5xmxryp (m/84'/1'/0'/1/135)
234706 sats tb1q52x4g9daqqvqaj8gljqxj6w67n584k2etfcf8h (m/84'/1'/0'/1/134)

Eight of the outputs belong to the "all all ... all" seed SegWit v0 account #1:
588098 sats = 2 * 200000 + 118098 + 2 * 20000 + 3 * 10000 sats.

So the user is spending 589000 - 588098 = 902 sats. This is the one key piece of information that the user should be seeing in Suite when this transaction is displayed.

**Comment by andrewkozlik** [comment]
Here is the transaction as seen in Suite:

![image](https://user-images.githubusercontent.com/42678794/186375530-d4d8a5b0-a042-47c7-a164-51b1279ff166.png)

In terms of the UI, if the transaction contains an external input, then:
- Instead of "Sent TEST", I'd put "Joint TEST transaction" or "TEST CoinJoin".
- I'd hide the fee and the outputs instead of showing the first three like we do above, so that the transaction takes up as little space as possible. I'd only show "-0.00000902 TEST" and the "Show more" button.
- When the "Show more" button is clicked I'd show the output details as we do now, but also include the change-outputs, replacing their addresses with "Sent to myself".

The transaction details look like this:

![image](https://user-images.githubusercontent.com/42678794/186377922-1fcf7a8c-bd53-45e5-852f-5a23c69fae55.png)

- The information looks correct, except for "Amount", which I think should be 00000902 TEST.
- When the user clicks "Inputs, Outputs" they see all inputs and outputs, including their change-outputs. It would be nice if the user's own inputs and outputs were visually distinguished from the other's inputs and outputs by having a different color, for example.

I leave the final design details to @hynek-jina.

**Comment by hynek-jina** [comment]
The following issue: https://github.com/trezor/trezor-suite/issues/6211

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 22.10.0 (3e7ebf4ff17e4347baacd84b3143b44b4d4d4907)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0
 - OS: MacIntel
 - Screen: 1848x1155
 - Device: model T 2.5.2 Universal (revision 0d87b55ba4fed7eecc72bf2a94ee473830b095e9)
 - Transport: bridge 2.0.32
