### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by TMDStudios** [trezor/trezor-suite#5771]
All links under https://docs.trezor.io/packages/ are broken

**To Reproduce**
1. Go to: https://docs.trezor.io/packages/ 
All links under 'analytics' and 'suite-analytics' are broken

**Comment by matejcik** [comment]
@prusnak please move to Suite repo

**Comment by prusnak** [comment]
> @prusnak please move to Suite repo

done

**Comment by komret** [comment]
**QA**: https://docs.trezor.io/packages/ has been removed. The package READMEs are instead linked from https://docs.trezor.io/trezor-suite/analytics/index.html. This means that links from docs to READMEs must be absolute (e.g. https://github.com/trezor/trezor-suite/blob/develop/packages/analytics/README.md) because they can take the user between different domains. On the other hand, links in READMEs should be relative because both READMEs and docs can be displayed on Github. In practice, all links on https://docs.trezor.io/trezor-suite/analytics/index.html and on the linked pages should be working.

**Comment by bosomt** [comment]
**QA OK**

Analytics section is OK
Rest will be fixed later /see Notion QA task/
