### ISSUE TITLE
CoinJoin Tor check in onboarding modal

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6212]
Continues after adding CoinJoin account: https://github.com/trezor/trezor-suite/issues/5873 
First two steps moved to follow-up issue: https://github.com/trezor/trezor-suite/issues/6475

<details open>
<summary>3. Enabling Tor</summary>
<br/>

- Tor is required for CoinJoin account.
- This modal appears only, if the Tor is not yet enabled

![onboarding - tor](https://user-images.githubusercontent.com/26002916/188889696-10d432a4-950f-4c9d-b9c7-a590182cade5.png)

</details>

**Comment by karliatto** [comment]
In order to be able to Enable Tor in the modal number 2 proposed in this issue I see 2 possible options:
1. Redirect user to Settings where Tor can be enable
2. Create new modal similar to "Tor Splashscreen" where the user will get the feedback about Tor starting with the possibilities to retry in case it stops.

After discussion with @hynek-jina the option 2 is the one that should be implemented.

**Comment by karliatto** [comment]
@hynek-jina I see there were some changes in the figma designs for the part of this issue. Are those final or are the ones in this issue still apply?

**Comment by hynek-jina** [comment]
@karliatto 
I've updated the issue.. But the changes are rather cosmetic. For now you can ignore the last modal in Figma file..

**Comment by STew790** [comment]
**QA OK**

Enable Tor modal is shown when CJ account is added.

![image](https://user-images.githubusercontent.com/48477147/199717770-ff0166f4-bf8e-4a01-8899-454650b3235a.png)

**Info:**
 - Suite version: web 22.11.1 (8a8808d3c3fd752bde89507d50650bc4bac56647)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32
