### ISSUE TITLE
Coin control with anonymity level

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#6215]
**UTXO Categories**
1. Private - UTXOs with anonymity at least as desired anonymity level
2. Not private - UTXOs with anonymity lower then desired anonymity level
3. _Dust (already implemented)_

**UTXO Tags**
1. Registered in CoinJoin - ~~disabled from spend~~
2. Banned from CoinJoin - blacklisted or lower amount than `5000 sats`
3. _Change address (already implemented)_

User has to confirm additional check if he is using UTXOs with lower then desired anonymity level

_Note: we don't need to disable registered UTXOs from spending. Suite will not communicate registration confirmation to coordinator and UTXO will be automatically removed from CoinJoin round. Modal will prevent double-spend (CoinJoin round breakage) If we reach the critical phase_

![CoinJoin - Coin control](https://user-images.githubusercontent.com/26002916/197186055-f19de8f6-d4d6-4fe4-b5e0-d4b2f32afc6a.png)

**Comment by komret** [comment]
Regarding the banned transactions tag:
1) I am only implementing this for UTXOs lower than 5000 sat as the blacklisting has not been implemented yet if I'm not mistaken.
2) Are we going to differentiate the tooltip message between blacklisted and small UTXOs?
3) What exactly should the tooltip message say?

**Comment by komret** [comment]
The anonymity indicator uses a different icon and wording than the global indicator and a similar component in transaction detail. Is this intentional? Unless I am missing something, a unified representation seems better.
![Screenshot 2022-10-28 at 20 39 37](https://user-images.githubusercontent.com/42465546/198708860-25ef7640-656f-4390-b2ea-7384868df1dd.png)
![Screenshot 2022-10-28 at 20 35 32](https://user-images.githubusercontent.com/42465546/198708669-507e7eb7-e2e9-485c-91a3-d3ae1df1f407.png)
![Screenshot 2022-10-28 at 20 35 49](https://user-images.githubusercontent.com/42465546/198708689-92faf0ba-60ea-443c-aa1c-d9669f9418d4.png)

**Comment by hynek-jina** [comment]
> Regarding the banned transactions tag:
> 
> 1. I am only implementing this for UTXOs lower than 5000 sat as the blacklisting has not been implemented yet if I'm not mistaken.
> 2. Are we going to differentiate the tooltip message between blacklisted and small UTXOs?
> 3. What exactly should the tooltip message say?

@komret 
1. OK → I'll create a followup
2. Yes, please
3.  "Not available for CoinJoin - too small amount"

**Ad icons**
Thanks for noticing that... I agree with you. ~~I've asked Ondra, but If that blocks you, please use the two-headed icon meanwhile.~~
Please use three-headed icons everywhere.

**Comment by hynek-jina** [comment]
And please stick to `1 in X` representation of anonymity level...
