### ISSUE TITLE
User-agent in requests over TOR

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6230]
Followup for #6017

when communicating over TOR, we should consider user-agent header. 

Options are 

## 1. Send the most common UA header
Pros: Better privacy
Cons: what is common today will be unordinary after few months

## 2. Send the same UA like TOR browser does
pros and cons similar to the option 1

## 3. Send empty UA string
Props: Reportedly wasabi does it this way, better annonymity within coinjoin. Easy to do, no maitanance costs or risk

## 4. Rotate common UA strings
Similar to the option 1. Mitigating the fact that once a specific UA string becomes obsolete it becomes also somewhat easier to distinguish

**Comment by mroz22** [comment]
- consider using https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization instead of user-agent
- send the same headers like wasabi does

**Comment by karliatto** [comment]
I created PR https://github.com/trezor/trezor-suite/pull/6290 to update User-Agent to Proxy-Authorization.

But I there is the other task `send the same headers like wasabi does` which requires checking all the header that `wasabiwallet` is sending and override what it different. Some of them are different for sure, since now when we do not override User-Agent it looks like below when using npm module `node-fetch`:

```
'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
```
