### ISSUE TITLE
Create account of coin that did not success in discovery crashes the app

### ISSUE THREAD

**Issue by karliatto** [trezor/trezor-suite#6450]
**Describe the bug** 
Creating new account when discovery has finished even unsuccessfully is available but the app crashes when trying to create a new account.

**Info:**

-   Suite Version: latest develop, desktop because

**How to reproduce**

1. Start the app with (for example) Bitcoin as only crypto and use as custom back-end  blockbook with and URL that is not going to work like "https://test.com"
1. Refresh app so discovery starts again and wait until discovery fails because it has wrong custom back-end.
1. Go to "Accounts"
1. Click on `+` button besides "My accounts"
1. Select Bitcoin and app crashes.

**Expected behavior**
The app should not crash.
Probably the correct behavior would be preventing the user from creating new account or a currency  that did not successfully finished discovery.

**Screenshots**

![image](https://user-images.githubusercontent.com/5362163/193552683-2fa41cf1-d26c-4317-afca-181d4b17ba6b.png)

**Additional context**
It looks like the issue is caused because account is not present https://github.com/trezor/trezor-suite/blob/0c46c33e2a00b7f183ebad624c32097819db4367/packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx#L46

Probably it should check if account is present and if not display some kind of message to the error, because it could happen that some currency successfully finished discovery and other did not.

**Comment by mroz22** [comment]
may I plese ask @trezor/qa to check whether the repro still works? And if yes, (optional) write an automated test for this repro for a test driven development fix?

**Comment by STew790** [comment]
When I refresh the app after adding the backend URL that won't work, the loading of the app takes quite some time (about 30s) but the app will eventually load and when I want to add the account, it again takes some time but it will eventually fail on this, which is not really correct but I think it's OK:
![image](https://github.com/user-attachments/assets/a7cf2eb6-3a2e-43a1-9b3c-ba0a00d91d2a)

because on other accounts and in the bottom left tooltip I can see that the backend is not connected:
![image](https://github.com/user-attachments/assets/221c8a39-596f-4c84-a4a9-7fb617587358)

Nonetheless, it doesn't end with crash.

**Comment by karliatto** [comment]
Closing since it is not reproducible anymore.
