### ISSUE TITLE
Coinjoin:  coinjoin not authorized, device call in progress race condition

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-suite#6748]
![image](https://user-images.githubusercontent.com/30367552/199319712-d79927ea-3135-4eeb-a2bf-088ac1f69c78.png)

can be reproduced in test added in this PR https://github.com/trezor/trezor-suite/pull/6737

**Comment by bosomt** [comment]
**QA NOK**

I was able to reproduce issue.
Looks like i was able to press `Anonymize` button trice at once.
This usually happens when you press one button and before Suite and Trezor reacts you will send another request to device.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/31506317/200398031-c0bd04c4-4db0-4340-97b5-a4313e762b99.png">

**Info:**
 - Suite version: desktop 22.11.1 (36517f2367056ec69f25858ddd96684364d1dbc5)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.11.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by mroz22** [comment]
Yep, 
- relevant coinjoin methods should be added here https://github.com/trezor/trezor-suite/blob/develop/suite-common/connect-init/src/connectInitThunks.ts#L64
- and we should make sure that all the buttons that should be disabled are disabled when suite.locks are set

**Comment by bosomt** [comment]
**QA OK**

I have not seen this error for long time.
