### ISSUE TITLE
Broken formating when name of the asset is long

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#6770]
When the name of asset is longer and the amount has too many number of digits after zero, design is broken. 

We agreed with designers to go with these rules:
1. Values (FIAT and crypto balance)
- Dashboard and Asset detail header - Dynamic type 
- Dashboard coin tiles - crop the text

2. Texts (name of asset)
- ✅ Dashboard, asset list and TX Detail - Overflow
- Header text - crop

3. TX ID
- ✅ cropping in the middle

Types of how to approach the text and values are in Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/tCSmT0EOdXmhAst051Nxal/s2-Mobile?node-id=7568%3A47342&t=z17h9eezA2fRAay3-0

Printscreens:
Dynamic type:
![Image](https://user-images.githubusercontent.com/84183817/210736195-94c1a1cc-cf76-4270-b1ed-b81936e0c103.png)

Overflow:
![Image](https://user-images.githubusercontent.com/84183817/210736285-e46d02c8-e6fa-439b-bcd5-867c94604bde.png)

Cropping
![Image](https://user-images.githubusercontent.com/84183817/210736367-34464d77-12e9-4373-af6d-d477896c365c.png)

Crop in the middle (TX Detail)
![Image](https://user-images.githubusercontent.com/84183817/210736448-f713c2bf-2093-449c-ada9-f5b11cca0234.png)

**Comment by juriczech** [comment]
@mnuky I think this is more problem of number formatting. Maybe you'll disagree but I think the number / balance should be formatted with fixed number of decimal points. Eg. 0.022 instead of super long number. This would fix the problem. Then we can also have a look at some edge cases when longer names of coins appear, but if we just cut the number to some reasonable length, it will be fine. What do you think?

**Comment by mnuky** [comment]
@juriczech I agree and there has been issue already created to round the digits - https://github.com/trezor/trezor-suite/issues/6790. We can first round the digits and then check whether it worked and fixed the formatting, ok?

**Comment by mnuky** [comment]
it seems the number of digits differs for each coin, for Ether we use 18 digits. So we would need to handle the situation with more digits anyhow

**Comment by juriczech** [comment]
@mnuky Can you please discuss this with UI somehow? Currently, I don't think we'll be able to fit full coin name and 18 digits on same line so there needs to be some change because of that. Formatting digits will be taken care of in https://github.com/trezor/trezor-suite/issues/6790 and then we can figure out how to format with text properly in this task.

**Comment by mnuky** [comment]
Sure, I will today

**Comment by juriczech** [comment]
I'll move this to next sprint so we can first determine whether the rounding digits is sufficient to solve this problem.

**Comment by juriczech** [comment]
@mnuky Rounding digits task was merged yesterday. Can you please check it out and determine whether this task is still needed?

IMO: Rounding digits currently solves issues for accepted currencies and until we allow importing more coins, there is no need to do this now, so we could close this issue and resolve it when we allow more coins in the app.

**Comment by juriczech** [comment]
Sorry, accidentaly closed by comment. Reopened until we decide how to approach this 🥶

**Comment by mnuky** [comment]
it is still an issue while the name of asset is long - take a look on the printscreen. But it is more UI problem now. 
![Image](https://user-images.githubusercontent.com/84183817/201883948-c25122de-7c0e-42a0-a8c7-9b19b2292dd5.PNG)

I would suggest to change the issue from bug to standard task and I will assign to myself to come up with solution together with designers

**Comment by bosomt** [comment]
**QA OK**

tested on iPhone version 225
