### ISSUE TITLE
Trezor Connect throws Method_NotAllowed on non-localhost origins

### ISSUE THREAD

**Issue by arminsabouri** [trezor/trezor-suite#6805]
**Describe the bug**
I am looking to call 
```js
TrezorConnect.applySettings({
  safety_checks: 'PromptTemporarily',
})
```
This appears to work on localhost and trezor web suite. However, on any other origin, this method throws 
`{"code":  "Method_NotAllowed", "error": "Method not allowed for this configuration"}`

 Is this expected behavior? Is there any way to init trezorConnect to get around this?

**Firmware version and revision**
Trezor Model T 2.4.3

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Custom
 - OS: MacOS 12.3.1
 - Browser Chrome
 - Version 107.0.5304.87

**To Reproduce**
1. Call `applySettings({...})` on any non-localhost origin.

**Expected behavior**
Saftey checks can be disabled

**Comment by sime** [comment]
Hi @0xBEEFCAF3 

This is intentional, we intentionally disallow device ['management'](https://github.com/trezor/trezor-suite/blob/develop/packages/connect/src/api/applySettings.ts#L10) features on 3rd party applications.

I will flow this ticket for now, though you are welcome to share your use case, and we can put it to consideration.
