### ISSUE TITLE
refactor: Rename accounts screen and packages to Assets

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6827]
@mnuky Is the naming for assets and asset detail already set? For example currently we're using `AccountDetailScreen` in code but according to design, naming should be `AssetDetail`. Is this going to be stable naming for now and we can refactor screens to use this naming as well? Thanks.
cc @Nodonisko

**Comment by mnuky** [comment]
Good question.. So far we did not discuss final naming of the elements but so far we agreed to use assets instead of account . I can't guarantee that it will not change in the future

**Comment by Nodonisko** [comment]
I do not agree, it will be more confusing, because we don't treat it as Assets now. For example right now you can have multiple BTC accounts and you can see each detail of each on AccountDetailScreen, but from definition Asset is something like all BTC accounts merged into one, which we don't do anywhere except overview on Dashboard.

**Comment by Nodonisko** [comment]
I think idea of Assets is still somehow confusing because we treat Assets as Accounts in many places just calling them differently. We need to be clearly set-up what is "Asset", how it should behave etc. Right now it doesn't make sense to rename accounts to assets because it should be two different things.

**Comment by juriczech** [comment]
@Nodonisko I agree with that. That is why I wanted to just create a discussion. If we should have it as accounts, it shouldn't be named asset detail, because asset detail is basically list of accounts, not account detail. 

It's just slightly annoying to have this mental model when coding this stuff, because it just doesn't feel right 😀

Not to talk about an inconsistency with desktop as well. If I would be using trezor with desktop and then would switch to the app, I would be confused. I wouldn't mind if we just used the account naming and when it's time to switch to assets, we should probably do it on both platforms to keep it consistent.

**Comment by mnuky** [comment]
understand, the discussion around naming is still progress. The problem with namin Account is that users don't understand that it is the coin, there is huge confusion around that and from user research it seems that name Asset is more understandable for users. But I agree we need to sort this out.

**Comment by Nodonisko** [comment]
If you want to call it assets, I would prefer rename it only for users and in code still use accounts because whole suite use this naming.

**Comment by Nodonisko** [comment]
So conclusion on this is rename it for users, in code it stays same.

**Comment by juriczech** [comment]
@Nodonisko Should we close this issue and rename this when there is more changes as well? I assume there will be more copywriting issues before release. Wouldn't worry about it now - I just wanted to solve inconsistencies.

**Comment by Nodonisko** [comment]
Yes, feel free to create new one for that copy.
