### ISSUE TITLE
Improve formatting of the coinjoin session countdown timer

### ISSUE THREAD

**Issue by dahaca** [trezor/trezor-suite#6927]
Currently the main countdown timer looks slightly off because there is too much text inside of the circle. It can be improved by adding a custom locale object to `formatDuration()`, replacing `hours`, `minutes`, etc with `h`, `m`, translated to all languages.

<img src="https://user-images.githubusercontent.com/45338719/201990370-90283238-41ab-4ad9-bfb5-a35cec487fd4.png" />

**Comment by STew790** [comment]
**QA OK**
H instead of "hours".
![image](https://user-images.githubusercontent.com/48477147/222455982-87d5d776-0bac-4a85-8f01-7854b9299442.png)

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32
