### ISSUE TITLE
Transaction signing error

### ISSUE THREAD

**Issue by Bonzbonanza** [trezor/trezor-suite#6945]
I was getting the following error when trying to move some ADA from a hidden wallet on my Trezor T to another wallet. Wallet is through Yoroi. 

"Transaction signing error: Constructed transaction doesn't match the hash returned by the device."

Newest firmware, newest Suite. Other transactions working.

Eventually solved by turning off Tor, creating a new recipient address, and initiating the transaction through Yoroi instead of Suite.

**Comment by bosomt** [comment]
**QA OK**

i was not able to reproduce issue on dev master /tried to sign 20+ txs/

**Info:**
 - Suite version: desktop 22.12.0 (26b0a1d40abe308102d5f1a27cac0bf483fb541e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.12.0 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: bridge 2.0.32

**Comment by shoojilipef** [comment]
It only is happening with one of my ada wallets. I've been transfer all of the funds from the malfunctioning wallet to a new wallet and while the test amounts worked twice for two different wallet addresses I can't get the remainder of the funds to transfer to another wallet now. I've tried restarting the app, my computer and waiting 12 hours..

**Comment by Bobjt** [comment]
I reproduce this issue regularly: 
"Transaction signing error: Constructed transaction doesn't match the hash returned by the device."
on account (XPUB): 
d062883d2b1d437f7f97575f41e9653845578a9f47ff4e4c5b73b8a56df7951b0529a2ee571f2b162f0ef078e5728760245ab597ddea2d7412ddaa670fb141eb

- Trezor Suite version 22.11.1 (22.11.1.23351)
- Firmware [2.5.3] (16th November 2022)
 
No matter of changing destination addresses, amount, gas/lovelace works around it. And because Trezor isn't exporting the right keys to let me view this account in other third party wallets (Yoroi, Adalite, Nufi) this account/balance is 100% dead in the water!

**Comment by Bobjt** [comment]
Ah supposed to be fixed in 22.12.0. Holding out for that... Thanks all!!!

**Comment by Bobjt** [comment]
When is 22.12.0 arriving and why isn't this fixed on the web yet?

**Comment by sime** [comment]
Release is planned for the 21st of December, with early access typically available a week before.

We release both web and desktop together.
