### ISSUE TITLE
Filter imported accounts 

### ISSUE THREAD

**Issue by juriczech** [trezor/trezor-suite#6988]
As a user I would like to be able to filter / search in imported assets in order to be able to find my assets faster when I have dozens of them. 

Figma: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/%5Bs2.0%5D-Mobile?type=design&node-id=19433%3A112322&mode=design&t=oX0r9J8ejKIZrzpt-1

Acceptance criteria: 

- User can search via name of the account, name of the coin
- Matching results are displayed

Add filter for imported accounts based on stored xpubs. If user adds new type of coin, it should be included as filtering option in `My assets` tab.

**Comment by hynek-jina** [comment]
@juriczech Is this done?

**Comment by mnuky** [comment]
QA NOK:
1. UI is not matching:
- Paddings don't match with Figma designs
DEV:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/388d5e77-d4c7-4778-bc92-30dd854b6cba)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/1f3fd734-7e80-42f1-9d0b-e833f0d028a1)
![Image](https://github.com/trezor/trezor-suite/assets/84183817/2b5ad160-0bc2-4849-8827-9ebf272406ae)


Figma:
![Image](https://github.com/trezor/trezor-suite/assets/84183817/9aacdce6-25be-4a55-9a2e-2691a7f7268f)
- Input is moved above the inserted text, it should disappear, otherwise the input field is too high and it does not look good
2. When I search for ETH token, results show ETH and related tokens as well. 


![Image](https://github.com/trezor/trezor-suite/assets/84183817/aa6995b6-a798-4b49-b166-40f215b2a6a6)

**Comment by bosomt** [comment]
**QA NOK**

- iPhone 11
- f1d7d1f - [develop] - fix(suite): RBF form DecreasedOutputs view RadioButton margin

Search still results in all Eth tokens/accounts displayed.
otherwise works as expected

![telegram-cloud-photo-size-4-5978598114325544042-y](https://github.com/trezor/trezor-suite/assets/31506317/8a165604-5ec9-48d2-a6a3-e7115a969368)

**Comment by PeKne** [comment]
@bosomt 
> **QA NOK**
> 
> * iPhone 11
> * [f1d7d1f](https://github.com/trezor/trezor-suite/commit/f1d7d1fbf4a076eaa26874649af2aaa3b7825bdb) - [develop] - fix(suite): RBF form DecreasedOutputs view RadioButton margin
> 
> Search still results in all Eth tokens/accounts displayed. otherwise works as expected

It is expected. In the end, we decided that this needs more research on how tokens should be filtered (if they should be included or not). So for now we decided to leave it as it is. 

Sorry for forgetting to mention this in this issue.
