### ISSUE TITLE
Integrate multiple intermediary FW to Suite

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7290]
Implement the recognition of the necessary second intermediary FW according to the Trezor device
 
_We are not able to stick to one universal intermediary firmware_

**Comment by matejcik** [comment]
## Background: Legacy signing methods

For legacy (T1) firmware, there are two header types:
* **legacy-style**: starts with `TRZR` bytes, does not have much information, just some signatures and a feature bit or two. First 256 bytes are header, the rest is firmware data.
  Bootloaders **< 1.8.0** require a legacy-style header.
* **core-style**: starts with `TRZF`, has a structured header with a lot of data incl. version, header has ~800 bytes total.
  Bootloaders **>= 1.8.0** require a core-style header.

And there are **three** signature versions:
* **v1** - used exclusively with legacy-style header, i.e., up to BL **< 1.8.0**. 3-of-5 scheme.
* **v2** - used with core-style header, BL **>= 1.8.0, < 1.12.0**. Same scheme and same keys as v1.
* **v3** - used with core-style header, BL **>= 1.12.0**. 2-of-3 scheme, new keys.

The difference between v2 and v3 is whether the last of the 3 signature slots is used or not.
If you see a signature in the third slot, consider the image v2-signed. If it is all zero, it should be v3-signed.

## Dual-mode headers

It is possible to encapsulate a core-style firmware within a legacy-style header, by:
1. building and signing a core-style image
2. prepending a 256-byte legacy-style header and signing it, with the signed core-style image as its firmware data.

You would only download a single file for any BL version. If the version was 1.8.0 or above, you would strip first 256 bytes of data from the firmware image, otherwise you would keep it as-is.

## Current situation

Dual mode is unfortunately not enough to fit three distinct signed images -- and we didn't implement triple-mode.

Going forward, we will only be distributing firmwares as **v3** signed core-style images. That means that to install firmware, the Trezor _must_ have BL **1.12.0** and up.
(technically speaking 1.12.1 because version 1.12.0 was internal only)

To get there, we will distribute **intermediate images** for all three signature versions:
* **inter-v1v3** is _dual-mode_ legacy style image signed v1, with core style image signed v3 inside
* **inter-v2** is core style image signed v2

if it makes things any easier, we can as well distribute an **inter-v3** image as a core-style signed v3.

## Versions & applicability

To upgrade a BL **< 1.8.0** to current => send it an **inter-v1v3** image unmodified.
To upgrade a BL **>= 1.8.0, < 1.12.0** to current => send it an **inter-v2** image.
To upgrade a BL **>= 1.12.0** to current => strip first 256 bytes from the **inter-v1v3** image, then send the result.

**Comment by sime** [comment]
@matejcik Is this a blocker for the March T1 FW release?

**Comment by matejkriz** [comment]
> @matejcik Is this a blocker for the March T1 FW release?

@sime yes

**Comment by STew790** [comment]
**QA OK**
Tested during our sanity tests including the new FWs.
