### ISSUE TITLE
Automatic conversion of non-checksummed address

### ISSUE THREAD

**Issue by mkolar242** [trezor/trezor-suite#7407]
**Design:**
![convert-checksum](https://user-images.githubusercontent.com/42438053/213112662-0945fcae-5791-4696-8946-e7dea6dbf46c.png)

**Spec:**
As a user if I type or paste an Ethereum address in invalid format, Trezor Suite needs to convert the address to a supported format automatically and inform me about it.

When I paste or manually enter valid non-checksummed Ethereum address to the Ethereum Send address field, Trezor Suite converts it to checksummed address

I need to be informed that such automatic conversion happened below the Send address field

**Acceptance criteria**

- Trezor Suite checks the address and converts it to a checksummed version automatically
- Below the recipient’s address on the left side I see blue double check mark which indicates the address was checked as valid and also converted to the checksummed address
- Next to the double check mark I see blue text “Converted to checksum address”
- On the right side I see “Learn more” button which redirects to the KB article ([https://trezor.io/support/a/ethereum-convert-checksum-address](https://trezor.io/support/a/ethereum-convert-checksum-address))
- When I paste or manually enter invalid Ethereum address to the Ethereum Send address field, Trezor Suite shows an error the same way as it does now

**Comment by tomasklim** [comment]
During development, it would be nice to approach it in a generic manner, so that we can reuse it for ENS. It can potentionally be reused also for a "warning system" - for alerts e.g. user when is sending money to a contract address or to an address he has never sent to before

**Comment by Hannsek** [comment]
Yes, this right. We plan to do that in the future. No ETA tho. :(

**Comment by andrewkozlik** [comment]
@mkolar242 how does one determine the validity of a non-checksummed Ethereum address?

**Comment by andrewkozlik** [comment]
Automatic conversion of addresses is a very dangerous feature that can lead to irreversible loss of assets. We need to be very careful about how we implement a feature like this.

AFAIK every hexadecimal string of 40 digits in length is a valid Ethereum address if you ignore capitalization. The capitalization acts as a checksum. So if it doesn't match, then either the user made a typo which they should fix themself, or the user entered the address without capitalization, i.e. without checksum, in which case Suite offers the "*Convert to checksum address*" button.

We need to be clear about terminology. I propose the following:

A *valid* Ethereum address is one that matches the regular expression `^0x[0-9A-Fa-f]\{40\}$`, i.e. starts with `0x` followed by 40 hexadecimal digits. We could even make the `0x` optional.

A valid Ethereum address is *unchecksummed* if it matches the regular expression `^0x[0-9a-f]\{40\}$\|^0x[0-9A-F]\{40\}$`, i.e. all hexadecimal letters are either uppercase or lowercase. Otherwise the address is *checksummed*, i.e. contains at least one lowercase and one uppercase hexadecimal letter.

A checksummed Ethereum address may either be checksummed *correctly* or *incorrectly* depending on whether it satisfies EIP 55 or not.

A valid Ethereum address is *used* if, when we ignore capitalization, it leads to an account with at least one outgoing transaction. In other words, the destination address has a non-empty history and in addition someone was capable of spending funds from that address in the past.

I propose the following behavior in Suite:
- Once the user enters a valid Ethereum address, Suite will check via Blockbook whether the address is used.
- If the address is used but unchecksummed or incorrectly checksummed, then Suite will automatically convert the address to the correct checksummed form and inform the user as described in the OP.
- If the address is not used or the usage state is unknown, e.g. because Suite is offline, then Suite will essentially proceed as it does now, but it will include an additional warning dialog. In particular:
  - If the address is incorrectly checksummed, then Suite will not offer any means to repair the checksum.
  - If the address is unchecksummed, then Suite will offer the "*Convert to checksum address*" button. When this button is clicked, Suite will show a warning dialog explaining what is happening, e.g. "*The capitalization of the address will be repaired. Please check carefully that the result is correct.*", with an option to proceed or cancel. If the user chooses to proceed, then Suite will convert the address to the correct checksummed form and inform the user as described in the OP.

We may also consider renaming the "*Convert to checksum address*" button to something more intelligible to users, such as "*Fix capitalization*" or "*Repair address*". Not sure if it helps anything. Just a thought.

**Comment by bosomt** [comment]
**QA OK**

- dead link to [KB](https://trezor.io/learn/a/evm-address-checksum-in-trezor-suite) but i expect it to be released with this PR
- fresh address that i changed to all lower case `Address has no transaction history and is not checksummed. Please verify it is correct.`
- already used address that i changed to all lower case is `converted to checksum`
- valid address is still accepted with no message
- address with 0X and not 0x is `Address is not valid`

**Info:**
 - Suite version: web 24.9.0 (6d647cf2c218b432a970a7ca830f3fa2e8673b60)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
 - Transport: BridgeTransport 2.0.32

**Comment by enjojoy** [comment]
> **QA OK**
> 
> * dead link to [KB](https://trezor.io/learn/a/evm-address-checksum-in-trezor-suite) but i expect it to be released with this PR
> * fresh address that i changed to all lower case `Address has no transaction history and is not checksummed. Please verify it is correct.`
> * already used address that i changed to all lower case is `converted to checksum`
> * valid address is still accepted with no message
> * address with 0X and not 0x is `Address is not valid`
> 
> **Info:**
> 
> * Suite version: web 24.9.0 ([6d647cf](https://github.com/trezor/trezor-suite/commit/6d647cf2c218b432a970a7ca830f3fa2e8673b60))
> * Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
> * OS: MacIntel
> * Screen: 1512x982
> * Device: Trezor T2T1 2.8.1 regular (revision 632b9561559b7ab6824bb7eeac072874e07b7b82)
> * Transport: BridgeTransport 2.0.32

Thank you. Yes, we've requested the article about checksum, so it should be updated before the freeze.
