### ISSUE TITLE
Make Text atom pass styling to children Text components

### ISSUE THREAD

**Issue by PeKne** [trezor/trezor-suite#7468]
The current implementation of the Text component doesn't pass styling props to its children.  Make styling props inheritable so it's not needed to redefine props already defined in the parent.

### Current implementation
```jsx
                <Text variant="titleSmall">
                    <Text variant="titleSmall" color="forest">
                        Trezor Go
                    </Text>
                    addresses
                </Text>
```

### Expected implementation
```jsx
                <Text variant="titleSmall">
                    <Text color="forest">
                        Trezor Go
                    </Text>
                    addresses
                </Text>
```

### Appearance of code above
![Image](https://user-images.githubusercontent.com/26143964/215034694-e80904c9-57e3-46e0-8e45-d2d57daa8c25.png)

**Comment by Nodonisko** [comment]
Two solutions for this in my mind:
1. Add one extra option value `inherit` to typography/color/align prop that will cause that no styles will for this will be appplied at all, which will cause Text to inherit these values.
2. Use context approach like NativeBase for example https://github.com/GeekyAnts/NativeBase/blob/master/src/components/primitives/Text/index.tsx

I probably prefer 1. because it's quite simple. Anyway no big issue for us now, so we will keep this in backlog for now.

**Comment by Nodonisko** [comment]
We need this very rarely, just pass same styles twice. It's also faster than any other solutions in terms of perf.
