### ISSUE TITLE
Missing switch between multiple coinjoins

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#7469]
**Describe the bug**
Missing switch between multiple coinjoins

**How to reproduce**
1. Add two coinjoin accounts (use various passphrases)
1. Start coinjoin on both accounts
1. You should see small `view` button in top right corner → but it's not there in latest version

**Expected behavior**
When I'm not in coinjoin account (for example in another account) I should have an option in top global progress bar to navigate to running coinjoin..
<img width="127" alt="image" src="https://user-images.githubusercontent.com/26002916/215038142-f629dccd-c468-4fe7-9233-2f2a5658f8cd.png">

**Screenshots**
![Snímek obrazovky 2023-01-25 v 14 21 24 (1)](https://user-images.githubusercontent.com/26002916/215037829-6f1cf5f3-0cce-4065-bc42-37037748ffd0.png)

_note from @matejkriz:_
> _I see that there is a condition that the discovery on the other account has to be completed_

**Comment by dahaca** [comment]
As matej said, the only condition for the button to show up is that the [device is discovered](https://github.com/trezor/trezor-suite/blob/d6603dfc4a612d5c71d7a641cf023d67c2525c61/packages/suite/src/components/suite/CoinjoinStatusBar.tsx#L125). Based on your screenshot it should be, since `Hynek` and `Hynek2` are located on the same device. 🤔  I was not able to replicate as well, sadly. 

Perhaps one of the accounts was out of sync but then it should be resolved as soon as it was synced.

**Comment by matejkriz** [comment]
> As matej said, the only condition for the button to show up is that the [device is discovered](https://github.com/trezor/trezor-suite/blob/d6603dfc4a612d5c71d7a641cf023d67c2525c61/packages/suite/src/components/suite/CoinjoinStatusBar.tsx#L125). Based on your screenshot it should be, since `Hynek` and `Hynek2` are located on the same device. 🤔 I was not able to replicate as well, sadly.
> 
> Perhaps one of the accounts was out of sync but then it should be resolved as soon as it was synced.

In this context device means wallet – add multiple hidden wallets and check the redux state... So you can't say from the screenshot, that the device is discovered.

I believe that the condition is just wrong. Do you remember why you put that condition in there?

**Comment by hynek-jina** [comment]
However I'm not able to reproduce it on `23.2.1`
