### ISSUE TITLE
Cardano can't be imported (iPhone) or breaks the graph (Android)

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#7517]
**Steps to reproduce iPhone**
- Try to import Cardano XPUB
- Import fails - see printscreen
![Image](https://user-images.githubusercontent.com/84183817/216030154-8fda105b-c4b8-4ab4-bec4-5488c2b5e6fe.PNG)

**Steps to reproduce on Android:**
- Import Cardano XPUB
- Portfolio graph is not loaded
- Go to Cardano asset detail - graph is not loaded
![Image](https://user-images.githubusercontent.com/84183817/216030663-28758570-15f6-44ce-ba01-4004912e89d0.png)
![Image](https://user-images.githubusercontent.com/84183817/216030665-6ac82122-8ccb-47dd-8ad7-8a20d5079a74.png)

**Comment by mnuky** [comment]
Upload itself is working, but the graph is still broken:
[

![Image](https://user-images.githubusercontent.com/84183817/222174829-4f13eb1a-bfa6-494f-b642-712376c9a98f.png)

](url)

**Comment by PeKne** [comment]
Import of Cardano works correctly since the merge of #7722. The Problem of a broken graph chart is not related to this at all. 

Broken graph chart is caused by calling of function: https://github.com/trezor/trezor-suite/blob/12b31a9473c9ccbe70ac69b27fb72ebcd5055f90/packages/blockchain-link/src/workers/blockbook/index.ts#L90

Which is implemented for blockbook, but not for blockfrost (Cardano worker). IMHO blockfrost does not support fiat rates at all at the moment. To fix this, the method `getFiatRatesForTimestamps` need to be implemented also for blockfrost or we need to get Cardano fiat rates from elsewhere.

**Comment by bosomt** [comment]
**QA OK**


i was able to import cardano account via qr code 
- version - iPhone dev 23.6.1 (297). 8ac7640
