### ISSUE TITLE
Coinjoin unpause automatically or is not paused

### ISSUE THREAD

**Issue by matejkriz** [trezor/trezor-suite#7693]
**Describe the bug**
I see couple times that coinjoin starts automatically after Suite launch, remembered device. @andrewkozlik reported from 23.2.2 (c985af54) version that he paused the coinjoin and than critical phase after couple of minutes begin anyway. 

**Info:**

-   Remembered Wallet: yes
-   Suite Version: app 23.2.2 , commit c985af54

**How to reproduce**

1. Go to coinjoin account and start coinjoining
1. Click on Pause
1. Do something, not sure what exactly, I guess it could be Tor related

**Expected behavior**
coinjoin should not started automatically if it has not been paused automatically by going to Send form or loosing connection.

**Additional context**
Related logic has been touched recently in this PR https://github.com/trezor/trezor-suite/pull/7587 but the bug report is from the version before this has been merged.

**Comment by matejkriz** [comment]
I have a logs from Andrew available.

**Comment by matejkriz** [comment]
Maybe it's happening only in our dev flows because of some reloads or I don't know. Maybe we can handle it by deleting `interrupted` flag on start (not sure what action should trigger that deletion)

**Comment by komret** [comment]
This is what's happening:
1. Suite opens
2. `tor-status` returns `Disabled` while Suite is loading
3. `coinjoinMiddleware` reacts to `tor-status` by interrupting a session - it thinks the session is running because database does not say `paused: true`; this is either because the session was running when the user quit Suite or because the account was not saved after pausing the session (bug)
4. when `tor-status` is checked again, it returns `Enabled`
5. `coinjoinMiddleware` restores all interrupted sessions

Possible solutions (supposing we do not want Suite to ever restore the session on launch):
A) Do not store any session data in the database - there will simply be no session on launch. This is straightforward, but I am not sure if need the data for something. I noticed we save `previousSessions`. @hynek-jina prefers this.
B) Whenever session data is saved to (or read from) the database, set `paused` to `true`, `interrupted` to `false` and `starting` to `false` - there will always be a paused session on launch if one has been started previously.

Suggestions welcome.

**Comment by szymonlesisz** [comment]
<del>i dont think it is strictly tor-status related issue, i'm experiencing the same while developing in browser where there is no tor related actions.
i didnt focus on it too much but something tells me that issue is somewhere near conditions in middleware + discovery/account update combination.</del>
 i was wrong, it's exactly as you said :)


i would not remove `CoinjoinSession` from the account, it's planned to be extended in the future (post mvp) to be able to fully restore previously running session in case of reload in critical phase.

i would rather go with B and redact saved data like storageActions: serializeDevice

**Comment by komret** [comment]
OK, I did what @szymonlesisz proposed and created a `serializeCoinjoinSession` util which always sets `paused` to `true` when the session is saved. However, if we WANT the session to automatically restart in future, we will have to come up with some other approach.

**Comment by komret** [comment]
**QA:** Whatever the state of coinjoin session was when Suite closed/reloaded, it should be paused at launch/refresh. The top bar should never show a time estimate when session is paused.

**Comment by STew790** [comment]
**QA OK**
I just tried reload and restart (and also accidentally one crash :sweat_smile: ) and CJ paused and resumed correctly.

**Info:**
 - Suite version: desktop 23.4.0 (f4dee18ecd17bcce530ae7837c5a34a7b922762a)
 - Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.4.0 Chrome/104.0.5112.124 Electron/20.3.12 Safari/537.36
 - OS: Linux x86_64
 - Screen: 1920x1080
 - Device: model T 2.5.4 Universal (revision 557e29769b09dd3abd7b67f9b4fe3d380db9f6c9)
 - Transport: BridgeTransport 2.0.32
