### ISSUE TITLE
The release tagging is in the wrong place these days

### ISSUE THREAD

**Issue by fujicoin** [trezor/trezor-suite#7819]
It seems like the release tagging is in the wrong place these days. The source code at the location of the tag and the distributed binary must not correspond.
I will explain more specifically. For example, the `v23.2.2` tag is attached to commit `18d3ebe`, but this commit is on the `master` branch, not on branch `release/23.02`. At this time, "suiteVersion": "23.3.0" is written in package.json. However, the actual released binary is `v23.2.2`.
Why are these strange things happening?

**Comment by vdovhanych** [comment]
Looks like when this `pre-release` was created, we didn't set the `release/22.03` as the base branch when creating the tag, and it took the main branch for it. That's why it is pointing to the `develop` commit, as that was the latest commit at the time of creating the release and tag. That's where the confusion comes from, we will try to fix the tag if possible, but in general, we should avoid this mistake in the future.

Thank you for pointing this out.

**Comment by matejkriz** [comment]
@fujicoin Thanks again for noticing and especially for letting us know, it should be fixed now. Sorry for the confusion.
