### ISSUE TITLE
CJ initial sync took about 10min

### ISSUE THREAD

**Issue by nostitos** [trezor/trezor-suite#8150]
It looks like Trezor suite is checking way too many addresses for funds.

![image](https://user-images.githubusercontent.com/48504624/233092590-b42506f1-85dc-49e8-8168-79c271dd29af.png)

**Comment by marekrjpolak** [comment]
Hello @nostitos,

in order to preserve user's privacy, Coinjoin accounts fetch block filters for every block from initial checkpoint (block 778666 on mainnet) over Tor and scan them locally for your addresses. Because of that, CJ account syncing will always take much more time than regular accounts, depending mostly on Tor network status and performance of your machine.

We're working on some improvements which could accelerate the process a little. Meanwhile, you could speed up the subsequent syncs by remembering the wallet.
