### ISSUE TITLE
Communicate banned and pending UTXOs in coin control

### ISSUE THREAD

**Issue by hynek-jina** [trezor/trezor-suite#8372]
Requires: https://github.com/trezor/trezor-suite/issues/8370

Provide more information about UTXO:
| Icon | Meaning | Tooltip | State |
| --- | --- | --- | --- |
| ![Ban](https://user-images.githubusercontent.com/26002916/236407528-144c4816-c9a6-42e0-a9fe-a3f67a8f6710.png) | Banned for ruining round - it can last circa 6 hours | Currently unavailable for coinjoin | normal |
| ![ArrowsCounterClockwise](https://user-images.githubusercontent.com/26002916/236407875-d4db1d90-85cc-4334-ac05-097bdd96b62d.png) | Registered in signed transaction. Otherwise registered coins can be unregistered on demmand | Registered in coinjoin | disabled |

Example:
![Screenshot 2023-05-05 at 9 18 46](https://user-images.githubusercontent.com/26002916/236409371-bb50868c-db41-49c2-a29e-f6d6b690cc8c.png)

**Comment by komret** [comment]
I suggest using a tooltip instead of the icon to communicate UTXOs registered in coinjoin. Users might overlook the icon. This is in line with behaviour of other disabled controls in Suite. In fact, I already did it in https://github.com/trezor/trezor-suite/pull/9021.

https://github.com/trezor/trezor-suite/assets/42465546/404c4f9c-8d24-4b79-a225-cb91b1581fbf

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 23.8.1 (c6b91601f5c333a1de056fbf0b712995a96b5d90)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.8.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2T1 2.6.1 Universal (revision b151a3db6b04d2bee0bb68470e57b822443bf83d)
 - Transport: BridgeTransport 2.0.33
