### ISSUE TITLE
Empty account

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#840]
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6efa120829110bc496f4

**Comment by wendys-cats** [comment]
https://suite.corp.sldev.cz/suite-web/develop

**steps to reproduce:**
1. Deactivate all coin accounts in Settings
2. Go into wallet

**Expected behavior:**
see the visual provided in zeplin (message, picture, buttons)

**Actual behavior:**
Missing the message, missing the picture, also missing the Coin Settings button

![empty acc](https://user-images.githubusercontent.com/58593111/75447919-8e7a3300-596a-11ea-9da6-24f314dc4251.png)
