### ISSUE TITLE
General Settings

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#845]
General settings page: https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dde6f7ad36cb91f2de63ec5

**Comment by ZdenekSL** [comment]
@matejzak We think there is missing the language setting, fiat and btc settings, , or . etc. Lets brainstorm together

**Comment by mroz22** [comment]
imho done, more or less. Labeling button does nothing but thats because labeling is not implemented and it is separate issue.

**Comment by glacierbits** [comment]
@mroz22 Hide labelling "Connect Dropbox" option from the Settings (1Q). 
Once done, feel free to close the issue. Thanks!

**Comment by bosomt** [comment]
all buttons are working fine.
if there will be some issue I will create separate one

**Comment by wendys-cats** [comment]
**Issue: Cannot see in Device Settings chosen FIAT**

**Expected**
User can see the selected FIAT (in Device Settings, from "Primary FIAT currency to display" dropdown)

**Actual**
While the functionality is working (meaning user can change the displayed FIAT currency), only the placeholder (Select) is shown in Device Settings instead of the selected FIAT currency.

![FIAT SETTINGS](https://user-images.githubusercontent.com/58593111/79223737-33d56180-7e5a-11ea-99fb-c778f1a28f7c.png)
