### ISSUE TITLE
REQ: A new version of Suite without Coinjoin or Trade features (ie Trezor-Slim)

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-suite#8524]
## Trezor-Slim

**Request:**
Just as some customers want a bitcoin only firmware to ensure that no other attack surfaces or available, there are also customers that would prefer a scaled down version of Suite without integrations to zkSNARKs or +invity.  The principle complaint about both of these integrations is that the workflows they are part of can terminate with KYC (see 1, 2).  Although these are both OPT-IN features, given the pushback that the market has given on [past decisions by Ledger]() (see 3), and Trezor's own [reversal on AOPP]() (see 4), it may be a good time to introduce a minimalist version of Suite with as little third party IO as possible.

1. https://github.com/zkSNACKs/WalletWasabi/blob/8b159cb/WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
2. https://blog.invity.io/crypto-faq-what-is-kyc-know-your-customer/
3. https://www.reddit.com/r/ledgerwallet/comments/13layt7/my_personal_view_on_the_pr_disaster_from_a_ledger/
4. https://blog.trezor.io/a-decision-on-aopp-789540c2930b

Secondary considerations would also pertain to firmware flashing.  Since the only two ways to flash firmware are Trezor Suite and TrezorCTL, there is a possible need for something in-between those two products to catch users who are very concerned about networking traffic, but lack the technical skills to install TrezorCTL.

**Design:** 
A simple design with conditional inclusions would likely be the easiest appraoch.  This keeps everything in a single codebase, while still allowing the production of Trezor-Suite and Trezor-Slim.  Giving the full catalog of wallet software as:

* Trezor-Suite-App - The existing standalone binary as it exists today
* Trezor-Slim-App - The newly proposed build of Suite, but without CoinJoin or +invity
* Trezor-Lite-App - The newly launched mobile watch-wallet, unmodified
* Trezor-Suite-Web - The existing web-app site as it exists today
* Trezor-Slim-Web - A new web-app like Suite-Web, but without CoinJoin or +invity

**Comment by sime** [comment]
Hi @brianddk 

Thanks for the suggestion. Since coinjoin is a part of our Bitcoin only firmware, we can't imagine a distribution of Trezor Suite without it.

To extend your `Trezor-Slim-Web` idea, coinjoin accounts are not possible on Trezor Suite web, due to the requirements of multiple Tor identities.

> Since the only two ways to flash firmware are Trezor Suite and TrezorCTL, there is a possible need for something in-between those two products to catch users who are very concerned about networking traffic, but lack the technical skills to install TrezorCTL.

Just to note, Trezor Suite for Web also allows for device flashing. _Rarely_ do people just need flashing, they need to be onboarded to set up their Trezor too. Creating a new product would split our focus, and given our experience with Trezor Password Manager, we don't fare so well when that happens.

Thanks for your suggestion, and I feel I understand where your motivation is are coming from, and it's super appreciated.

For now, we won't work on any trimmed distributions of Trezor Suite.

**Comment by brianddk** [comment]
> To extend your Trezor-Slim-Web idea, coinjoin accounts are not possible on Trezor Suite web, due to the requirements of multiple Tor identities.

Excellent, I had assumed CJ was available on web.  This does indeed help and reduce the need for a formal product.
