### ISSUE TITLE
UI polishing - paddings

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8574]
Current version of the app has wrong paddings. See the comparison real app vs. figma designs: https://www.figma.com/file/Z6AGVUmKQzLNtDozFamW7f/branch/9ekR1zKZAnvteokURutvZ4/%5Bs2.0%5D-Mobile?type=design&node-id=18386%3A101695&t=gHvIG4FScRVHGpI6-1

1. Paddings from the side
![Image](https://user-images.githubusercontent.com/84183817/240843709-593b8223-70b1-4a28-9e19-0ca654613ef0.png)

2. paddings between texts
![Image](https://user-images.githubusercontent.com/84183817/240844281-2dcc2c4d-23c5-48f8-955d-f1c7b35ba1bd.png)

3. Paddings in headers
![Image](https://user-images.githubusercontent.com/84183817/240844534-5df7009e-919d-4843-9072-bb19df1dda4d.png)

4. Paddings between buttons
![Image](https://user-images.githubusercontent.com/84183817/240844759-b4ce69f2-83ff-4276-b084-adf10b78a519.png)

**Comment by juriczech** [comment]
**Implementation idea**

It's quite common that we have a title and card underneath and this should really be extracted into a component that accepts `React.children` prop to avoid this issue in the future so that it's possible to change only in one place when we want to further change these styles and spacings

**Comment by bosomt** [comment]
**QA OK**

0b5962f - [develop] - Fix\/UI polishment (#9213)
