### ISSUE TITLE
Coinjoin does not use lookahead, which is a problem in high-fee environment, users can't see funds

### ISSUE THREAD

**Issue by jooray** [trezor/trezor-suite#8691]
**Describe the bug**
I received coins into a coinjoin account, but they never confirmed. I generated a few addresses. I received BTC on fourth or fifth address.

I connected my Trezor to a different Trezor Suite. Because the incoming txs to the first address never confirmed, Trezor Suite does not see my funds that are on account four a further and shows zero balance. It will not even allow me to generate new address unless I receive funds to the first address.

**Info:**

-   Remembered Wallet: no
-   Suite Version: app, 23.5.2
-   OS: macOS 13.4

**How to reproduce**

1. Receive btc to the first address in coinjoin account with low fee (1sat/vB)
2. Receive btc into the second address in coinjoin account with normal fee
3. Reconnect trezor in the new installation of Trezor Suite when the first tx is out of mempool
4. No funds seen, although there are btc confirmed on the second address

**Expected behavior**
There should be some lookahead similar to normal btc account (like 10 addresses)

**Comment by matejkriz** [comment]
@jooray Thanks for well described issue, 

In Suite 23.6 (which will soon be available in the Early Access Program) there will be a new "Rescan" button in Details tab of coinjoin account that allows you to fully rescan account history without birthdate optimization so it should help in this case. 

https://github.com/trezor/trezor-suite/pull/8614

It's a compromise because private discovery of coinjoin account takes so long. We will continue to consider ways to improve this.

**Comment by hynek-jina** [comment]
Already available in 23.6 as promised
![Screenshot 2023-06-22 at 8 57 16](https://github.com/trezor/trezor-suite/assets/26002916/0633479b-65ff-4073-9bcf-db2a9c68a253)

**Comment by bosomt** [comment]
already deployed in 23.6.1 

 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
