### ISSUE TITLE
UI for message system

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#8694]
Implement UI for messaging system. Messaging system can send various types to app.

Message can include:
- Text
- Link (optional)
- Option to dismiss (close) the message

Figma: https://www.figma.com/file/xiPjYIgQtWDEhpFBwvhLlj/MobileApp-%E2%80%A2-Assorted?type=design&node-id=2007%3A39529&mode=design&t=sVGxrjZuscfyMxkq-1

Acceptance criteria:
Displayed message looks according to set up parameters:
1. Colour is changed according to severity (blue, orange, red)
2. If parameter of the message has option to close the message, user can close the message
3. If message contains link, link is displayed in the message

**Comment by tomasklim** [comment]
Low -> Info
Medium -> Warning
Critical ✅ 

Messages can be dismissible so ❌  is missing in the design because CTA button `Read` with button `Got it` will not fit.

I like the `ETH` icon next to warning icon. We do not support it now. However, I like the idea to extend message system message by some `topic` attribute.

There can be more banners valid for 1 user, it would be nice to think about stacking of banners or transition if the more prioritised one is closed.

`Force to update due to major critical bug in the app` is probably `modal` type of message. Looks like it has to be extended in message system schema. Right now it supports only `title` and `image`, it can be extended whatever you need as we do not use it in desktop app, yet
