### ISSUE TITLE
Cannot update the Suite

### ISSUE THREAD

**Issue by vladimirvolek** [trezor/trezor-suite#8803]
![image](https://github.com/trezor/trezor-suite/assets/3112191/5c7e1ac1-fb6a-4b74-8e81-40cb77635b95)

When I reload the page I can see the update again.

![image](https://github.com/trezor/trezor-suite/assets/3112191/6a850ffb-aa8e-4252-b07b-3c85d084ecc6)

After clicking the "Start Update".

![image](https://github.com/trezor/trezor-suite/assets/3112191/6d802a41-b042-49ce-a0fc-21c31471bc78)

btw! It stopped at 100% for the first time.  

![2023-06-26 14 17 32](https://github.com/trezor/trezor-suite/assets/3112191/472ec615-6dde-4e4f-85df-bce2f988cfa4)

**Comment by bosomt** [comment]
We have this open issue for reload of Suite during update: https://github.com/trezor/trezor-suite/issues/7740
And this issue was already released so i hope you wont experience issues with download during next update: https://github.com/trezor/trezor-suite/pull/8498

Performed one more update without any kind of problem during download or install.

<img width="301" alt="Screenshot 2023-07-03 at 14 01 51" src="https://github.com/trezor/trezor-suite/assets/31506317/1435b8a8-7cd2-485b-b42b-60af765f2f5b">
<img width="521" alt="Screenshot 2023-07-03 at 14 01 37" src="https://github.com/trezor/trezor-suite/assets/31506317/6200f384-644f-498b-a73d-a5144f2e1722">

**Info:**
 - Suite version: desktop 23.6.1 (bddd516378beadfcff94523e7c94834ba14f147f)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.6.1 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: BridgeTransport 2.0.33

**Comment by vladimirvolek** [comment]
I have the same version as you.
