### ISSUE TITLE
Firmware installation modal missing green close button

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#9522]
**Describe the bug**

**Info:**

-   Suite Version: 23.10.0

**How to reproduce**

1. update fw in Device Settings

**Expected behavior**

I would expect to have green closing button there and not just `X`

**Screenshots**

![Screenshot 2023-09-21 at 12 43 28](https://github.com/trezor/trezor-suite/assets/33235762/0792f8c5-192d-4c4c-89f7-d511ff7f9bca)

**Comment by matejkriz** [comment]
@trezor/qa I believe it was an issue only with T2B1 and it has been fixed by https://github.com/trezor/trezor-suite-private/commit/31f8870f40dffa4c40adae53986bbd4a8f678591 but please double check on 23.10.1 that close button is there for T2B1 and T2T1

<img width="655" alt="image" src="https://github.com/trezor/trezor-suite/assets/3729633/c13ec065-0469-473c-8348-b841562556d8">

**Comment by bosomt** [comment]
**QA OK**


**Info:**
 - Suite version: desktop 23.10.1 (6c8d061f7305947b0270a2560e4cc65d1f7ded27)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.10.1 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: Trezor T2B1 2.6.2 bitcoin-only (revision 6e5967af25de87bebd331d697e6ef940e64286ef)
 - Transport: BridgeTransport 2.0.33
