### ISSUE TITLE
Sell improvements

### ISSUE THREAD

**Issue by IvaFingerova** [trezor/trezor-suite#9579]
**Describe the bug**
- There is a misleading message once the TX is done 
- ~There is a link to support with failed TX (offer timeouted) but we can send users to the checkout, where they can finish transaction~
- ~Sorting of offers seems to be hardcoded - it should be from the best offer to the worst one by default~

**Comment by tomasklim** [comment]
@bosomt could you please check those three bullets and if they are still available, could you please create bugs?

**Comment by STew790** [comment]
I can't really see the message once Tx is done, because this is the difference between what is in the Suite vs what the provider says:
![image](https://github.com/user-attachments/assets/eb3420e3-b2d9-4591-8f2d-5f1c53f65d7f)
vs
![image](https://github.com/user-attachments/assets/617cca6e-0892-44e6-8792-420f18c6dde2)

The weird thing is, once I disconnected the device, the transaction immediately shown as approved:
![image](https://github.com/user-attachments/assets/15910f5b-49c4-4b31-8cb2-bb26fdeede90)

Also, I have to point out that I did a swap like 2 days ago and I wanted to check if that was also still "Pending" and at first, when I clicked on "Last transactions" it showed as "Pending" for like a split second and then approved and it was approved the minute I looked at it basically (according to Suite trade section but in the transactions it was approved much earlier, 2 days prior to that as I said)
![image](https://github.com/user-attachments/assets/9ec531f9-0b94-4a81-b5ea-67c1b15d92cb)

**Comment by tomasklim** [comment]
Closing because you dont get notification at all and 2 and 3 are outdated
