### ISSUE TITLE
Ethereum Staking Rewards not appearing in account balance in Trezor Suite

### ISSUE THREAD

**Issue by mnuky** [trezor/trezor-suite#9771]
From reddit (https://www.reddit.com/r/TREZOR/comments/17hf5z8/ethereum_staking_rewards_not_appearing_in_account/) It appears Trezor suite only updates the ethereum balance when a traditional on-chain transaction is detected. Since Ethereum staking rewards are different, The wallet balance does not update when I receive a staking withdraw reward. Therefore Trezor suite says I have less Ethereum in my wallet then there actually is. However, if I receive any on chain transaction afterwards, the Wallet balance refreshes and the balance shows up properly. Is there a way to manually refresh a wallets balance without having to receive an on chain transaction? Curiously, Trezor suite lite has this problem on the main page, but not when you click the balance and view it

**Comment by tomasklim** [comment]
The problem is probably here 

https://github.com/trezor/trezor-suite/blob/ea4c23d83a499c9dd73660e5d4e42498d582f288/suite-common/wallet-utils/src/accountUtils.ts#L561

We refresh account only when tx amount is changed. However, we do not see those beacon chain txs. I think the problem can also include internal transfers. 

We should take beacon chain txs and internal transfers in mind. For now probably by refreshing account when balance has been changed.
