### ISSUE TITLE
[Wallet] Send form QR code

### ISSUE THREAD

**Issue by ZdenekSL** [trezor/trezor-suite#997]
scan QR – confirm - https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bf0adb70818952a6495

Scan QR – confirmed
https://app.zeplin.io/project/5dadb7820bdfd3832e04afca/screen/5dfa1bed9c2f1097b807acee

**Comment by slowbackspace** [comment]
missing a design of an error state. Possible reasons for an error are: "Permission to access the camera was denied.", "The camera was not recognized." (could be a hw issue), or one of the other bambillions reasons (we display the message "Unknown error. See console logs for details."):

See below the screenshot how the error state is currently handled:
(there is a bug, instead of object object there should be a message)
<img width="475" alt="Screenshot 2020-01-08 at 17 25 36" src="https://user-images.githubusercontent.com/6961901/71996084-e4204200-323b-11ea-8ff9-a464b29b569a.png">

**Comment by slowbackspace** [comment]
what's the URL for "Learn more" link?
